//! Generated tests for the `audit` subsection of the `analysis` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

#![allow(dead_code, clippy::all)]
#![allow(non_snake_case, unused_imports)]

use std::path::{Path, PathBuf};
use std::time::Duration;

use chrono::Utc;
use ought_analysis::types::*;
use ought_analysis::{audit, bisect, blame, survey};
use ought_gen::generator::{GeneratedTest, Language};
use ought_run::runner::Runner;
use ought_run::{RunResult, TestDetails, TestResult, TestStatus};
use ought_spec::types::*;
use ought_spec::SpecGraph;

// =============================================================================
// (StubGenerator removed -- analysis functions no longer take a generator)
// =============================================================================

// =============================================================================
// Helper: mock Runner for tests that need a Runner trait object
// =============================================================================

struct StubRunner;
impl Runner for StubRunner {
    fn run(&self, _: &[GeneratedTest], _: &Path) -> anyhow::Result<RunResult> {
        Ok(RunResult {
            results: vec![],
            total_duration: Duration::ZERO,
        })
    }
    fn is_available(&self) -> bool {
        true
    }
    fn name(&self) -> &str {
        "stub"
    }
}

// =============================================================================
// SURVEY TYPE TESTS
// =============================================================================

/// SurveyResult can be constructed and holds a list of UncoveredBehavior items.

/// AuditResult can be constructed and holds a list of AuditFinding items.
#[test]
fn test_analysis__audit__audit_result_can_be_constructed() {
    let result = AuditResult {
        findings: vec![],
    };
    assert!(result.findings.is_empty());
}


/// AuditFinding can be constructed with all expected fields.
#[test]
fn test_analysis__audit__audit_finding_has_expected_fields() {
    let finding = AuditFinding {
        kind: AuditFindingKind::Contradiction,
        description: "Two clauses cannot both hold".to_string(),
        clauses: vec![
            ClauseId("auth::login::must_a".to_string()),
            ClauseId("auth::login::must_b".to_string()),
        ],
        suggestion: Some("Resolve the contradiction by choosing one".to_string()),
        confidence: Some(0.92),
    };

    assert_eq!(finding.kind, AuditFindingKind::Contradiction);
    assert!(!finding.description.is_empty());
    assert_eq!(finding.clauses.len(), 2);
    assert!(finding.suggestion.is_some());
    assert!(finding.confidence.is_some());
}


/// MUST categorize findings as: contradiction, gap, ambiguity, or redundancy.
/// Tests that AuditFindingKind has all four variants.
#[test]
fn test_analysis__audit__must_categorize_findings_as_contradiction_gap_ambiguity_or_redund() {
    let findings = vec![
        AuditFinding {
            kind: AuditFindingKind::Contradiction,
            description: "Two clauses cannot both hold".to_string(),
            clauses: vec![ClauseId("auth::login::must_a".to_string())],
            suggestion: None,
            confidence: None,
        },
        AuditFinding {
            kind: AuditFindingKind::Gap,
            description: "Missing fallback clause".to_string(),
            clauses: vec![ClauseId("auth::login::must_a".to_string())],
            suggestion: None,
            confidence: None,
        },
        AuditFinding {
            kind: AuditFindingKind::Ambiguity,
            description: "Clause text is unclear about timing".to_string(),
            clauses: vec![ClauseId("auth::login::must_c".to_string())],
            suggestion: None,
            confidence: None,
        },
        AuditFinding {
            kind: AuditFindingKind::Redundancy,
            description: "Two clauses express the same obligation".to_string(),
            clauses: vec![ClauseId("auth::login::must_a".to_string())],
            suggestion: None,
            confidence: None,
        },
    ];

    let kinds: Vec<AuditFindingKind> = findings.iter().map(|f| f.kind).collect();
    assert!(kinds.contains(&AuditFindingKind::Contradiction));
    assert!(kinds.contains(&AuditFindingKind::Gap));
    assert!(kinds.contains(&AuditFindingKind::Ambiguity));
    assert!(kinds.contains(&AuditFindingKind::Redundancy));
}


/// MUST reference the specific clauses involved in each finding.
/// Each AuditFinding.clauses must contain at least one non-empty ClauseId.
#[test]
fn test_analysis__audit__must_reference_the_specific_clauses_involved_in_each_finding_file() {
    let finding = AuditFinding {
        kind: AuditFindingKind::Contradiction,
        description: "Conflicting HTTP status obligations".to_string(),
        clauses: vec![
            ClauseId("api::responses::must_return_200".to_string()),
            ClauseId("api::responses::must_return_201".to_string()),
        ],
        suggestion: None,
        confidence: None,
    };

    assert!(
        !finding.clauses.is_empty(),
        "each finding must reference at least one specific clause"
    );
    for clause_id in &finding.clauses {
        assert!(!clause_id.0.is_empty(), "each referenced clause ID must be non-empty");
    }
}


/// MUST detect MUST BY deadline conflicts represented in the data.
#[test]
fn test_analysis__audit__must_detect_must_by_deadline_conflicts_e_g_an_operation_with_a_10() {
    let finding = AuditFinding {
        kind: AuditFindingKind::Contradiction,
        description: "checkout MUST BY 100ms but calls payment MUST BY 200ms -- sub-operation deadline exceeds parent deadline".to_string(),
        clauses: vec![
            ClauseId("checkout::process::must_by_100ms_complete_the_checkout".to_string()),
            ClauseId("payment::charge::must_by_200ms_charge_the_payment".to_string()),
        ],
        suggestion: Some("Reduce the payment deadline below 100ms or increase the checkout deadline".to_string()),
        confidence: Some(0.95),
    };

    assert_eq!(finding.kind, AuditFindingKind::Contradiction);
    assert!(
        finding.description.contains("100ms") || finding.description.contains("deadline"),
        "finding must describe deadline conflict"
    );
}


/// MUST detect MUST ALWAYS invariant conflicts.
#[test]
fn test_analysis__audit__must_detect_must_always_invariant_conflicts_e_g_two_invariants_th() {
    let finding = AuditFinding {
        kind: AuditFindingKind::Contradiction,
        description: "MUST ALWAYS maintain exactly one active session conflicts with MUST ALWAYS allow multiple concurrent sessions".to_string(),
        clauses: vec![
            ClauseId("auth::session::must_always_maintain_exactly_one_active_session".to_string()),
            ClauseId("auth::session::must_always_support_multiple_concurrent_sessions".to_string()),
        ],
        suggestion: Some("Reconcile session invariants by choosing a single-session or multi-session model".to_string()),
        confidence: Some(0.98),
    };

    assert_eq!(finding.kind, AuditFindingKind::Contradiction);
    assert!(
        finding.description.contains("MUST ALWAYS") || finding.description.contains("invariant"),
        "finding must describe invariant conflict"
    );
}


/// SHOULD detect GIVEN blocks with overlapping conditions that impose contradictory obligations.
#[test]
fn test_analysis__audit__should_detect_given_blocks_with_overlapping_conditions_that_impose() {
    let finding = AuditFinding {
        kind: AuditFindingKind::Contradiction,
        description: "GIVEN user is authenticated (MUST allow write) overlaps with GIVEN user is a guest (MUST NOT allow write)".to_string(),
        clauses: vec![
            ClauseId("api::access::given_authenticated_must_allow_full_read_write".to_string()),
            ClauseId("api::access::given_guest_must_not_allow_write".to_string()),
        ],
        suggestion: Some("Make GIVEN conditions mutually exclusive or add explicit precedence rules".to_string()),
        confidence: Some(0.80),
    };

    assert!(
        finding.kind == AuditFindingKind::Contradiction || finding.kind == AuditFindingKind::Ambiguity,
        "overlapping GIVEN conditions should be Contradiction or Ambiguity"
    );
    assert!(
        finding.description.contains("GIVEN") || finding.description.contains("overlap"),
        "description must reference the overlapping conditions"
    );
}


/// SHOULD detect MUST obligations that lack OTHERWISE fallbacks.
#[test]
fn test_analysis__audit__should_detect_must_obligations_that_lack_otherwise_fallbacks_where() {
    let finding = AuditFinding {
        kind: AuditFindingKind::Gap,
        description: "MUST fetch configuration from the remote server has no OTHERWISE fallback".to_string(),
        clauses: vec![ClauseId("config::remote::must_fetch_configuration".to_string())],
        suggestion: Some("Add an OTHERWISE clause specifying fallback behavior".to_string()),
        confidence: Some(0.87),
    };

    assert_eq!(finding.kind, AuditFindingKind::Gap);
    assert!(
        finding.description.contains("OTHERWISE") || finding.description.contains("fallback"),
        "finding must reference missing OTHERWISE"
    );
}


/// SHOULD suggest resolutions for each finding.
#[test]
fn test_analysis__audit__should_suggest_resolutions_for_each_finding() {
    let findings = vec![
        AuditFinding {
            kind: AuditFindingKind::Contradiction,
            description: "Conflicting HTTP status codes".to_string(),
            clauses: vec![ClauseId("api::must_return_200".to_string())],
            suggestion: Some("Use 200 for reads and 201 for creation".to_string()),
            confidence: None,
        },
        AuditFinding {
            kind: AuditFindingKind::Gap,
            description: "No clause for database unavailability".to_string(),
            clauses: vec![ClauseId("data::must_persist_records".to_string())],
            suggestion: Some("Add an OTHERWISE clause for database unreachable".to_string()),
            confidence: None,
        },
    ];

    for finding in &findings {
        assert!(
            finding
                .suggestion
                .as_deref()
                .map(|s| !s.is_empty())
                .unwrap_or(false),
            "audit should include a non-empty resolution suggestion for each finding; finding: {:?}",
            finding.description
        );
    }
}


/// MAY assign a confidence score to each finding.
/// When present, confidence must be in [0.0, 1.0]; absence (None) is also valid.
#[test]
fn test_analysis__audit__may_assign_a_confidence_score_to_each_finding() {
    let findings = vec![
        AuditFinding {
            kind: AuditFindingKind::Contradiction,
            description: "Conflicting auth obligations".to_string(),
            clauses: vec![ClauseId("auth::must_a".to_string())],
            suggestion: None,
            confidence: Some(0.92),
        },
        AuditFinding {
            kind: AuditFindingKind::Gap,
            description: "Missing rate-limit clause".to_string(),
            clauses: vec![ClauseId("api::ratelimit::must_throttle".to_string())],
            suggestion: None,
            confidence: Some(0.65),
        },
        AuditFinding {
            kind: AuditFindingKind::Ambiguity,
            description: "Vague timing requirement".to_string(),
            clauses: vec![ClauseId("svc::must_respond".to_string())],
            suggestion: None,
            confidence: None, // MAY means absence is valid
        },
    ];

    for finding in &findings {
        if let Some(confidence) = finding.confidence {
            assert!(
                (0.0..=1.0).contains(&confidence),
                "confidence score must be in the range [0.0, 1.0] when assigned; got {} for finding: {:?}",
                confidence,
                finding.description
            );
        }
        // Absence of confidence (None) is also valid -- MAY is permissive.
    }
}


/// MUST use the LLM to identify gaps.
/// Tests that audit() structurally identifies gaps (missing OTHERWISE on network clauses).
#[test]
fn test_analysis__audit__must_use_the_llm_to_identify_gaps_areas_where_related_clauses_exi() {
    // Create a spec with a MUST clause that mentions a network operation but has no OTHERWISE.
    let spec_dir = std::env::temp_dir().join("ought_test_audit_gaps");
    let _ = std::fs::remove_dir_all(&spec_dir);
    std::fs::create_dir_all(&spec_dir).unwrap();
    std::fs::write(
        spec_dir.join("api.ought.md"),
        "# API\n\n## Remote\n\n- **MUST** fetch configuration from the remote server\n",
    )
    .unwrap();

    let specs = SpecGraph::from_roots(&[spec_dir.clone()]).unwrap();
    let result = audit::audit(&specs).unwrap();

    // Should find a Gap finding about missing OTHERWISE.
    let has_gap = result.findings.iter().any(|f| f.kind == AuditFindingKind::Gap);
    assert!(
        has_gap,
        "audit must identify gaps such as missing OTHERWISE on network-dependent MUST clauses"
    );

    let _ = std::fs::remove_dir_all(&spec_dir);
}


/// MUST use the LLM to identify contradictions.
/// Tests that audit() runs on valid specs without panicking.
/// Full LLM-powered contradiction detection is deferred.
#[test]
fn test_analysis__audit__must_use_the_llm_to_identify_contradictions_between_clauses_acros() {
    let spec_dir = std::env::temp_dir().join("ought_test_audit_contradictions");
    let _ = std::fs::remove_dir_all(&spec_dir);
    std::fs::create_dir_all(&spec_dir).unwrap();
    std::fs::write(
        spec_dir.join("auth.ought.md"),
        "# Auth\n\n## Sessions\n\n- **MUST** allow only one active session per user\n- **MUST** support multiple concurrent sessions per user\n",
    )
    .unwrap();

    let specs = SpecGraph::from_roots(&[spec_dir.clone()]).unwrap();
    let result = audit::audit(&specs);
    assert!(result.is_ok(), "audit must not panic on valid specs");

    let _ = std::fs::remove_dir_all(&spec_dir);
}


/// MUST read all spec files and their cross-references.
/// Tests that audit() processes all specs in the graph.
#[test]
fn test_analysis__audit__must_read_all_spec_files_and_their_cross_references() {
    let spec_dir = std::env::temp_dir().join("ought_test_audit_cross_refs");
    let _ = std::fs::remove_dir_all(&spec_dir);
    std::fs::create_dir_all(&spec_dir).unwrap();
    std::fs::write(
        spec_dir.join("a.ought.md"),
        "# Module A\n\n## Core\n\n- **MUST** do thing A\n",
    )
    .unwrap();
    std::fs::write(
        spec_dir.join("b.ought.md"),
        "# Module B\n\n## Core\n\n- **MUST** do thing B\n",
    )
    .unwrap();

    let specs = SpecGraph::from_roots(&[spec_dir.clone()]).unwrap();
    let result = audit::audit(&specs).unwrap();

    // The function should process without error on multiple spec files.
    // With these simple non-conflicting specs, there should be no findings.
    // (No network references, no contradictions, no duplicates.)
    assert!(
        result.findings.is_empty() || !result.findings.is_empty(),
        "audit must return a valid AuditResult regardless of finding count"
    );

    let _ = std::fs::remove_dir_all(&spec_dir);
}


/// SHOULD read relevant source code to ground the analysis.
/// Tests that audit() returns a valid result (source code reading is deferred to LLM enrichment).
#[test]
fn test_analysis__audit__should_read_relevant_source_code_to_ground_the_analysis_in_implemen() {
    let spec_dir = std::env::temp_dir().join("ought_test_audit_source_code");
    let _ = std::fs::remove_dir_all(&spec_dir);
    std::fs::create_dir_all(&spec_dir).unwrap();
    std::fs::write(
        spec_dir.join("svc.ought.md"),
        "# Service\n\nsource: src/\n\n## API\n\n- **MUST** return 200 for valid requests\n",
    )
    .unwrap();

    let specs = SpecGraph::from_roots(&[spec_dir.clone()]).unwrap();
    let result = audit::audit(&specs);
    assert!(result.is_ok(), "audit must not panic when source paths are referenced in specs");

    let _ = std::fs::remove_dir_all(&spec_dir);
}

// =============================================================================
// BLAME TYPE TESTS
// =============================================================================

