//! Generated tests for the `survey` subsection of the `analysis` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

#![allow(dead_code, clippy::all)]
#![allow(non_snake_case, unused_imports)]

use std::path::{Path, PathBuf};
use std::time::Duration;

use chrono::Utc;
use ought_analysis::types::*;
use ought_analysis::{audit, bisect, blame, survey};
use ought_gen::generator::{GeneratedTest, Language};
use ought_run::runner::Runner;
use ought_run::{RunResult, TestDetails, TestResult, TestStatus};
use ought_spec::types::*;
use ought_spec::SpecGraph;

// =============================================================================
// (StubGenerator removed -- analysis functions no longer take a generator)
// =============================================================================

// =============================================================================
// Helper: mock Runner for tests that need a Runner trait object
// =============================================================================

struct StubRunner;
impl Runner for StubRunner {
    fn run(&self, _: &[GeneratedTest], _: &Path) -> anyhow::Result<RunResult> {
        Ok(RunResult {
            results: vec![],
            total_duration: Duration::ZERO,
        })
    }
    fn is_available(&self) -> bool {
        true
    }
    fn name(&self) -> &str {
        "stub"
    }
}

// =============================================================================
// SURVEY TYPE TESTS
// =============================================================================

/// SurveyResult can be constructed and holds a list of UncoveredBehavior items.

/// SurveyResult can be constructed and holds a list of UncoveredBehavior items.
#[test]
fn test_analysis__survey__survey_result_can_be_constructed() {
    let result = SurveyResult {
        uncovered: vec![],
    };
    assert!(result.uncovered.is_empty());
}


/// UncoveredBehavior can be constructed with all expected fields.
#[test]
fn test_analysis__survey__uncovered_behavior_has_expected_fields() {
    let behavior = UncoveredBehavior {
        file: PathBuf::from("src/api.rs"),
        line: 42,
        description: "create_user has no clause".to_string(),
        suggested_clause: "MUST create a user with the given name".to_string(),
        suggested_keyword: Keyword::Must,
        suggested_spec: PathBuf::from("ought/api.ought.md"),
    };

    assert_eq!(behavior.file, PathBuf::from("src/api.rs"));
    assert_eq!(behavior.line, 42);
    assert!(!behavior.description.is_empty());
    assert!(!behavior.suggested_clause.is_empty());
    assert_eq!(behavior.suggested_keyword, Keyword::Must);
    assert_eq!(behavior.suggested_spec, PathBuf::from("ought/api.ought.md"));
}


/// MUST output a list of uncovered behaviors with file and line references.
/// Tests the UncoveredBehavior structure carries non-empty file and positive line.
#[test]
fn test_analysis__survey__must_output_a_list_of_uncovered_behaviors_with_file_and_line_refe() {
    let behaviors = vec![
        UncoveredBehavior {
            file: PathBuf::from("src/api.rs"),
            line: 1,
            description: "create_user has no clause".to_string(),
            suggested_clause: "MUST create a user with the given name".to_string(),
            suggested_keyword: Keyword::Must,
            suggested_spec: PathBuf::from("ought/api.ought.md"),
        },
        UncoveredBehavior {
            file: PathBuf::from("src/api.rs"),
            line: 2,
            description: "delete_user has no clause".to_string(),
            suggested_clause: "MUST delete the user with the given id".to_string(),
            suggested_keyword: Keyword::Must,
            suggested_spec: PathBuf::from("ought/api.ought.md"),
        },
    ];

    let result = SurveyResult {
        uncovered: behaviors,
    };

    assert!(!result.uncovered.is_empty(), "survey must output at least one uncovered behavior");
    for b in &result.uncovered {
        assert!(
            b.file != PathBuf::from(""),
            "each uncovered behavior must include a non-empty file path"
        );
        assert!(
            b.line > 0,
            "each uncovered behavior must include a positive line reference; got line {}",
            b.line
        );
    }
}


/// MUST suggest concrete clause text with appropriate keyword for each uncovered behavior.
/// All behavioral keywords (not structural ones like Given/Otherwise) are valid.
#[test]
fn test_analysis__survey__must_suggest_concrete_clause_text_with_appropriate_keyword_for_ea() {
    const BEHAVIORAL_KEYWORDS: &[Keyword] = &[
        Keyword::Must,
        Keyword::MustNot,
        Keyword::Should,
        Keyword::ShouldNot,
        Keyword::May,
        Keyword::Wont,
        Keyword::MustAlways,
        Keyword::MustBy,
    ];

    let behaviors = vec![
        UncoveredBehavior {
            file: PathBuf::from("src/service.rs"),
            line: 1,
            description: "process_payment uncovered".to_string(),
            suggested_clause: "MUST process the payment and return success status".to_string(),
            suggested_keyword: Keyword::Must,
            suggested_spec: PathBuf::from("ought/svc.ought.md"),
        },
        UncoveredBehavior {
            file: PathBuf::from("src/service.rs"),
            line: 1,
            description: "payment error path".to_string(),
            suggested_clause: "SHOULD return false when payment fails".to_string(),
            suggested_keyword: Keyword::Should,
            suggested_spec: PathBuf::from("ought/svc.ought.md"),
        },
    ];

    for b in &behaviors {
        assert!(
            !b.suggested_clause.is_empty(),
            "suggested_clause must be non-empty for every uncovered behavior"
        );
        assert!(
            BEHAVIORAL_KEYWORDS.contains(&b.suggested_keyword),
            "suggested_keyword {:?} must be a deontic behavioral keyword, not structural",
            b.suggested_keyword
        );
    }
}


/// SHOULD group suggestions by the spec file they would belong to.
/// Behaviors for the same suggested_spec should appear adjacent.
#[test]
fn test_analysis__survey__should_group_suggestions_by_the_spec_file_they_would_belong_to() {
    let behaviors = vec![
        UncoveredBehavior {
            file: PathBuf::from("src/lib.rs"),
            line: 1,
            description: "auth_login uncovered".to_string(),
            suggested_clause: "MUST authenticate the user on login".to_string(),
            suggested_keyword: Keyword::Must,
            suggested_spec: PathBuf::from("auth.ought.md"),
        },
        UncoveredBehavior {
            file: PathBuf::from("src/lib.rs"),
            line: 2,
            description: "auth_logout uncovered".to_string(),
            suggested_clause: "MUST invalidate session on logout".to_string(),
            suggested_keyword: Keyword::Must,
            suggested_spec: PathBuf::from("auth.ought.md"),
        },
        UncoveredBehavior {
            file: PathBuf::from("src/lib.rs"),
            line: 3,
            description: "billing_charge uncovered".to_string(),
            suggested_clause: "MUST charge the correct amount".to_string(),
            suggested_keyword: Keyword::Must,
            suggested_spec: PathBuf::from("billing.ought.md"),
        },
    ];

    let result = SurveyResult {
        uncovered: behaviors,
    };

    assert_eq!(result.uncovered.len(), 3, "all three behaviors must be reported");

    // Verify grouping: behaviors for the same spec file are adjacent.
    let mut seen_specs: Vec<PathBuf> = Vec::new();
    let mut last_spec: Option<PathBuf> = None;
    for b in &result.uncovered {
        if last_spec.as_ref() != Some(&b.suggested_spec) {
            assert!(
                !seen_specs.contains(&b.suggested_spec),
                "behaviors for {:?} are not grouped -- they appear interleaved with other spec files",
                b.suggested_spec
            );
            if let Some(prev) = last_spec.take() {
                seen_specs.push(prev);
            }
            last_spec = Some(b.suggested_spec.clone());
        }
    }
}


/// SHOULD offer to append suggested clauses to the relevant spec file.
/// Each UncoveredBehavior must carry a non-empty suggested_spec path.
#[test]
fn test_analysis__survey__should_offer_to_append_suggested_clauses_to_the_relevant_spec_file() {
    let behavior = UncoveredBehavior {
        file: PathBuf::from("src/router.rs"),
        line: 1,
        description: "route function uncovered".to_string(),
        suggested_clause: "MUST dispatch requests to the correct handler".to_string(),
        suggested_keyword: Keyword::Must,
        suggested_spec: PathBuf::from("specs/router.ought.md"),
    };

    assert!(
        behavior.suggested_spec != PathBuf::from(""),
        "every uncovered behavior must include a suggested_spec path for append-offer"
    );
}


/// SHOULD rank uncovered behaviors by risk (public API > internal helper).
/// The type supports this ordering via the data it stores.
#[test]
fn test_analysis__survey__should_rank_uncovered_behaviors_by_risk_public_api_internal_helper() {
    let public_behavior = UncoveredBehavior {
        file: PathBuf::from("src/lib.rs"),
        line: 1,
        description: "public_process (public API)".to_string(),
        suggested_clause: "MUST process data and return result".to_string(),
        suggested_keyword: Keyword::Must,
        suggested_spec: PathBuf::from("ought/svc.ought.md"),
    };
    let private_behavior = UncoveredBehavior {
        file: PathBuf::from("src/lib.rs"),
        line: 2,
        description: "private_validate (internal helper)".to_string(),
        suggested_clause: "SHOULD validate non-empty data".to_string(),
        suggested_keyword: Keyword::Should,
        suggested_spec: PathBuf::from("ought/svc.ought.md"),
    };

    // When the result ranks public first, public API appears before internal helper.
    let result = SurveyResult {
        uncovered: vec![public_behavior, private_behavior],
    };

    assert_eq!(result.uncovered.len(), 2);
    let first = &result.uncovered[0];
    let second = &result.uncovered[1];
    assert!(
        first.description.contains("public"),
        "public API behavior must rank first; got description: {:?}",
        first.description
    );
    assert!(
        second.description.contains("private"),
        "internal helper must rank second; got description: {:?}",
        second.description
    );
}


/// WONT auto-add clauses without user confirmation.
/// survey() returns SurveyResult; it does not modify spec files on disk.
/// The type has no side-effect fields -- it only carries suggestions.
#[test]
fn test_analysis__survey__wont_auto_add_clauses_without_user_confirmation() {
    let result = SurveyResult {
        uncovered: vec![UncoveredBehavior {
            file: PathBuf::from("src/lib.rs"),
            line: 1,
            description: "uncovered_fn has no clause".to_string(),
            suggested_clause: "MUST implement uncovered_fn".to_string(),
            suggested_keyword: Keyword::Must,
            suggested_spec: PathBuf::from("specs/svc.ought.md"),
        }],
    };

    // SurveyResult only carries data (suggestions), no mutation methods.
    // This confirms the type design prevents auto-modification.
    assert!(
        !result.uncovered.is_empty(),
        "survey must still return suggestions even though it does not write them"
    );
}


/// MUST read source files from the given path or project source root.
/// Tests that survey() reads source files and returns results without panicking.
#[test]
fn test_analysis__survey__must_read_source_files_from_the_given_path_or_project_source_root() {
    // Create a temp directory with a source file containing a public function.
    let tmp = std::env::temp_dir().join("ought_test_survey_source");
    let _ = std::fs::remove_dir_all(&tmp);
    std::fs::create_dir_all(&tmp).unwrap();
    std::fs::write(
        tmp.join("example.rs"),
        "pub fn uncovered_function() {\n    // does something\n}\n",
    )
    .unwrap();

    // Use an empty spec graph (no specs directory needed).
    let empty_dir = std::env::temp_dir().join("ought_test_survey_empty_specs");
    let _ = std::fs::remove_dir_all(&empty_dir);
    std::fs::create_dir_all(&empty_dir).unwrap();
    let specs = SpecGraph::from_roots(&[empty_dir.clone()]).unwrap();
    let result = survey::survey(&specs, &[tmp.clone()]).unwrap();

    // Should find the uncovered function.
    assert!(
        !result.uncovered.is_empty(),
        "survey must discover uncovered behaviors from source files"
    );
    assert!(
        result.uncovered.iter().any(|u| u.description.contains("uncovered_function")),
        "survey must find 'uncovered_function' in the source file"
    );

    // Cleanup.
    let _ = std::fs::remove_dir_all(&tmp);
    let _ = std::fs::remove_dir_all(&empty_dir);
}


/// MUST read all existing spec files to know what is already covered.
/// Tests that survey() considers existing clauses and does not report them as uncovered.
#[test]
fn test_analysis__survey__must_read_all_existing_spec_files_to_know_what_is_already_covered() {
    // Create a temp directory with a source file containing a function.
    let tmp = std::env::temp_dir().join("ought_test_survey_covered");
    let _ = std::fs::remove_dir_all(&tmp);
    std::fs::create_dir_all(&tmp).unwrap();
    std::fs::write(
        tmp.join("example.rs"),
        "pub fn create_user() {\n    // creates a user\n}\npub fn delete_user() {\n    // deletes a user\n}\n",
    )
    .unwrap();

    // Create a spec that covers "create_user".
    let spec_dir = std::env::temp_dir().join("ought_test_survey_covered_specs");
    let _ = std::fs::remove_dir_all(&spec_dir);
    std::fs::create_dir_all(&spec_dir).unwrap();
    std::fs::write(
        spec_dir.join("api.ought.md"),
        "# API\n\n## Users\n\n- **MUST** create_user and return the new user id\n",
    )
    .unwrap();

    let specs = SpecGraph::from_roots(&[spec_dir.clone()]).unwrap();
    let result = survey::survey(&specs, &[tmp.clone()]).unwrap();

    // "create_user" should NOT appear in uncovered (it's covered by the clause).
    let has_create = result.uncovered.iter().any(|u| u.description.contains("create_user"));
    assert!(
        !has_create,
        "survey must not report 'create_user' as uncovered when a clause mentions it"
    );

    // "delete_user" should appear (no clause mentions it).
    let has_delete = result.uncovered.iter().any(|u| u.description.contains("delete_user"));
    assert!(
        has_delete,
        "survey must report 'delete_user' as uncovered since no clause mentions it"
    );

    // Cleanup.
    let _ = std::fs::remove_dir_all(&tmp);
    let _ = std::fs::remove_dir_all(&spec_dir);
}


/// MUST use the LLM to identify public behaviors, APIs, and logic branches.
/// Tests that survey() at minimum identifies public function signatures structurally.
/// LLM enrichment is deferred to a future release, but structural analysis works.
#[test]
fn test_analysis__survey__must_use_the_llm_to_identify_public_behaviors_apis_and_logic_bran() {
    let tmp = std::env::temp_dir().join("ought_test_survey_public");
    let _ = std::fs::remove_dir_all(&tmp);
    std::fs::create_dir_all(&tmp).unwrap();
    std::fs::write(
        tmp.join("service.rs"),
        "pub fn public_api_method() {}\nfn private_helper() {}\n",
    )
    .unwrap();

    let spec_dir = std::env::temp_dir().join("ought_test_survey_public_specs");
    let _ = std::fs::remove_dir_all(&spec_dir);
    std::fs::create_dir_all(&spec_dir).unwrap();
    let specs = SpecGraph::from_roots(&[spec_dir.clone()]).unwrap();
    let result = survey::survey(&specs, &[tmp.clone()]).unwrap();

    // Should identify the public method.
    let public_found = result.uncovered.iter().any(|u| u.description.contains("public_api_method"));
    assert!(
        public_found,
        "survey must identify public function signatures from source files"
    );

    // Cleanup.
    let _ = std::fs::remove_dir_all(&tmp);
    let _ = std::fs::remove_dir_all(&spec_dir);
}

// =============================================================================
// AUDIT TYPE TESTS
// =============================================================================

