//! Generated tests for the `traits` subsection of the `analysis` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

#![allow(dead_code, clippy::all)]
#![allow(non_snake_case, unused_imports)]

use std::path::{Path, PathBuf};
use std::time::Duration;

use chrono::Utc;
use ought_analysis::types::*;
use ought_analysis::{audit, bisect, blame, survey};
use ought_gen::generator::{GeneratedTest, Language};
use ought_run::runner::Runner;
use ought_run::{RunResult, TestDetails, TestResult, TestStatus};
use ought_spec::types::*;
use ought_spec::SpecGraph;

// =============================================================================
// (StubGenerator removed -- analysis functions no longer take a generator)
// =============================================================================

// =============================================================================
// Helper: mock Runner for tests that need a Runner trait object
// =============================================================================

struct StubRunner;
impl Runner for StubRunner {
    fn run(&self, _: &[GeneratedTest], _: &Path) -> anyhow::Result<RunResult> {
        Ok(RunResult {
            results: vec![],
            total_duration: Duration::ZERO,
        })
    }
    fn is_available(&self) -> bool {
        true
    }
    fn name(&self) -> &str {
        "stub"
    }
}

// =============================================================================
// SURVEY TYPE TESTS
// =============================================================================

/// SurveyResult can be constructed and holds a list of UncoveredBehavior items.

/// The Runner trait can be implemented with a mock.
#[test]
fn test_analysis__traits__runner_trait_can_be_implemented() {
    let runner = StubRunner;
    assert!(runner.is_available());
    assert_eq!(runner.name(), "stub");

    let result = runner.run(&[], Path::new("/tmp"));
    assert!(result.is_ok(), "mock runner must succeed");
    let run_result = result.unwrap();
    assert!(run_result.results.is_empty());
    assert_eq!(run_result.total_duration, Duration::ZERO);
}


/// The Runner trait is object-safe (can be used as dyn Runner).
#[test]
fn test_analysis__traits__runner_is_object_safe() {
    let runner: Box<dyn Runner> = Box::new(StubRunner);
    assert!(runner.is_available());
    assert_eq!(runner.name(), "stub");
}

// =============================================================================
// FUNCTION SIGNATURE TESTS -- verify the analysis functions exist with correct types
// =============================================================================

