//! Generated tests for the `implementation` subsection of the `ought` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use ought_cli::config::Config;
use ought_spec::{OughtMdParser, Parser, SpecGraph};
use ought_spec::types::*;

use crate::helpers::{
    ought_bin, scaffold_project, unique_dir, walkdir, write_spec, write_test,
};

/// MUST be written in Rust
#[test]
fn test_ought__implementation__must_be_written_in_rust() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR must be set by cargo");

    let mut dir = Path::new(&manifest_dir).to_path_buf();
    let mut found_workspace = false;

    loop {
        let candidate = dir.join("Cargo.toml");
        if candidate.exists() {
            let contents = fs::read_to_string(&candidate).expect("failed to read Cargo.toml");
            if contents.contains("[workspace]") {
                found_workspace = true;
                break;
            }
        }
        if !dir.pop() { break; }
    }

    assert!(found_workspace,
        "Expected to find a Cargo.toml with a [workspace] section, confirming the project is written in Rust");
}

/// SHOULD use a workspace structure so components can be used independently
#[test]
fn test_ought__implementation__should_use_a_workspace_structure_so_components_can_be_used_independ() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR must be set by cargo");

    let mut workspace_root = Path::new(&manifest_dir).to_path_buf();
    let workspace_toml;
    loop {
        let candidate = workspace_root.join("Cargo.toml");
        if candidate.exists() {
            let contents = fs::read_to_string(&candidate).expect("failed to read Cargo.toml");
            if contents.contains("[workspace]") {
                workspace_toml = contents;
                break;
            }
        }
        assert!(workspace_root.pop(), "Could not find workspace root from CARGO_MANIFEST_DIR");
    }

    let member_lines: Vec<&str> = workspace_toml.lines()
        .filter(|l| {
            let trimmed = l.trim();
            (trimmed.starts_with('"') && trimmed.ends_with("\","))
                || (trimmed.starts_with('"') && trimmed.ends_with('"'))
        })
        .collect();

    let members: Vec<String> = member_lines.iter()
        .map(|l| l.trim().trim_matches('"').trim_end_matches(',').trim_matches('"').to_string())
        .filter(|s| !s.is_empty())
        .collect();

    assert!(members.len() >= 2,
        "Workspace should declare at least 2 members; found {} member(s).", members.len());

    for member in &members {
        let member_manifest = workspace_root.join(member).join("Cargo.toml");
        assert!(member_manifest.exists(),
            "Workspace member '{}' does not have its own Cargo.toml at '{}'",
            member, member_manifest.display());
    }
}

/// MUST publish the spec parser as a standalone crate (ought-spec) with no LLM dependencies
#[test]
fn test_ought__implementation__must_publish_the_spec_parser_as_a_standalone_crate_ought_spec_wit() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR must be set by cargo");

    let mut workspace_root = Path::new(&manifest_dir).to_path_buf();
    loop {
        let candidate = workspace_root.join("Cargo.toml");
        if candidate.exists() {
            let contents = fs::read_to_string(&candidate).expect("failed to read Cargo.toml");
            if contents.contains("[workspace]") { break; }
        }
        assert!(workspace_root.pop(), "Could not find workspace root from CARGO_MANIFEST_DIR");
    }

    let candidates = [
        workspace_root.join("crates").join("ought-spec").join("Cargo.toml"),
        workspace_root.join("ought-spec").join("Cargo.toml"),
    ];

    let spec_manifest_path = candidates.iter().find(|p| p.exists())
        .expect("ought-spec crate not found; expected at crates/ought-spec/Cargo.toml");

    let spec_manifest = fs::read_to_string(spec_manifest_path)
        .expect("failed to read ought-spec/Cargo.toml");

    assert!(spec_manifest.contains("name = \"ought-spec\""),
        "ought-spec/Cargo.toml should declare name = \"ought-spec\"");

    let llm_deps = ["openai", "anthropic", "mistral", "\"llm\"", "langchain", "rig", "llama", "ollama", "genai", "async-openai"];
    for dep in &llm_deps {
        assert!(!spec_manifest.contains(dep),
            "ought-spec/Cargo.toml must not depend on LLM library '{}', but it was found in the manifest", dep);
    }
}

// ===========================================================================
// generated_test_management
// ===========================================================================

