//! Generated tests for the `language_agnostic` subsection of the `ought` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.
//! (Hand-updated once for the generic-CLI-runner refactor; safe to regenerate.)

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use ought_cli::config::Config;
use ought_spec::{OughtMdParser, Parser, SpecGraph};
use ought_spec::types::*;

use crate::helpers::{
    ought_bin, scaffold_project, unique_dir, walkdir, write_spec, write_test,
};

/// Build a runner for a language by filling in just the `test_dir` over its
/// preset — matches the minimal `[runner.<name>]` form documented in
/// `ought.toml`.
fn runner_for(lang: &str) -> anyhow::Result<Box<dyn ought_run::Runner>> {
    let cfg = ought_run::RunnerConfig {
        test_dir: Some(PathBuf::from("ought/ought-gen/")),
        ..Default::default()
    };
    ought_run::runners::from_config(lang, &cfg, Path::new("."))
}

/// MUST be agnostic to the programming language of the project under test
#[test]
fn test_ought__language_agnostic__must_be_agnostic_to_the_programming_language_of_the_project_under() {
    let languages = ["rust", "python", "typescript", "go"];
    for lang in languages {
        let runner = runner_for(lang)
            .unwrap_or_else(|e| panic!("runner_for({lang:?}) failed: {e}"));
        let name: &str = runner.name();
        let _available: bool = runner.is_available();
        assert_eq!(name, lang, "runner created for {lang:?} must report that same name back");
    }

    // Unknown language: must fail to resolve a preset.
    let unknown_cfg = ought_run::RunnerConfig {
        test_dir: Some(PathBuf::from("ought/ought-gen/")),
        ..Default::default()
    };
    let unknown = ought_run::runners::from_config("cobol", &unknown_cfg, Path::new("."));
    assert!(unknown.is_err(), "unknown language with no preset and no command must return Err");

    let runners: Vec<_> = languages.iter().map(|lang| runner_for(lang).unwrap()).collect();
    let names: std::collections::HashSet<String> =
        runners.iter().map(|r| r.name().to_string()).collect();
    assert_eq!(names.len(), languages.len(), "all supported runner names must be distinct");
}

/// MUST delegate test execution to the project's existing test harness
#[test]
fn test_ought__language_agnostic__must_delegate_test_execution_to_the_project_s_existing_test_harne() {
    // Each preset should ultimately spawn one of these well-known harness
    // binaries — we verify the preset resolves to a command whose first
    // token matches expectations.
    let harness_map: &[(&str, &[&str])] = &[
        ("rust",       &["cargo"]),                // `cargo nextest run ...`
        ("python",     &["pytest"]),
        ("typescript", &["npx"]),
        ("go",         &["gotestsum", "go"]),
    ];

    for (lang, harness_hints) in harness_map {
        let preset = ought_run::presets::preset(lang)
            .unwrap_or_else(|| panic!("preset for {lang:?} must exist"));
        let command = preset
            .command
            .as_deref()
            .unwrap_or_else(|| panic!("{lang:?} preset must have a command"));
        let first_token = command.split_whitespace().next().unwrap_or("");
        assert!(
            harness_hints.contains(&first_token),
            "runner for {lang} must delegate to one of {harness_hints:?}, got {first_token}"
        );
    }

    // Each preset's first-token binary must be distinct from the others
    // (excluding the `go` preset which is allowed to use either `gotestsum`
    // or `go` — harness_hints above captures that).
    let unique: std::collections::HashSet<&str> = harness_map
        .iter()
        .map(|(_, h)| h[0])
        .collect();
    assert_eq!(unique.len(), harness_map.len(),
        "each runner's primary harness binary must be distinct");
}

/// MUST ship with runners for at least Rust and one other mainstream language
#[test]
fn test_ought__language_agnostic__must_ship_with_runners_for_at_least_rust_and_one_other_mainstream() {
    let rust_runner = runner_for("rust")
        .expect("Rust runner must be included");
    assert_eq!(rust_runner.name(), "rust");

    let other_mainstream = ["python", "typescript", "go", "javascript"];
    let available_others: Vec<&str> = other_mainstream.iter().copied()
        .filter(|lang| runner_for(lang).is_ok())
        .collect();

    assert!(!available_others.is_empty(),
        "at least one non-Rust mainstream runner must ship; tried {:?}", other_mainstream);
}

/// MUST NOT require any language-specific SDK or library in the project under test
#[test]
fn test_ought__language_agnostic__must_not_require_any_language_specific_sdk_or_library_in_the_project() {
    use ought_run::RunnerConfig;
    use ought_gen::GeneratedTest;
    use ought_gen::generator::Language;

    // A fully custom runner config (no preset) is accepted without ought
    // depending on ruby at build time.
    let ruby_cfg = RunnerConfig {
        command: Some("bundle exec rspec --format=junit --out={junit_path}".to_string()),
        test_dir: Some(PathBuf::from("spec/ought/")),
        format: Some(ought_run::OutputFormat::JunitXml),
        file_extensions: Some(vec!["rb".to_string()]),
        ..Default::default()
    };
    let resolved = ruby_cfg.resolve("ruby").expect("ruby config must resolve");
    assert_eq!(resolved.command, "bundle exec rspec --format=junit --out={junit_path}");

    let rust_test = GeneratedTest {
        clause_id: ClauseId("example::must_add".to_string()),
        code: "#[test]\nfn test_example__must_add() { assert_eq!(1 + 1, 2); }".to_string(),
        language: Language::Rust,
        file_path: PathBuf::from("test_example__must_add.rs"),
    };
    assert!(!rust_test.code.contains("use ought"), "generated Rust test must not require ought imports");
    assert!(!rust_test.code.contains("extern crate ought"), "generated Rust test must not require ought crate");

    let python_test = GeneratedTest {
        clause_id: ClauseId("example::must_add_python".to_string()),
        code: "def test_example__must_add():\n    assert 1 + 1 == 2".to_string(),
        language: Language::Python,
        file_path: PathBuf::from("test_example__must_add.py"),
    };
    assert!(!python_test.code.contains("import ought"), "generated Python test must not require ought import");
}

/// SHOULD support custom runners via configuration
#[test]
fn test_ought__language_agnostic__should_support_custom_runners_via_configuration() {
    use ought_cli::config::Config;

    let toml_str = r#"
[project]
name = "custom-runner-test"
version = "0.1.0"

[generator]
provider = "anthropic"

[runner.elixir]
command = "mix test"
test_dir = "test/ought/"
format = "junit-xml"
file_extensions = ["ex", "exs"]

[runner.ruby]
command = "bundle exec rspec"
test_dir = "spec/ought/"
format = "junit-xml"
file_extensions = ["rb"]

[runner.dotnet]
command = "dotnet test"
test_dir = "tests/ought/"
format = "junit-xml"
file_extensions = ["cs"]
"#;

    let tmp = std::env::temp_dir().join(format!("ought_custom_runner_cfg_{}", std::process::id()));
    fs::create_dir_all(&tmp).unwrap();
    let cfg_path = tmp.join("ought.toml");
    fs::write(&cfg_path, toml_str).unwrap();

    let config = Config::load(&cfg_path)
        .expect("ought.toml with custom [runner.*] sections must parse without error");

    assert_eq!(config.runner.len(), 3,
        "all custom runner sections must be present after parsing; found keys: {:?}",
        config.runner.keys().collect::<Vec<_>>());

    let elixir = config.runner.get("elixir").expect("runner 'elixir' must be accepted");
    assert_eq!(elixir.command.as_deref(), Some("mix test"));
    assert_eq!(
        elixir.test_dir.as_ref().unwrap().to_string_lossy(),
        "test/ought/"
    );

    let ruby = config.runner.get("ruby").expect("runner 'ruby' must be accepted");
    assert_eq!(ruby.command.as_deref(), Some("bundle exec rspec"));

    let dotnet = config.runner.get("dotnet").expect("runner 'dotnet' must be accepted");
    assert_eq!(dotnet.command.as_deref(), Some("dotnet test"));

    let _ = fs::remove_dir_all(&tmp);
}

// ===========================================================================
// reporting
// ===========================================================================
