//! Generated tests for the `language_agnostic` subsection of the `ought` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use ought_cli::config::Config;
use ought_spec::{OughtMdParser, Parser, SpecGraph};
use ought_spec::types::*;

use crate::helpers::{
    ought_bin, scaffold_project, unique_dir, walkdir, write_spec, write_test,
};

/// MUST be agnostic to the programming language of the project under test
#[test]
fn test_ought__language_agnostic__must_be_agnostic_to_the_programming_language_of_the_project_under() {
    let languages = ["rust", "python", "typescript", "go"];
    for lang in languages {
        let runner = ought_run::runners::from_name(lang)
            .unwrap_or_else(|e| panic!("from_name({lang:?}) failed: {e}"));
        let name: &str = runner.name();
        let _available: bool = runner.is_available();
        assert_eq!(name, lang, "runner created for {lang:?} must report that same name back");
    }

    let unknown = ought_run::runners::from_name("cobol");
    assert!(unknown.is_err(), "from_name with an unrecognised language must return Err");

    let runners: Vec<_> = languages.iter().map(|lang| ought_run::runners::from_name(lang).unwrap()).collect();
    let names: std::collections::HashSet<&str> = runners.iter().map(|r| r.name()).collect();
    assert_eq!(names.len(), languages.len(), "all supported runner names must be distinct");
}

/// MUST delegate test execution to the project's existing test harness
#[test]
fn test_ought__language_agnostic__must_delegate_test_execution_to_the_project_s_existing_test_harne() {
    let harness_map: &[(&str, &str)] = &[
        ("rust",       "cargo"),
        ("python",     "pytest"),
        ("typescript", "npx"),
        ("go",         "go"),
    ];

    for (lang, harness_hint) in harness_map {
        let runner = ought_run::runners::from_name(lang)
            .unwrap_or_else(|e| panic!("from_name({lang:?}) must succeed: {e}"));
        assert_eq!(runner.name(), *lang);
        let _available: bool = runner.is_available();
        assert!(!harness_hint.is_empty());
    }

    let unique_harnesses: std::collections::HashSet<&str> = harness_map.iter().map(|(_, h)| *h).collect();
    assert_eq!(unique_harnesses.len(), harness_map.len(),
        "each runner must delegate to a distinct harness binary");
}

/// MUST ship with runners for at least Rust and one other mainstream language
#[test]
fn test_ought__language_agnostic__must_ship_with_runners_for_at_least_rust_and_one_other_mainstream() {
    let rust_runner = ought_run::runners::from_name("rust")
        .expect("Rust runner must be included");
    assert_eq!(rust_runner.name(), "rust");

    let other_mainstream = ["python", "typescript", "go", "javascript"];
    let available_others: Vec<&str> = other_mainstream.iter().copied()
        .filter(|lang| ought_run::runners::from_name(lang).is_ok())
        .collect();

    assert!(!available_others.is_empty(),
        "at least one non-Rust mainstream runner must ship; tried {:?}", other_mainstream);
}

/// MUST NOT require any language-specific SDK or library in the project under test
#[test]
fn test_ought__language_agnostic__must_not_require_any_language_specific_sdk_or_library_in_the_project() {
    use ought_run::RunnerConfig;
    use ought_gen::GeneratedTest;
    use ought_gen::generator::Language;

    let ruby_cfg = RunnerConfig {
        command: "bundle exec rspec".to_string(),
        test_dir: PathBuf::from("spec/ought/"),
    };
    assert_eq!(ruby_cfg.command, "bundle exec rspec");

    let rust_test = GeneratedTest {
        clause_id: ClauseId("example::must_add".to_string()),
        code: "#[test]\nfn test_example__must_add() { assert_eq!(1 + 1, 2); }".to_string(),
        language: Language::Rust,
        file_path: PathBuf::from("test_example__must_add.rs"),
    };
    assert!(!rust_test.code.contains("use ought"), "generated Rust test must not require ought imports");
    assert!(!rust_test.code.contains("extern crate ought"), "generated Rust test must not require ought crate");

    let python_test = GeneratedTest {
        clause_id: ClauseId("example::must_add_python".to_string()),
        code: "def test_example__must_add():\n    assert 1 + 1 == 2".to_string(),
        language: Language::Python,
        file_path: PathBuf::from("test_example__must_add.py"),
    };
    assert!(!python_test.code.contains("import ought"), "generated Python test must not require ought import");
}

/// SHOULD support custom runners via configuration
#[test]
fn test_ought__language_agnostic__should_support_custom_runners_via_configuration() {
    use ought_cli::config::Config;

    let toml_str = r#"
[project]
name = "custom-runner-test"
version = "0.1.0"

[generator]
provider = "anthropic"

[runner.elixir]
command = "mix test"
test_dir = "test/ought/"

[runner.ruby]
command = "bundle exec rspec"
test_dir = "spec/ought/"

[runner.dotnet]
command = "dotnet test"
test_dir = "tests/ought/"
"#;

    let tmp = std::env::temp_dir().join(format!("ought_custom_runner_cfg_{}", std::process::id()));
    fs::create_dir_all(&tmp).unwrap();
    let cfg_path = tmp.join("ought.toml");
    fs::write(&cfg_path, toml_str).unwrap();

    let config = Config::load(&cfg_path)
        .expect("ought.toml with custom [runner.*] sections must parse without error");

    assert_eq!(config.runner.len(), 3,
        "all custom runner sections must be present after parsing; found keys: {:?}",
        config.runner.keys().collect::<Vec<_>>());

    let elixir = config.runner.get("elixir").expect("runner 'elixir' must be accepted");
    assert_eq!(elixir.command, "mix test");
    assert_eq!(elixir.test_dir.to_string_lossy(), "test/ought/");

    let ruby = config.runner.get("ruby").expect("runner 'ruby' must be accepted");
    assert_eq!(ruby.command, "bundle exec rspec");

    let dotnet = config.runner.get("dotnet").expect("runner 'dotnet' must be accepted");
    assert_eq!(dotnet.command, "dotnet test");

    let _ = fs::remove_dir_all(&tmp);
}

// ===========================================================================
// reporting
// ===========================================================================

