//! Generated tests for the `llm_agnostic` subsection of the `ought` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use ought_cli::config::Config;
use ought_spec::{OughtMdParser, Parser, SpecGraph};
use ought_spec::types::*;

use crate::helpers::{
    ought_bin, scaffold_project, unique_dir, walkdir, write_spec, write_test,
};

/// MUST be agnostic to which LLM provider generates the test code
#[test]
fn test_ought__llm_agnostic__must_be_agnostic_to_which_llm_provider_generates_the_test_code() {
    use ought_gen::generator::{GeneratedTest, Language};

    // The GeneratedTest struct carries no provider information -- it is purely
    // a (clause_id, code, language, file_path) tuple. This proves provider agnosticism.
    let test_a = GeneratedTest {
        clause_id: ClauseId("ought::llm_agnostic::agnostic_clause".to_string()),
        code: "// generated by provider_a\n#[test]\nfn test_x() { assert!(true); }".to_string(),
        language: Language::Rust,
        file_path: PathBuf::from("x_test.rs"),
    };
    let test_b = GeneratedTest {
        clause_id: ClauseId("ought::llm_agnostic::agnostic_clause".to_string()),
        code: "// generated by provider_b\n#[test]\nfn test_x() { assert!(true); }".to_string(),
        language: Language::Rust,
        file_path: PathBuf::from("x_test.rs"),
    };

    // Both tests have the same clause_id and language regardless of which provider produced them.
    assert_eq!(test_a.clause_id, test_b.clause_id);
    assert_eq!(test_a.language, test_b.language);
}

/// MUST allow the provider and model to be configured in `ought.toml`
#[test]
fn test_ought__llm_agnostic__must_allow_the_provider_and_model_to_be_configured_in_ought_toml() {
    use ought_cli::config::Config;

    let dir = std::env::temp_dir().join(format!("ought_llm_agnostic_config_test_{}", std::process::id()));
    fs::create_dir_all(&dir).expect("must create temp dir");

    // Provider is a typed enum in the config surface; the TOML value is
    // the lowercase variant name. When `model` is omitted, the config
    // falls back to the default model string (no longer Option<String>).
    use ought_gen::Provider;
    let cases: &[(&str, Provider, Option<&str>)] = &[
        ("anthropic", Provider::Anthropic, Some("claude-sonnet-4-6")),
        ("anthropic", Provider::Anthropic, Some("claude-opus-4-6")),
        ("openai", Provider::Openai, Some("gpt-4o")),
        ("openai", Provider::Openai, Some("gpt-4o-mini")),
        ("openrouter", Provider::Openrouter, Some("openrouter/auto")),
        ("ollama", Provider::Ollama, Some("llama3")),
        ("ollama", Provider::Ollama, None),
        ("anthropic", Provider::Anthropic, None),
        ("openai", Provider::Openai, None),
    ];

    for (toml_name, expected_provider, model) in cases {
        let model_line = match model {
            Some(m) => format!("model = \"{m}\""),
            None => String::new(),
        };
        let toml = format!(
            "[project]\nname = \"test\"\n\n[generator]\nprovider = \"{toml_name}\"\n{model_line}\n\n[runner.rust]\ncommand = \"cargo test\"\ntest_dir = \"tests/\"\n"
        );
        let path = dir.join("ought.toml");
        fs::write(&path, &toml).expect("must write ought.toml");

        let config = Config::load(&path).unwrap_or_else(|e| {
            panic!("Config::load must succeed for provider=\"{toml_name}\" model={model:?}; got: {e}")
        });

        assert_eq!(config.generator.provider, *expected_provider);

        if let Some(m) = model {
            assert_eq!(config.generator.model, *m);
        } else {
            // Omitting `model` in TOML falls back to the serde default
            // (the current Claude Sonnet id); it's always a non-empty
            // string, not an Option.
            assert!(
                !config.generator.model.is_empty(),
                "default model must be populated when omitted"
            );
        }
    }

    fs::remove_dir_all(&dir).ok();
}

/// MUST NOT depend on any provider-specific features in the core spec format or runner
#[test]
fn test_ought__llm_agnostic__must_not_depend_on_any_provider_specific_features_in_the_core_spec_fo() {
    use ought_gen::generator::{GeneratedTest, Language};
    use ought_run::runner::Runner;
    use ought_run::types::RunResult;

    let clause = Clause {
        id: ClauseId("ought::llm_agnostic::core_format_clause".to_string()),
        keyword: Keyword::Must,
        severity: Severity::Required,
        text: "not depend on provider-specific features".to_string(),
        condition: None,
        otherwise: vec![],
        temporal: None,
        hints: vec![],
        source_location: SourceLocation { file: PathBuf::from("spec.ought.md"), line: 1 },
        content_hash: "xyz".to_string(),
        pending: false,
    };
    assert_eq!(clause.id.0, "ought::llm_agnostic::core_format_clause");

    let test = GeneratedTest {
        clause_id: clause.id.clone(),
        code: "#[test]\nfn test_x() { assert!(true); }".to_string(),
        language: Language::Rust,
        file_path: PathBuf::from("ought/llm_agnostic/core_format_clause_test.rs"),
    };
    assert_eq!(test.clause_id, clause.id);

    struct NeutralRunner;
    impl Runner for NeutralRunner {
        fn run(&self, _tests: &[GeneratedTest], _test_dir: &std::path::Path) -> anyhow::Result<RunResult> {
            Ok(RunResult { results: vec![], total_duration: std::time::Duration::ZERO })
        }
        fn is_available(&self) -> bool { true }
        fn name(&self) -> &str { "neutral" }
    }

    let runner: Box<dyn Runner> = Box::new(NeutralRunner);
    assert_eq!(runner.name(), "neutral");
    assert!(runner.is_available());

    let result = runner.run(&[test], &PathBuf::from("/tmp"))
        .expect("Runner must accept GeneratedTest without caring about the originating provider");
    assert_eq!(result.results.len(), 0);
}

/// MUST support at least Anthropic (Claude) and OpenAI as providers via agent mode
#[test]
fn test_ought__llm_agnostic__must_support_at_least_anthropic_claude_and_openai_as_providers() {
    // Provider configuration is validated at the config level. The
    // orchestrator maps the typed Provider enum to the appropriate
    // in-process Llm adapter. Verify that the four shipped provider
    // names deserialize to their enum variants.
    use ought_gen::Provider;
    let dir = std::env::temp_dir().join(format!("ought_provider_test_{}", std::process::id()));
    fs::create_dir_all(&dir).expect("must create temp dir");

    for (toml_name, expected) in &[
        ("anthropic", Provider::Anthropic),
        ("openai", Provider::Openai),
        ("openrouter", Provider::Openrouter),
        ("ollama", Provider::Ollama),
    ] {
        let toml_content = format!(
            "[project]\nname = \"test\"\n\n[generator]\nprovider = \"{toml_name}\"\n\n[runner.rust]\ncommand = \"cargo test\"\ntest_dir = \"tests/\"\n"
        );
        let path = dir.join("ought.toml");
        fs::write(&path, &toml_content).expect("must write ought.toml");
        let config = Config::load(&path);
        assert!(
            config.is_ok(),
            "Config must load with provider=\"{toml_name}\"; got: {:?}",
            config.err()
        );
        assert_eq!(config.unwrap().generator.provider, *expected);
    }

    fs::remove_dir_all(&dir).ok();
}

// ===========================================================================
// language_agnostic
// ===========================================================================

