//! Generated tests for the `spec_format` subsection of the `ought` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use ought_cli::config::Config;
use ought_spec::{OughtMdParser, Parser, SpecGraph};
use ought_spec::types::*;

use crate::helpers::{
    ought_bin, scaffold_project, unique_dir, walkdir, write_spec, write_test,
};

/// MUST support RFC 2119 keywords (MUST, MUST NOT, SHOULD, SHOULD NOT, MAY) as deontic operators.
#[test]
fn test_ought__spec_format__must_support_rfc_2119_keywords_must_must_not_should_should_not_ma() {
    let md = r#"# Spec Format

## Rules

- **MUST** always validate input
- **MUST NOT** store plaintext passwords
- **SHOULD** log all access attempts
- **SHOULD NOT** cache sensitive data
- **MAY** support optional audit trails
"#;

    let spec = OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed");
    let clauses = &spec.sections[0].clauses;

    assert_eq!(clauses.len(), 5);

    assert_eq!(clauses[0].keyword, Keyword::Must);
    assert_eq!(clauses[0].severity, Severity::Required);
    assert!(clauses[0].text.contains("validate input"));

    assert_eq!(clauses[1].keyword, Keyword::MustNot);
    assert_eq!(clauses[1].severity, Severity::Required);
    assert!(clauses[1].text.contains("plaintext passwords"));

    assert_eq!(clauses[2].keyword, Keyword::Should);
    assert_eq!(clauses[2].severity, Severity::Recommended);
    assert!(clauses[2].text.contains("log all access"));

    assert_eq!(clauses[3].keyword, Keyword::ShouldNot);
    assert_eq!(clauses[3].severity, Severity::Recommended);
    assert!(clauses[3].text.contains("cache sensitive"));

    assert_eq!(clauses[4].keyword, Keyword::May);
    assert_eq!(clauses[4].severity, Severity::Optional);
    assert!(clauses[4].text.contains("audit trails"));
}

/// MUST use standard markdown (CommonMark) so specs render in GitHub, editors, and browsers.
#[test]
fn test_ought__spec_format__must_use_standard_markdown_commonmark_so_specs_render_in_github_e() {
    let md = r#"# Spec Format

> This spec is written in standard CommonMark.

## Rules

Some *introductory* prose with `inline code` and **bold** text.

- **MUST** render correctly in any CommonMark-compliant renderer

```markdown
# Example heading
- **MUST** sample clause
```
"#;

    let result = OughtMdParser.parse_string(md, Path::new("spec_format.ought.md"));
    assert!(result.is_ok(), "CommonMark spec should parse without errors: {:?}", result.err());
    let spec = result.unwrap();

    assert_eq!(spec.name, "Spec Format");
    assert_eq!(spec.sections.len(), 1);
    assert_eq!(spec.sections[0].title, "Rules");
    assert!(!spec.sections[0].prose.is_empty(), "CommonMark prose should be captured");
    assert_eq!(spec.sections[0].clauses.len(), 1);
    assert!(spec.sections[0].clauses[0].text.contains("render correctly"));
    assert_eq!(spec.sections[0].clauses[0].hints.len(), 1);
}

/// MUST support the WONT keyword for deliberately absent capabilities.
#[test]
fn test_ought__spec_format__must_support_the_wont_keyword_for_deliberately_absent_capabilitie() {
    let md = r#"# Spec Format

## Scope Exclusions

- **WONT** support OAuth 1.0 due to known security flaws
- **WONT** provide a SOAP API
"#;

    let spec = OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed");
    let clauses = &spec.sections[0].clauses;

    assert_eq!(clauses.len(), 2);

    assert_eq!(clauses[0].keyword, Keyword::Wont);
    assert_eq!(clauses[0].severity, Severity::NegativeConfirmation);
    assert!(clauses[0].text.contains("OAuth 1.0"));

    assert_eq!(clauses[1].keyword, Keyword::Wont);
    assert_eq!(clauses[1].severity, Severity::NegativeConfirmation);
    assert!(clauses[1].text.contains("SOAP API"));
}

/// MUST support GIVEN blocks for conditional obligations.
#[test]
fn test_ought__spec_format__must_support_given_blocks_for_conditional_obligations_clauses_tha() {
    let md = r#"# Spec Format

## Access Control

- **GIVEN** the user is authenticated:
  - **MUST** return their profile data
  - **MUST NOT** return other users' private data
  - **MAY** return extended metadata
"#;

    let spec = OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed");
    let clauses = &spec.sections[0].clauses;

    assert_eq!(clauses.len(), 3, "GIVEN should not appear as its own clause");
    assert!(
        clauses.iter().all(|c| c.keyword != Keyword::Given),
        "Keyword::Given should not be emitted as a top-level clause"
    );

    let expected_condition = "the user is authenticated:";
    for clause in clauses {
        assert_eq!(clause.condition.as_deref(), Some(expected_condition),
            "All clauses inside GIVEN must carry the condition");
    }

    assert_eq!(clauses[0].keyword, Keyword::Must);
    assert_eq!(clauses[1].keyword, Keyword::MustNot);
    assert_eq!(clauses[2].keyword, Keyword::May);
}

/// MUST support OTHERWISE chains for contrary-to-duty fallbacks.
#[test]
fn test_ought__spec_format__must_support_otherwise_chains_for_contrary_to_duty_fallbacks_grac() {
    let md = r#"# Spec Format

## Resilience

- **MUST** respond within 200ms
  - **OTHERWISE** return a cached response
  - **OTHERWISE** return 503 Service Unavailable
"#;

    let spec = OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed");
    let clauses = &spec.sections[0].clauses;

    assert_eq!(clauses.len(), 1, "OTHERWISE items must not appear as top-level clauses");

    let primary = &clauses[0];
    assert_eq!(primary.keyword, Keyword::Must);
    assert_eq!(primary.otherwise.len(), 2, "Two OTHERWISE fallbacks expected");

    assert_eq!(primary.otherwise[0].keyword, Keyword::Otherwise);
    assert!(primary.otherwise[0].text.contains("cached response"));
    assert_eq!(primary.otherwise[0].severity, Severity::Required);

    assert_eq!(primary.otherwise[1].keyword, Keyword::Otherwise);
    assert!(primary.otherwise[1].text.contains("503"));
    assert_eq!(primary.otherwise[1].severity, Severity::Required);
}

/// MUST support MUST ALWAYS for invariants.
#[test]
fn test_ought__spec_format__must_support_must_always_for_invariants_properties_that_must_hold() {
    let md = r#"# Spec Format

## Invariants

- **MUST ALWAYS** keep database connections below pool maximum
- **MUST ALWAYS** produce a valid UTF-8 response body
"#;

    let spec = OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed");
    let clauses = &spec.sections[0].clauses;

    assert_eq!(clauses.len(), 2);

    for clause in clauses {
        assert_eq!(clause.keyword, Keyword::MustAlways);
        assert_eq!(clause.severity, Severity::Required);
        assert!(
            matches!(clause.temporal, Some(Temporal::Invariant)),
            "MUST ALWAYS must set temporal to Invariant, got {:?}", clause.temporal
        );
    }

    assert!(clauses[0].text.contains("pool maximum"));
    assert!(clauses[1].text.contains("UTF-8"));
}

/// MUST support MUST BY for deadline obligations.
#[test]
fn test_ought__spec_format__must_support_must_by_for_deadline_obligations_operations_that_mus() {
    use std::time::Duration;

    let md = r#"# Spec Format

## Performance

- **MUST BY 100ms** return search results
- **MUST BY 5s** complete authentication handshake
- **MUST BY 30m** finish the nightly batch export
"#;

    let spec = OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed");
    let clauses = &spec.sections[0].clauses;

    assert_eq!(clauses.len(), 3);

    for clause in clauses {
        assert_eq!(clause.keyword, Keyword::MustBy);
        assert_eq!(clause.severity, Severity::Required);
    }

    assert!(
        matches!(clauses[0].temporal, Some(Temporal::Deadline(d)) if d == Duration::from_millis(100)),
        "Expected 100ms deadline, got {:?}", clauses[0].temporal
    );
    assert!(clauses[0].text.contains("search results"));

    assert!(
        matches!(clauses[1].temporal, Some(Temporal::Deadline(d)) if d == Duration::from_secs(5)),
        "Expected 5s deadline, got {:?}", clauses[1].temporal
    );
    assert!(clauses[1].text.contains("authentication handshake"));

    assert!(
        matches!(clauses[2].temporal, Some(Temporal::Deadline(d)) if d == Duration::from_secs(30 * 60)),
        "Expected 30m deadline, got {:?}", clauses[2].temporal
    );
    assert!(clauses[2].text.contains("batch export"));
}

/// MUST support cross-file references via standard markdown links.
#[test]
fn test_ought__spec_format__must_support_cross_file_references_via_standard_markdown_links_so() {
    let md = r#"# Spec Format

requires: [Auth](auth.ought.md), [Billing](billing.ought.md#invoices), [Core](core/base.ought.md#rules)

## Sections

- **MUST** integrate with referenced specs
"#;

    let spec = OughtMdParser.parse_string(md, Path::new("spec_format.ought.md")).expect("parse failed");
    let refs = &spec.metadata.requires;

    assert_eq!(refs.len(), 3, "Three cross-file references expected");

    assert_eq!(refs[0].label, "Auth");
    assert_eq!(refs[0].path.to_str().unwrap(), "auth.ought.md");
    assert_eq!(refs[0].anchor, None);

    assert_eq!(refs[1].label, "Billing");
    assert_eq!(refs[1].path.to_str().unwrap(), "billing.ought.md");
    assert_eq!(refs[1].anchor.as_deref(), Some("invoices"));

    assert_eq!(refs[2].label, "Core");
    assert_eq!(refs[2].path.to_str().unwrap(), "core/base.ought.md");
    assert_eq!(refs[2].anchor.as_deref(), Some("rules"));
}

/// SHOULD be parseable by a standalone library with no LLM dependency.
#[test]
fn test_ought__spec_format__should_be_parseable_by_a_standalone_library_with_no_llm_dependency() {
    let md = r#"# Standalone Spec

context: Verifies the parser works with no external dependencies

requires: [Other](other.ought.md)

## Obligations

- **MUST** validate all inputs
- **MUST NOT** leak secrets
- **SHOULD** emit structured logs
- **SHOULD NOT** swallow errors silently
- **MAY** support optional features
- **WONT** implement deprecated protocols

## Conditional

- **GIVEN** the cache is warm:
  - **MUST** serve from cache

## Degradation

- **MUST** return a result
  - **OTHERWISE** return a fallback value

## Temporal

- **MUST ALWAYS** preserve referential integrity
- **MUST BY 500ms** respond to health checks
"#;

    let result = OughtMdParser.parse_string(md, Path::new("standalone.ought.md"));
    assert!(result.is_ok(), "Standalone parser must succeed: {:?}", result.err());

    let spec = result.unwrap();

    assert_eq!(spec.name, "Standalone Spec");
    assert_eq!(spec.metadata.context.as_deref(), Some("Verifies the parser works with no external dependencies"));
    assert_eq!(spec.metadata.requires.len(), 1);
    assert_eq!(spec.sections.len(), 4);

    let obligations = &spec.sections[0].clauses;
    assert_eq!(obligations.len(), 6);
    assert!(obligations.iter().any(|c| c.keyword == Keyword::Must));
    assert!(obligations.iter().any(|c| c.keyword == Keyword::MustNot));
    assert!(obligations.iter().any(|c| c.keyword == Keyword::Should));
    assert!(obligations.iter().any(|c| c.keyword == Keyword::ShouldNot));
    assert!(obligations.iter().any(|c| c.keyword == Keyword::May));
    assert!(obligations.iter().any(|c| c.keyword == Keyword::Wont));

    let conditional = &spec.sections[1].clauses;
    assert_eq!(conditional.len(), 1);
    assert!(conditional[0].condition.is_some());

    let degradation = &spec.sections[2].clauses;
    assert_eq!(degradation.len(), 1);
    assert_eq!(degradation[0].otherwise.len(), 1);

    let temporal = &spec.sections[3].clauses;
    assert_eq!(temporal.len(), 2);
    assert!(matches!(temporal[0].temporal, Some(Temporal::Invariant)));
    assert!(matches!(temporal[1].temporal, Some(Temporal::Deadline(_))));

    let all_clauses: Vec<_> = spec.sections.iter()
        .flat_map(|s| s.clauses.iter())
        .collect();
    let ids: Vec<_> = all_clauses.iter().map(|c| &c.id.0).collect();
    let unique_ids: std::collections::HashSet<_> = ids.iter().collect();
    assert_eq!(ids.len(), unique_ids.len(), "All clause IDs must be unique");
    assert!(all_clauses.iter().all(|c| !c.id.0.is_empty()), "No clause may have an empty ID");

    for clause in &all_clauses {
        let expected = clause.keyword.severity();
        assert_eq!(clause.severity, expected,
            "Severity mismatch for {:?}: expected {:?}", clause.keyword, expected);
    }
}

// ===========================================================================
// implementation
// ===========================================================================

