//! Generated tests for the `what_ought_does` subsection of the `ought` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use ought_cli::config::Config;
use ought_spec::{OughtMdParser, Parser, SpecGraph};
use ought_spec::types::*;

use crate::helpers::{
    ought_bin, scaffold_project, unique_dir, walkdir, write_spec, write_test,
};

/// MUST accept behavioral specifications written in standard markdown files (`.ought.md`)
#[test]
fn test_ought__what_ought_does__must_accept_behavioral_specifications_written_in_standard_markdow() {
    let tmp_path = std::env::temp_dir().join(format!("test_spec_{}.ought.md", std::process::id()));
    let spec_content = "# My Spec\n\n## Section\n\n- **MUST** do something\n";
    fs::write(&tmp_path, spec_content).expect("Failed to write test .ought.md file");

    assert!(tmp_path.exists(), "Spec file should exist after writing");
    assert!(
        tmp_path.to_str().unwrap().ends_with(".ought.md"),
        "File must use .ought.md compound extension"
    );

    let contents = fs::read_to_string(&tmp_path).expect("Spec file should be readable as UTF-8");
    assert!(!contents.is_empty(), "Spec file should not be empty");
    assert!(contents.contains('#'), "Spec file should contain markdown headings");

    // The parser must accept this file
    let result = OughtMdParser.parse_string(&contents, &tmp_path);
    assert!(result.is_ok(), "Parser must accept a valid .ought.md file: {:?}", result.err());

    let _ = fs::remove_file(&tmp_path);
}

/// MUST provide a CLI (`ought`) as the primary interface for all operations
#[test]
fn test_ought__what_ought_does__must_provide_a_cli_ought_as_the_primary_interface_for_all_operati() {
    let bin = ought_bin();
    let output = Command::new(&bin).arg("--help").output();

    match output {
        Ok(out) => {
            let stdout = String::from_utf8_lossy(&out.stdout);
            let stderr = String::from_utf8_lossy(&out.stderr);
            let combined = format!("{}{}", stdout, stderr);
            assert!(
                !combined.is_empty(),
                "The `ought` CLI must produce output when invoked with --help"
            );
        }
        Err(e) => {
            panic!(
                "The `ought` CLI binary must be available; invocation failed: {}", e
            );
        }
    }
}

/// MUST execute generated tests and report pass/fail results mapped back to the original spec clauses
#[test]
fn test_ought__what_ought_does__must_execute_generated_tests_and_report_pass_fail_results_mapped() {
    #[derive(Debug, PartialEq)]
    enum TestOutcome { Pass, Fail }

    struct ClauseResult {
        clause_id: String,
        outcome: TestOutcome,
    }

    let results = vec![
        ClauseResult { clause_id: "my_spec::section::must_do_something".to_string(), outcome: TestOutcome::Pass },
        ClauseResult { clause_id: "my_spec::section::must_handle_error".to_string(), outcome: TestOutcome::Fail },
    ];

    for r in &results {
        assert!(!r.clause_id.is_empty(), "Every test result must reference a clause ID");
        assert!(r.clause_id.contains("::"), "Clause IDs must use '::' namespace separators, got: {}", r.clause_id);
    }

    let passes: Vec<_> = results.iter().filter(|r| r.outcome == TestOutcome::Pass).collect();
    let failures: Vec<_> = results.iter().filter(|r| r.outcome == TestOutcome::Fail).collect();

    assert_eq!(passes.len(), 1);
    assert_eq!(failures.len(), 1);
    assert_eq!(passes[0].clause_id, "my_spec::section::must_do_something");
    assert_eq!(failures[0].clause_id, "my_spec::section::must_handle_error");
}

/// MUST use an LLM to generate concrete, runnable test code from those specifications
#[test]
fn test_ought__what_ought_does__must_use_an_llm_to_generate_concrete_runnable_test_code_from_thos() {
    let generated_samples = vec![
        "#[test]\nfn test_example() { assert!(true); }",
        "#[test]\nfn test_another() { let x = 1; assert_eq!(x, 1); }",
        "#[test]\nfn test_boundary() { assert_ne!(0, 1); }",
    ];

    for sample in &generated_samples {
        assert!(sample.contains("#[test]"), "Generated code must carry the #[test] attribute: {:?}", sample);
        assert!(sample.contains("fn test_"), "Generated code must declare a test function: {:?}", sample);
        let has_assertion = sample.contains("assert!(") || sample.contains("assert_eq!(") || sample.contains("assert_ne!(");
        assert!(has_assertion, "Generated tests must include at least one assertion: {:?}", sample);
    }
}

/// MUST NOT require users to write any test code by hand
#[test]
fn test_ought__what_ought_does__must_not_require_users_to_write_any_test_code_by_hand() {
    let tmp_dir = std::env::temp_dir().join(format!("ought_no_manual_tests_{}", std::process::id()));
    let _ = fs::create_dir_all(&tmp_dir);

    let spec_path = tmp_dir.join("feature.ought.md");
    let spec_content = "# Feature\n\n## Section\n\n- **MUST** work correctly\n";
    fs::write(&spec_path, spec_content).expect("Should be able to write spec file");

    let handwritten_test = tmp_dir.join("tests.rs");
    assert!(!handwritten_test.exists(), "Users must not be required to provide a hand-written tests.rs");

    let contents = fs::read_to_string(&spec_path).unwrap();
    assert!(!contents.contains("#[test]"), "User-facing spec files must not contain #[test] attributes");
    assert!(!contents.contains("fn test_"), "User-facing spec files must not contain test function definitions");
    assert!(!contents.contains("assert!("), "User-facing spec files must not contain assertion macros");

    let _ = fs::remove_dir_all(&tmp_dir);
}

// ===========================================================================
// spec_format
// ===========================================================================

