//! Generated tests for the `resources` subsection of the `mcp_server` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

#![allow(dead_code, clippy::all)]
#![allow(non_snake_case, unused_imports)]

use std::collections::HashMap;
use std::path::PathBuf;
use ought_mcp::server::{McpServer, Transport};
use ought_mcp::tools::ToolHandler;
use ought_mcp::resources::ResourceHandler;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// The McpServer type exists and can be constructed with project context.
fn make_server() -> McpServer {
    McpServer::new(PathBuf::from("."), vec![], HashMap::new())
}

fn make_tool_handler() -> ToolHandler {
    ToolHandler::new(PathBuf::from("."), vec![], HashMap::new())
}

fn make_resource_handler() -> ResourceHandler {
    ResourceHandler::new(PathBuf::from("."), vec![])
}

// ===========================================================================
// server_lifecycle
// ===========================================================================

/// MUST start the MCP server via `ought mcp serve`
///
/// Verifies the McpServer type can be constructed and the Transport enum exists.

/// MUST expose `ought://specs` -- list of all spec files with their clause counts
///
/// Verifies the ResourceHandler::specs_list method exists and returns Result<Value>.
#[test]
fn test_mcp_server__resources__must_expose_ought_specs_list_of_all_spec_files_with_their_clause() {
    let _: fn(&ResourceHandler) -> anyhow::Result<serde_json::Value> =
        ResourceHandler::specs_list;
}


/// MUST expose `ought://specs/{name}` -- parsed clauses for a specific spec file
#[test]
fn test_mcp_server__resources__must_expose_ought_specs_name_parsed_clauses_for_a_specific_spec_f() {
    let _: fn(&ResourceHandler, &str) -> anyhow::Result<serde_json::Value> =
        ResourceHandler::specs_get;
}


/// MUST expose `ought://results/latest` -- results from the most recent run
#[test]
fn test_mcp_server__resources__must_expose_ought_results_latest_results_from_the_most_recent_run() {
    let _: fn(&ResourceHandler) -> anyhow::Result<serde_json::Value> =
        ResourceHandler::results_latest;
}


/// MUST expose `ought://coverage` -- clause coverage map
#[test]
fn test_mcp_server__resources__must_expose_ought_coverage_clause_coverage_map_which_clauses_have() {
    let _: fn(&ResourceHandler) -> anyhow::Result<serde_json::Value> =
        ResourceHandler::coverage;
}


/// SHOULD expose `ought://manifest` -- current generation manifest
#[test]
fn test_mcp_server__resources__should_expose_ought_manifest_current_generation_manifest_hashes_tim() {
    let _: fn(&ResourceHandler) -> anyhow::Result<serde_json::Value> =
        ResourceHandler::manifest;
}


/// MUST route resources/read correctly through JSON-RPC layer.
#[test]
fn test_mcp_server__resources__must_route_resource_read_through_jsonrpc() {
    let tool_handler = make_tool_handler();
    let resource_handler = make_resource_handler();

    // Read an unknown resource -- should get an error response, not a crash
    let request = r#"{"jsonrpc": "2.0", "id": 5, "method": "resources/read", "params": {"uri": "ought://unknown"}}"#;
    let response = McpServer::handle_request(request, &tool_handler, &resource_handler);

    assert_eq!(response["jsonrpc"], "2.0");
    assert_eq!(response["id"], 5);
    assert!(response["error"].is_object());
}


/// MUST return error when resources/read is missing the URI.
#[test]
fn test_mcp_server__resources__must_return_error_when_missing_uri() {
    let tool_handler = make_tool_handler();
    let resource_handler = make_resource_handler();

    let request = r#"{"jsonrpc": "2.0", "id": 6, "method": "resources/read", "params": {}}"#;
    let response = McpServer::handle_request(request, &tool_handler, &resource_handler);

    assert_eq!(response["jsonrpc"], "2.0");
    assert_eq!(response["id"], 6);
    assert!(response["error"].is_object());
    assert_eq!(response["error"]["code"], -32602);
}


/// SHOULD support resource subscriptions so clients get notified when results change
///
/// Requires actual server implementation. Marked ignored.
#[test]
#[ignore]
fn test_mcp_server__resources__should_support_resource_subscriptions_so_clients_get_notified_when() {
    // Would connect to the MCP server and subscribe to ought://results/latest.
}

// ===========================================================================
// error_handling
// ===========================================================================

