//! Generated tests for the `check` subsection of the `cli` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use ought_cli::config::Config;
use ought_spec::{OughtMdParser, Parser, SpecGraph};
use ought_spec::types::*;

use crate::helpers::{
    ought_bin, scaffold_project, unique_dir, walkdir, write_spec, write_test,
};

/// MUST exit with code 0 if all specs are valid, 1 if any are invalid
#[test]
fn test_cli__check__must_exit_with_code_0_if_all_specs_are_valid_1_if_any_are_invalid() {
    let base = std::env::temp_dir()
        .join(format!("ought_check_exit_{}", std::process::id()));
    let valid_dir = base.join("valid");
    let invalid_dir = base.join("invalid");
    std::fs::create_dir_all(&valid_dir).unwrap();
    std::fs::create_dir_all(&invalid_dir).unwrap();

    // ── exit 0: all specs are valid ───────────────────────────────────────────
    std::fs::write(
        valid_dir.join("svc.ought.md"),
        "# Service\n\n## Auth\n\n- **MUST** authenticate every request\n",
    )
    .unwrap();

    let valid_result = ought_spec::SpecGraph::from_roots(&[valid_dir.clone()]);
    assert!(
        valid_result.is_ok(),
        "valid specs must not produce errors (ought check would exit 0); errors: {:?}",
        valid_result.err()
    );

    // ── exit 1: at least one spec is invalid (circular dependency) ────────────
    // Two specs that require each other form a cycle, which is a hard error.
    std::fs::write(
        invalid_dir.join("a.ought.md"),
        "# Spec A\n\nrequires: [B](./b.ought.md)\n\n## Section\n\n- **MUST** depend on B\n",
    )
    .unwrap();
    std::fs::write(
        invalid_dir.join("b.ought.md"),
        "# Spec B\n\nrequires: [A](./a.ought.md)\n\n## Section\n\n- **MUST** depend on A\n",
    )
    .unwrap();

    let invalid_result = ought_spec::SpecGraph::from_roots(&[invalid_dir.clone()]);
    assert!(
        invalid_result.is_err(),
        "specs with circular dependencies must produce errors (ought check would exit 1)"
    );
    let errors = invalid_result.unwrap_err();
    assert!(
        !errors.is_empty(),
        "ought check must report at least one error when specs are invalid"
    );
    let any_cycle_msg = errors
        .iter()
        .any(|e| e.message.contains("circular") || e.message.contains("cycle"));
    assert!(
        any_cycle_msg,
        "error must describe the circular dependency; got: {:?}",
        errors
            .iter()
            .map(|e| e.to_string())
            .collect::<Vec<_>>()
    );

    let _ = std::fs::remove_dir_all(&base);
}

/// MUST report parse errors with file, line number, and a human-readable message
#[test]
fn test_cli__check__must_report_parse_errors_with_file_line_number_and_a_human_readab() {
    let base = std::env::temp_dir()
        .join(format!("ought_check_errmsg_{}", std::process::id()));
    std::fs::create_dir_all(&base).unwrap();

    // A missing file is the canonical trigger for a file-level ParseError.
    let missing = base.join("nonexistent.ought.md");

    let errors = OughtMdParser.parse_file(&missing)
        .expect_err("parsing a missing file must return Vec<ParseError>");

    assert!(!errors.is_empty(), "at least one parse error must be reported");
    let err = &errors[0];

    // Must carry the correct file path.
    assert_eq!(err.file, missing, "error must name the problematic file");

    // The Display impl must produce the canonical `file:line: message` format.
    let displayed = err.to_string();
    assert!(
        displayed.contains(missing.to_str().unwrap()),
        "Display must embed the file path; got: {:?}",
        displayed
    );
    let rest = displayed.trim_start_matches(missing.to_str().unwrap());
    assert!(
        rest.starts_with(':'),
        "Display must follow `file:line: message` format; got: {:?}",
        displayed
    );

    // Message must be non-trivially human-readable.
    assert!(
        !err.message.is_empty(),
        "parse error message must not be empty"
    );
    assert!(
        err.message.split_whitespace().count() >= 2,
        "message must be human-readable (≥ 2 words); got: {:?}",
        err.message
    );

    let _ = std::fs::remove_dir_all(&base);
}

/// MUST validate that cross-file references (links to other .ought.md files) resolve
#[test]
fn test_cli__check__must_validate_that_cross_file_references_links_to_other_ought_md() {
    let base = std::env::temp_dir()
        .join(format!("ought_check_xref_{}", std::process::id()));
    let valid_dir = base.join("valid");
    let broken_dir = base.join("broken");
    std::fs::create_dir_all(&valid_dir).unwrap();
    std::fs::create_dir_all(&broken_dir).unwrap();

    // ── valid case: referenced file exists in the same roots ─────────────────
    std::fs::write(
        valid_dir.join("base.ought.md"),
        "# Base\n\n## Core\n\n- **MUST** exist\n",
    )
    .unwrap();
    std::fs::write(
        valid_dir.join("extension.ought.md"),
        "# Extension\n\nrequires: [Base](./base.ought.md)\n\n## Extra\n\n- **MUST** build on base\n",
    )
    .unwrap();

    let valid_result = ought_spec::SpecGraph::from_roots(&[valid_dir.clone()]);
    assert!(
        valid_result.is_ok(),
        "specs whose cross-file references resolve must pass check; errors: {:?}",
        valid_result.err()
    );
    assert_eq!(
        valid_result.unwrap().specs().len(),
        2,
        "both the referencing and referenced spec must be loaded"
    );

    // ── broken case: referenced file does not exist ───────────────────────────
    std::fs::write(
        broken_dir.join("consumer.ought.md"),
        "# Consumer\n\nrequires: [Ghost](./ghost.ought.md)\n\n## Usage\n\n- **MUST** depend on ghost\n",
    )
    .unwrap();
    // ghost.ought.md is intentionally absent.

    let broken_result = ought_spec::SpecGraph::from_roots(&[broken_dir.clone()]);
    assert!(
        broken_result.is_err(),
        "specs with unresolvable cross-file references must fail check"
    );
    let errs = broken_result.unwrap_err();
    let combined = errs
        .iter()
        .map(|e| e.to_string())
        .collect::<Vec<_>>()
        .join("; ")
        .to_lowercase();
    assert!(
        combined.contains("ghost")
            || combined.contains("not found")
            || combined.contains("resolve")
            || combined.contains("missing"),
        "error must reference the unresolved file; got: {:?}",
        combined
    );

    let _ = std::fs::remove_dir_all(&base);
}

/// MUST validate the syntax of all spec files without generating or running anything
#[test]
fn test_cli__check__must_validate_the_syntax_of_all_spec_files_without_generating_or() {
    let base = std::env::temp_dir()
        .join(format!("ought_check_syntax_{}", std::process::id()));
    let spec_dir = base.join("specs");
    std::fs::create_dir_all(&spec_dir).unwrap();

    std::fs::write(
        spec_dir.join("auth.ought.md"),
        "# Auth\n\n## Login\n\n- **MUST** return a JWT token\n- **MUST NOT** expose password hashes\n",
    )
    .unwrap();
    std::fs::write(
        spec_dir.join("api.ought.md"),
        "# API\n\n## Endpoints\n\n- **MUST** respond within 200ms\n- **SHOULD** use pagination\n",
    )
    .unwrap();

    // Snapshot the directory state before invoking the check operation.
    let mut before: Vec<_> = std::fs::read_dir(&base)
        .unwrap()
        .flatten()
        .map(|e| e.path())
        .collect();
    before.sort();

    let result = ought_spec::SpecGraph::from_roots(&[spec_dir.clone()]);

    assert!(
        result.is_ok(),
        "check must succeed for valid spec files; errors: {:?}",
        result.err()
    );
    let graph = result.unwrap();
    assert_eq!(
        graph.specs().len(),
        2,
        "check must validate every spec file found in the roots"
    );

    // Check must be a read-only operation — no new files or directories created.
    let mut after: Vec<_> = std::fs::read_dir(&base)
        .unwrap()
        .flatten()
        .map(|e| e.path())
        .collect();
    after.sort();
    assert_eq!(
        before, after,
        "check must not generate or write any files"
    );

    let _ = std::fs::remove_dir_all(&base);
}

