//! Generated tests for the `diff` subsection of the `cli` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use ought_cli::config::Config;
use ought_spec::{OughtMdParser, Parser, SpecGraph};
use ought_spec::types::*;

use crate::helpers::{
    ought_bin, scaffold_project, unique_dir, walkdir, write_spec, write_test,
};

/// MUST show the diff between current generated tests and what would be generated now
#[test]
fn test_cli__diff__must_show_the_diff_between_current_generated_tests_and_what_would() {
    let dir = std::env::temp_dir()
        .join(format!("ought_diff_show_{}", std::process::id()));
    std::fs::create_dir_all(dir.join("ought")).unwrap();

    std::fs::write(
        dir.join("ought.toml"),
        "[project]\nname = \"test\"\nversion = \"0.1.0\"\n\n\
         [specs]\nroots = [\"ought/\"]\n\n\
         [context]\nsearch_paths = [\"src/\"]\nexclude = [\"target/\"]\n\n\
         [generator]\nprovider = \"anthropic\"\n\n\
         [runner.rust]\ncommand = \"cargo test\"\ntest_dir = \"ought/ought-gen/\"\n",
    )
    .unwrap();

    std::fs::write(
        dir.join("ought/auth.ought.md"),
        "# Auth\n\ncontext: Authentication service\n\n## Login\n\n- **MUST** return a JWT on success\n",
    )
    .unwrap();

    // Write an existing generated test representing the "current" state on disk.
    let gen_dir = dir.join("ought/ought-gen/auth/login");
    std::fs::create_dir_all(&gen_dir).unwrap();
    std::fs::write(
        gen_dir.join("must_return_a_jwt_on_success.rs"),
        "#[test]\nfn test_auth__login__must_return_a_jwt_on_success() {\n    // generated from old clause text\n    assert!(false, \"placeholder\");\n}\n",
    )
    .unwrap();

    // Manifest with a stale hash so ought diff has a change to report.
    std::fs::create_dir_all(dir.join("ought/ought-gen")).unwrap();
    std::fs::write(
        dir.join("ought/ought-gen/manifest.toml"),
        "[\"auth::login::must_return_a_jwt_on_success\"]\n\
         clause_hash = \"old_stale_hash_does_not_match_current\"\n\
         source_hash = \"\"\n\
         generated_at = \"2020-01-01T00:00:00Z\"\n\
         model = \"test\"\n",
    )
    .unwrap();

    let bin = ought_bin();

    let output = std::process::Command::new(&bin)
        .arg("diff")
        .current_dir(&dir)
        .output()
        .expect("failed to invoke ought diff");

    // Must not exit with a clap usage error.
    assert_ne!(
        output.status.code(),
        Some(2),
        "ought diff must not exit with a usage error (2); stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );

    let combined = format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );

    // Must not be the unimplemented stub message.
    assert!(
        !combined.contains("not yet implemented"),
        "ought diff must be implemented and show actual diffs; got:\n{combined}"
    );

    // Must produce output when stale clauses exist.
    assert!(
        !combined.trim().is_empty(),
        "ought diff must produce output when generated tests are stale; got no output"
    );

    // Output must reference the affected clause or file.
    assert!(
        combined.contains("auth") || combined.contains("must_return_a_jwt_on_success"),
        "ought diff output must reference the stale clause or its spec; got:\n{combined}"
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// SHOULD group diffs by spec file
#[test]
fn test_cli__diff__should_group_diffs_by_spec_file() {
    let dir = std::env::temp_dir()
        .join(format!("ought_diff_group_{}", std::process::id()));
    std::fs::create_dir_all(dir.join("ought")).unwrap();

    std::fs::write(
        dir.join("ought.toml"),
        "[project]\nname = \"test\"\nversion = \"0.1.0\"\n\n\
         [specs]\nroots = [\"ought/\"]\n\n\
         [context]\nsearch_paths = [\"src/\"]\nexclude = [\"target/\"]\n\n\
         [generator]\nprovider = \"anthropic\"\n\n\
         [runner.rust]\ncommand = \"cargo test\"\ntest_dir = \"ought/ought-gen/\"\n",
    )
    .unwrap();

    // Two separate spec files, each with a stale clause.
    std::fs::write(
        dir.join("ought/auth.ought.md"),
        "# Auth\n\ncontext: Authentication\n\n## Login\n\n- **MUST** validate credentials\n",
    )
    .unwrap();
    std::fs::write(
        dir.join("ought/payments.ought.md"),
        "# Payments\n\ncontext: Payments\n\n## Charge\n\n- **MUST** validate card expiry\n",
    )
    .unwrap();

    // Existing generated tests for both specs.
    let gen_auth = dir.join("ought/ought-gen/auth/login");
    let gen_pay = dir.join("ought/ought-gen/payments/charge");
    std::fs::create_dir_all(&gen_auth).unwrap();
    std::fs::create_dir_all(&gen_pay).unwrap();
    std::fs::write(
        gen_auth.join("must_validate_credentials.rs"),
        "#[test]\nfn test_auth__login__must_validate_credentials() { assert!(true); }\n",
    )
    .unwrap();
    std::fs::write(
        gen_pay.join("must_validate_card_expiry.rs"),
        "#[test]\nfn test_payments__charge__must_validate_card_expiry() { assert!(true); }\n",
    )
    .unwrap();

    // Both manifest entries are stale.
    std::fs::create_dir_all(dir.join("ought/ought-gen")).unwrap();
    std::fs::write(
        dir.join("ought/ought-gen/manifest.toml"),
        "[\"auth::login::must_validate_credentials\"]\n\
         clause_hash = \"stale_auth_hash\"\n\
         source_hash = \"\"\n\
         generated_at = \"2020-01-01T00:00:00Z\"\n\
         model = \"test\"\n\
         \n\
         [\"payments::charge::must_validate_card_expiry\"]\n\
         clause_hash = \"stale_payments_hash\"\n\
         source_hash = \"\"\n\
         generated_at = \"2020-01-01T00:00:00Z\"\n\
         model = \"test\"\n",
    )
    .unwrap();

    let bin = ought_bin();

    let output = std::process::Command::new(&bin)
        .arg("diff")
        .current_dir(&dir)
        .output()
        .expect("failed to invoke ought diff");

    let stdout = String::from_utf8_lossy(&output.stdout);

    // Output must reference both spec files.
    assert!(
        stdout.contains("auth"),
        "ought diff must include a section for auth.ought.md; stdout:\n{stdout}"
    );
    assert!(
        stdout.contains("payments"),
        "ought diff must include a section for payments.ought.md; stdout:\n{stdout}"
    );

    // The two spec files must appear as distinct groups: auth content and payments
    // content must not be interleaved without any per-file header.  We verify this
    // by checking that the first occurrence of each spec name is separated by some
    // output rather than appearing on the same line.
    let auth_pos = stdout.find("auth").expect("auth must appear in output");
    let pay_pos = stdout.find("payments").expect("payments must appear in output");
    assert!(
        auth_pos != pay_pos,
        "auth and payments diff groups must appear at distinct positions in the output"
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// SHOULD use a familiar unified diff format
#[test]
fn test_cli__diff__should_use_a_familiar_unified_diff_format() {
    let dir = std::env::temp_dir()
        .join(format!("ought_diff_format_{}", std::process::id()));
    std::fs::create_dir_all(dir.join("ought")).unwrap();

    std::fs::write(
        dir.join("ought.toml"),
        "[project]\nname = \"test\"\nversion = \"0.1.0\"\n\n\
         [specs]\nroots = [\"ought/\"]\n\n\
         [context]\nsearch_paths = [\"src/\"]\nexclude = [\"target/\"]\n\n\
         [generator]\nprovider = \"anthropic\"\n\n\
         [runner.rust]\ncommand = \"cargo test\"\ntest_dir = \"ought/ought-gen/\"\n",
    )
    .unwrap();

    std::fs::write(
        dir.join("ought/payments.ought.md"),
        "# Payments\n\ncontext: Payment processing\n\n## Charge\n\n- **MUST** reject invalid card numbers\n",
    )
    .unwrap();

    // Existing generated test — the "before" side of the diff.
    let gen_dir = dir.join("ought/ought-gen/payments/charge");
    std::fs::create_dir_all(&gen_dir).unwrap();
    std::fs::write(
        gen_dir.join("must_reject_invalid_card_numbers.rs"),
        "#[test]\nfn test_payments__charge__must_reject_invalid_card_numbers() {\n    // old body\n    assert!(true);\n}\n",
    )
    .unwrap();

    // Stale manifest entry to give diff something to show.
    std::fs::create_dir_all(dir.join("ought/ought-gen")).unwrap();
    std::fs::write(
        dir.join("ought/ought-gen/manifest.toml"),
        "[\"payments::charge::must_reject_invalid_card_numbers\"]\n\
         clause_hash = \"outdated_hash_does_not_match_current_clause\"\n\
         source_hash = \"\"\n\
         generated_at = \"2020-06-01T00:00:00Z\"\n\
         model = \"test\"\n",
    )
    .unwrap();

    let bin = ought_bin();

    let output = std::process::Command::new(&bin)
        .arg("diff")
        .current_dir(&dir)
        .output()
        .expect("failed to invoke ought diff");

    let stdout = String::from_utf8_lossy(&output.stdout);

    // Unified diff format requires --- / +++ file headers and @@ hunk markers.
    assert!(
        stdout.contains("---") && stdout.contains("+++"),
        "ought diff output must use unified diff format with --- and +++ file headers;\
         \nstdout:\n{stdout}"
    );
    assert!(
        stdout.contains("@@"),
        "ought diff output must include @@ hunk markers as in unified diff format;\
         \nstdout:\n{stdout}"
    );

    let _ = std::fs::remove_dir_all(&dir);
}

