//! Generated tests for the `generate` subsection of the `cli` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use ought_cli::config::Config;
use ought_spec::{OughtMdParser, Parser, SpecGraph};
use ought_spec::types::*;

use crate::helpers::{
    ought_bin, scaffold_project, unique_dir, walkdir, write_spec, write_test,
};

/// MUST NOT execute tests during generation (that is `run`'s job)
#[test]
fn test_cli__generate__must_not_execute_tests_during_generation_that_is_run_s_job() {
    let dir = std::env::temp_dir()
        .join(format!("ought_gen_norun_{}", std::process::id()));
    std::fs::create_dir_all(dir.join("ought")).unwrap();

    std::fs::write(
        dir.join("ought.toml"),
        "[project]\nname = \"test\"\nversion = \"0.1.0\"\n\n\
         [specs]\nroots = [\"ought/\"]\n\n\
         [context]\nsearch_paths = [\"src/\"]\nexclude = [\"target/\"]\n\n\
         [generator]\nprovider = \"anthropic\"\n\n\
         [runner.rust]\ncommand = \"cargo test\"\ntest_dir = \"ought/ought-gen/\"\n",
    )
    .unwrap();

    std::fs::write(
        dir.join("ought/spec.ought.md"),
        "# Spec\n\ncontext: test\n\n## Section\n\n- **MUST** do the thing\n",
    )
    .unwrap();

    let bin = ought_bin();

    let out = std::process::Command::new(&bin)
        .arg("generate")
        .arg("--check")
        .current_dir(&dir)
        .output()
        .expect("failed to invoke ought generate --check");

    let combined = format!(
        "{}{}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );

    // cargo test output always contains "test result:" or "running N test".
    // Neither must appear during generation.
    assert!(
        !combined.contains("test result:"),
        "ought generate must not execute tests; found 'test result:' in output: {combined}"
    );
    assert!(
        !combined.contains("running 1 test") && !combined.contains("running 0 tests"),
        "ought generate must not invoke the test runner; found runner output: {combined}"
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// MUST regenerate test code for all clauses where the clause hash or source hash has changed
#[test]
fn test_cli__generate__must_regenerate_test_code_for_all_clauses_where_the_clause_hash_o() {
    let dir = std::env::temp_dir()
        .join(format!("ought_gen_rehash_{}", std::process::id()));
    std::fs::create_dir_all(dir.join("ought")).unwrap();

    std::fs::write(
        dir.join("ought.toml"),
        "[project]\nname = \"test\"\nversion = \"0.1.0\"\n\n\
         [specs]\nroots = [\"ought/\"]\n\n\
         [context]\nsearch_paths = [\"src/\"]\nexclude = [\"target/\"]\n\n\
         [generator]\nprovider = \"anthropic\"\n\n\
         [runner.rust]\ncommand = \"cargo test\"\ntest_dir = \"ought/ought-gen/\"\n",
    )
    .unwrap();

    std::fs::write(
        dir.join("ought/spec.ought.md"),
        "# Spec\n\ncontext: test\n\n## Section\n\n- **MUST** do the thing\n",
    )
    .unwrap();

    // Write a manifest with a deliberately wrong clause hash so the clause is stale.
    std::fs::create_dir_all(dir.join("ought/ought-gen")).unwrap();
    std::fs::write(
        dir.join("ought/ought-gen/manifest.toml"),
        "[\"spec::section::must_do_the_thing\"]\n\
         clause_hash = \"old_stale_hash_that_will_not_match\"\n\
         source_hash = \"\"\n\
         generated_at = \"2020-01-01T00:00:00Z\"\n\
         model = \"test\"\n",
    )
    .unwrap();

    let bin = ought_bin();

    // --check detects staleness without invoking the LLM.
    let out = std::process::Command::new(&bin)
        .arg("generate")
        .arg("--check")
        .current_dir(&dir)
        .output()
        .expect("failed to invoke ought generate --check");

    // When any clause hash is stale, --check must exit 1.
    assert_eq!(
        out.status.code(),
        Some(1),
        "ought generate --check must exit 1 when clause hash has changed; stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );

    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(
        stderr.contains("stale"),
        "ought generate --check must report stale clauses; stderr: {stderr}"
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// MUST support `--check` flag that exits with code 1 if any generated tests are stale (for CI)
#[test]
fn test_cli__generate__must_support_check_flag_that_exits_with_code_1_if_any_generated_t() {
    let dir = std::env::temp_dir()
        .join(format!("ought_gen_check_{}", std::process::id()));
    std::fs::create_dir_all(dir.join("ought")).unwrap();

    std::fs::write(
        dir.join("ought.toml"),
        "[project]\nname = \"test\"\nversion = \"0.1.0\"\n\n\
         [specs]\nroots = [\"ought/\"]\n\n\
         [context]\nsearch_paths = [\"src/\"]\nexclude = [\"target/\"]\n\n\
         [generator]\nprovider = \"anthropic\"\n\n\
         [runner.rust]\ncommand = \"cargo test\"\ntest_dir = \"ought/ought-gen/\"\n",
    )
    .unwrap();

    std::fs::write(
        dir.join("ought/spec.ought.md"),
        "# Spec\n\ncontext: test\n\n## Section\n\n- **MUST** do the thing\n",
    )
    .unwrap();

    // No manifest: every clause is stale by definition.
    let bin = ought_bin();

    let out = std::process::Command::new(&bin)
        .arg("generate")
        .arg("--check")
        .current_dir(&dir)
        .output()
        .expect("failed to invoke ought generate --check");

    // --check must be accepted by clap (not a usage error).
    assert_ne!(
        out.status.code(),
        Some(2),
        "--check must be a recognised flag; stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );

    // With stale clauses --check must exit 1.
    assert_eq!(
        out.status.code(),
        Some(1),
        "ought generate --check must exit 1 when generated tests are stale; stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// MUST support `--force` flag to regenerate all clauses regardless of hash
#[test]
fn test_cli__generate__must_support_force_flag_to_regenerate_all_clauses_regardless_of_h() {
    let dir = std::env::temp_dir()
        .join(format!("ought_gen_force_{}", std::process::id()));
    std::fs::create_dir_all(dir.join("ought")).unwrap();

    std::fs::write(
        dir.join("ought.toml"),
        "[project]\nname = \"test\"\nversion = \"0.1.0\"\n\n\
         [specs]\nroots = [\"ought/\"]\n\n\
         [context]\nsearch_paths = [\"src/\"]\nexclude = [\"target/\"]\n\n\
         [generator]\nprovider = \"anthropic\"\n\n\
         [runner.rust]\ncommand = \"cargo test\"\ntest_dir = \"ought/ought-gen/\"\n",
    )
    .unwrap();

    std::fs::write(
        dir.join("ought/spec.ought.md"),
        "# Spec\n\ncontext: test\n\n## Section\n\n- **MUST** do the thing\n",
    )
    .unwrap();

    let bin = ought_bin();

    // --force must be a recognised flag (clap exit 2 = usage error).
    let out = std::process::Command::new(&bin)
        .arg("generate")
        .arg("--force")
        .arg("--check")
        .current_dir(&dir)
        .output()
        .expect("failed to invoke ought generate --force --check");

    assert_ne!(
        out.status.code(),
        Some(2),
        "--force must be a recognised flag; stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );

    // With --force all clauses are treated as stale regardless of manifest state.
    // Combining with --check avoids an LLM call while still asserting forced staleness.
    assert_eq!(
        out.status.code(),
        Some(1),
        "ought generate --force --check must exit 1 because --force marks every clause stale; \
         stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// MUST update the manifest.toml with new hashes after generation
#[test]
fn test_cli__generate__must_update_the_manifest_toml_with_new_hashes_after_generation() {
    let dir = std::env::temp_dir()
        .join(format!("ought_gen_manifest_{}", std::process::id()));
    std::fs::create_dir_all(dir.join("ought")).unwrap();

    std::fs::write(
        dir.join("ought.toml"),
        "[project]\nname = \"test\"\nversion = \"0.1.0\"\n\n\
         [specs]\nroots = [\"ought/\"]\n\n\
         [context]\nsearch_paths = [\"src/\"]\nexclude = [\"target/\"]\n\n\
         [generator]\nprovider = \"anthropic\"\n\n\
         [runner.rust]\ncommand = \"cargo test\"\ntest_dir = \"ought/ought-gen/\"\n",
    )
    .unwrap();

    std::fs::write(
        dir.join("ought/spec.ought.md"),
        "# Spec\n\ncontext: test\n\n## Section\n\n- **MUST** do the thing\n",
    )
    .unwrap();

    // No manifest exists yet.
    let manifest_path = dir.join("ought/ought-gen/manifest.toml");
    assert!(
        !manifest_path.exists(),
        "manifest.toml must not exist before generate"
    );

    let bin = ought_bin();

    // --check mode still saves the manifest (save happens before the stale exit).
    std::process::Command::new(&bin)
        .arg("generate")
        .arg("--check")
        .current_dir(&dir)
        .output()
        .expect("failed to invoke ought generate --check");

    // The manifest.toml must be written to ought/ought-gen/ after generate runs.
    assert!(
        manifest_path.exists(),
        "manifest.toml must be created at ought/ought-gen/manifest.toml after ought generate"
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// MUST write generated tests to the `ought/ought-gen/` directory
#[test]
fn test_cli__generate__must_write_generated_tests_to_the_ought_ought_gen_directory() {
    let dir = std::env::temp_dir()
        .join(format!("ought_gen_outdir_{}", std::process::id()));
    std::fs::create_dir_all(dir.join("ought")).unwrap();

    std::fs::write(
        dir.join("ought.toml"),
        "[project]\nname = \"test\"\nversion = \"0.1.0\"\n\n\
         [specs]\nroots = [\"ought/\"]\n\n\
         [context]\nsearch_paths = [\"src/\"]\nexclude = [\"target/\"]\n\n\
         [generator]\nprovider = \"anthropic\"\n\n\
         [runner.rust]\ncommand = \"cargo test\"\ntest_dir = \"ought/ought-gen/\"\n",
    )
    .unwrap();

    std::fs::write(
        dir.join("ought/spec.ought.md"),
        "# Spec\n\ncontext: test\n\n## Section\n\n- **MUST** do the thing\n",
    )
    .unwrap();

    // ought/ought-gen/ must not exist yet.
    let gen_dir = dir.join("ought/ought-gen");
    assert!(
        !gen_dir.exists(),
        "ought/ought-gen/ must not exist before generate"
    );

    let bin = ought_bin();

    // --check avoids calling the LLM while still exercising the generate path.
    std::process::Command::new(&bin)
        .arg("generate")
        .arg("--check")
        .current_dir(&dir)
        .output()
        .expect("failed to invoke ought generate --check");

    assert!(
        gen_dir.is_dir(),
        "ought generate must create the ought/ought-gen/ output directory"
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// SHOULD show a progress indicator during LLM generation
#[test]
fn test_cli__generate__should_show_a_progress_indicator_during_llm_generation() {
    let dir = std::env::temp_dir()
        .join(format!("ought_gen_progress_{}", std::process::id()));
    std::fs::create_dir_all(dir.join("ought")).unwrap();

    std::fs::write(
        dir.join("ought.toml"),
        "[project]\nname = \"test\"\nversion = \"0.1.0\"\n\n\
         [specs]\nroots = [\"ought/\"]\n\n\
         [context]\nsearch_paths = [\"src/\"]\nexclude = [\"target/\"]\n\n\
         [generator]\nprovider = \"anthropic\"\n\n\
         [runner.rust]\ncommand = \"cargo test\"\ntest_dir = \"ought/ought-gen/\"\n",
    )
    .unwrap();

    std::fs::write(
        dir.join("ought/spec.ought.md"),
        "# Spec\n\ncontext: test\n\n## Section\n\n- **MUST** do the thing\n",
    )
    .unwrap();

    let bin = ought_bin();

    let out = std::process::Command::new(&bin)
        .arg("generate")
        .arg("--check")
        .current_dir(&dir)
        .output()
        .expect("failed to invoke ought generate --check");

    // The generate command must emit diagnostic output to stderr so the user
    // can see activity (stale clause IDs, section headers, and/or a summary line).
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(
        !stderr.trim().is_empty(),
        "ought generate must produce diagnostic output on stderr as a progress indicator; \
         got empty stderr"
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// SHOULD support targeting a specific spec file: `ought generate ought/auth.ought.md`
#[test]
fn test_cli__generate__should_support_targeting_a_specific_spec_file_ought_generate_ought() {
    let dir = std::env::temp_dir()
        .join(format!("ought_gen_target_{}", std::process::id()));
    std::fs::create_dir_all(dir.join("ought")).unwrap();

    std::fs::write(
        dir.join("ought.toml"),
        "[project]\nname = \"test\"\nversion = \"0.1.0\"\n\n\
         [specs]\nroots = [\"ought/\"]\n\n\
         [context]\nsearch_paths = [\"src/\"]\nexclude = [\"target/\"]\n\n\
         [generator]\nprovider = \"anthropic\"\n\n\
         [runner.rust]\ncommand = \"cargo test\"\ntest_dir = \"ought/ought-gen/\"\n",
    )
    .unwrap();

    // Two spec files; the test targets only the auth one.
    std::fs::write(
        dir.join("ought/auth.ought.md"),
        "# Auth\n\ncontext: test\n\n## Login\n\n- **MUST** authenticate users\n",
    )
    .unwrap();
    std::fs::write(
        dir.join("ought/billing.ought.md"),
        "# Billing\n\ncontext: test\n\n## Payments\n\n- **MUST** charge the card\n",
    )
    .unwrap();

    let bin = ought_bin();

    let out = std::process::Command::new(&bin)
        .arg("generate")
        .arg("ought/auth.ought.md")
        .arg("--check")
        .current_dir(&dir)
        .output()
        .expect("failed to invoke ought generate with a specific spec path");

    // A path argument must not cause a clap usage error (exit 2).
    assert_ne!(
        out.status.code(),
        Some(2),
        "ought generate must accept a specific spec file path without a usage error; stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );

    let _ = std::fs::remove_dir_all(&dir);
}

