//! Generated tests for the `global_flags` subsection of the `cli` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use ought_cli::config::Config;
use ought_spec::{OughtMdParser, Parser, SpecGraph};
use ought_spec::types::*;

use crate::helpers::{
    ought_bin, scaffold_project, unique_dir, walkdir, write_spec, write_test,
};

/// MUST ALWAYS return a valid exit code (0, 1, or 2) — never crash without an exit code.
/// Invariant — verified across a wide fuzz-style range of invocations.
#[test]
fn test_cli__global_flags__must_always_return_a_valid_exit_code_0_1_or_2_never_crash_without_an_exi(
) {
    let bin = ought_bin();

    let proj = std::env::temp_dir()
        .join(format!("ought_exitcode_inv_{}", std::process::id()));
    std::fs::create_dir_all(&proj).unwrap();

    // Pre-initialise so commands that need a project have one.
    let _ = std::process::Command::new(&bin)
        .arg("init")
        .current_dir(&proj)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .output();

    // Fuzz corpus: valid commands, usage errors, missing args, bad flag values, edge cases.
    let invocations: &[&[&str]] = &[
        // ── Valid subcommands ────────────────────────────────────────────────
        &["check"],
        &["run"],
        &["diff"],
        &["--json", "run"],
        &["--quiet", "run"],
        &["--verbose", "check"],
        &["--color", "never", "check"],
        &["--color", "always", "check"],
        &["--color", "auto", "check"],
        &["--quiet", "--json", "run"],
        // ── Usage errors: unknown flags / subcommands (must exit 2) ─────────
        &["--nonexistent-flag"],
        &["nonexistent-subcommand"],
        &["--unknown-global", "check"],
        &["run", "--unknown-local"],
        // ── Missing required positional args (must exit 2) ──────────────────
        &["blame"],
        &["bisect"],
        &["inspect"],
        // ── Bad flag values (must exit 2) ────────────────────────────────────
        &["--color", "rainbow", "check"],
        // ── Config edge cases ────────────────────────────────────────────────
        &["--config", "/nonexistent/path/ought.toml", "check"],
        &["--config", "", "check"],
        // ── Re-init (project already exists) ─────────────────────────────────
        &["init"],
    ];

    for args in invocations {
        let out = std::process::Command::new(&bin)
            .args(*args)
            .current_dir(&proj)
            .stdin(std::process::Stdio::null())
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::piped())
            .output()
            .unwrap_or_else(|e| panic!("process::Command failed for {args:?}: {e}"));

        let code = out.status.code();
        assert!(
            matches!(code, Some(0) | Some(1) | Some(2)),
            "ought {args:?} must exit 0, 1, or 2 — never crash or signal-terminate; \
             got {code:?}; stderr: {}",
            String::from_utf8_lossy(&out.stderr)
        );
    }

    let _ = std::fs::remove_dir_all(&proj);
}

/// MUST ALWAYS write diagnostic messages to stderr, never stdout (stdout is reserved for
/// structured output and results). Invariant — verified across a range of invocations.
#[test]
fn test_cli__global_flags__must_always_write_diagnostic_messages_to_stderr_never_stdout_stdout_is_r(
) {
    let bin = ought_bin();

    // Set up a valid project so most commands have something real to work with.
    let proj = std::env::temp_dir()
        .join(format!("ought_stderr_inv_{}", std::process::id()));
    std::fs::create_dir_all(&proj).unwrap();
    let init = std::process::Command::new(&bin)
        .arg("init")
        .current_dir(&proj)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .output()
        .expect("ought init (stderr probe setup)");
    assert!(
        init.status.success(),
        "init must succeed for probe setup; stderr: {}",
        String::from_utf8_lossy(&init.stderr)
    );

    // Diagnostic keyword patterns that must never appear on stdout.
    // These are prefixes written by the application itself (not embedded in JSON payloads).
    let diagnostic_patterns: &[&str] = &[
        "error: ",
        "Error: ",
        "warning: ",
        "Warning: ",
        "fatal: ",
    ];

    // Probe a range of non-JSON invocations; for each, stdout must not contain raw diagnostics.
    let probes: &[(&[&str], &str)] = &[
        (&["check"], "check"),
        (&["--verbose", "check"], "--verbose check"),
        (&["--quiet", "check"], "--quiet check"),
        (&["run"], "run"),
        (&["--quiet", "run"], "--quiet run"),
    ];

    for (args, label) in probes {
        let out = std::process::Command::new(&bin)
            .args(*args)
            .current_dir(&proj)
            .stdin(std::process::Stdio::null())
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::piped())
            .output()
            .unwrap_or_else(|e| panic!("failed to run ought {label}: {e}"));

        let stdout = String::from_utf8_lossy(&out.stdout);
        for pat in diagnostic_patterns {
            assert!(
                !stdout.contains(pat),
                "ought {label}: diagnostic pattern {pat:?} must not appear on stdout; \
                 stdout={stdout:?}"
            );
        }
    }

    // A known-error path (nonexistent --config) must write its error to stderr, not stdout.
    let bad = std::process::Command::new(&bin)
        .args(["--config", "/nonexistent/path/ought.toml", "check"])
        .current_dir(&proj)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .output()
        .expect("ought --config /nonexistent check");

    assert_ne!(
        bad.status.code(),
        Some(0),
        "ought with a nonexistent --config must not succeed"
    );
    let bad_stdout = String::from_utf8_lossy(&bad.stdout);
    for pat in diagnostic_patterns {
        assert!(
            !bad_stdout.contains(pat),
            "error from bad --config must appear on stderr, not stdout; \
             stdout={bad_stdout:?}"
        );
    }
    let bad_stderr = String::from_utf8_lossy(&bad.stderr);
    assert!(
        !bad_stderr.is_empty(),
        "error from bad --config must produce output on stderr"
    );

    let _ = std::fs::remove_dir_all(&proj);
}

/// MUST support `--color <auto|always|never>` for terminal color control
#[test]
fn test_cli__global_flags__must_support_color_auto_always_never_for_terminal_color_control() {
    let bin = ought_bin();

    // Each variant must be accepted by the argument parser (exit code must not be 2).
    for color_value in ["auto", "always", "never"] {
        let dir = std::env::temp_dir().join(format!(
            "ought_color_{}_{}_{}",
            color_value,
            std::process::id(),
            color_value.len() // extra salt to keep names distinct in the loop
        ));
        std::fs::create_dir_all(&dir).unwrap();

        let out = std::process::Command::new(&bin)
            .args(["--color", color_value, "init"])
            .current_dir(&dir)
            .stdin(std::process::Stdio::null())
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::piped())
            .output()
            .unwrap_or_else(|e| {
                panic!("failed to run `ought --color {color_value} init`: {e}")
            });

        assert_ne!(
            out.status.code(),
            Some(2),
            "--color {color_value} must not produce a usage/parse error; stderr: {}",
            String::from_utf8_lossy(&out.stderr)
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    // An invalid value must be rejected with exit code 2.
    let dir_invalid = std::env::temp_dir()
        .join(format!("ought_color_invalid_{}", std::process::id()));
    std::fs::create_dir_all(&dir_invalid).unwrap();
    let bad = std::process::Command::new(&bin)
        .args(["--color", "rainbow", "init"])
        .current_dir(&dir_invalid)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .output()
        .expect("ought --color rainbow init");
    assert_eq!(
        bad.status.code(),
        Some(2),
        "--color with an invalid value must produce a usage error (exit 2)"
    );
    let _ = std::fs::remove_dir_all(&dir_invalid);
}

/// MUST support `--config <path>` to specify an alternate ought.toml location
#[test]
fn test_cli__global_flags__must_support_config_path_to_specify_an_alternate_ought_toml_locat() {
    let base = std::env::temp_dir()
        .join(format!("ought_cfg_flag_{}", std::process::id()));
    let specs_dir = base.join("specs");
    let alt_config = base.join("alt_ought.toml");
    std::fs::create_dir_all(&specs_dir).unwrap();

    std::fs::write(
        specs_dir.join("test.ought.md"),
        "# Test\n\n## Section: Basics\n\n### MUST do something\n",
    )
    .unwrap();

    // Write a valid ought.toml at a non-default location.
    std::fs::write(
        &alt_config,
        format!(
            "[project]\nname = \"test\"\nversion = \"0.1.0\"\n\n\
             [specs]\nroots = [\"{specs}\"]\n\n\
             [context]\nsearch_paths = [\"{base}\"]\n\n\
             [generator]\nprovider = \"anthropic\"\n",
            specs = specs_dir.display(),
            base = base.display(),
        ),
    )
    .unwrap();

    let bin = ought_bin();

    // Without --config and no ought.toml in `base`, config discovery must fail.
    let no_cfg = std::process::Command::new(&bin)
        .arg("check")
        .current_dir(&base)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .output()
        .expect("ought check (no config)");
    assert_ne!(
        no_cfg.status.code(),
        Some(0),
        "check with no discoverable config must not succeed"
    );

    // With --config pointing to the alternate file, ought must load it and succeed.
    let with_cfg = std::process::Command::new(&bin)
        .args(["--config", alt_config.to_str().unwrap(), "check"])
        .current_dir(&base)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .output()
        .expect("ought --config check");
    assert_eq!(
        with_cfg.status.code(),
        Some(0),
        "--config must load the alternate file; stderr: {}",
        String::from_utf8_lossy(&with_cfg.stderr)
    );

    let _ = std::fs::remove_dir_all(&base);
}

/// MUST support `--json` flag that outputs structured JSON for programmatic consumption
#[test]
fn test_cli__global_flags__must_support_json_flag_that_outputs_structured_json_for_programma() {
    let dir = std::env::temp_dir()
        .join(format!("ought_json_flag_{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();

    let bin = ought_bin();

    // Initialise a minimal project.
    let init = std::process::Command::new(&bin)
        .arg("init")
        .current_dir(&dir)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .output()
        .expect("ought init");
    assert!(
        init.status.success(),
        "init must succeed to set up the test project; stderr: {}",
        String::from_utf8_lossy(&init.stderr)
    );

    // Run with --json; the flag must be accepted and any stdout must be valid JSON.
    let out = std::process::Command::new(&bin)
        .args(["--json", "run"])
        .current_dir(&dir)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .output()
        .expect("ought --json run");

    assert_ne!(
        out.status.code(),
        Some(2),
        "--json must not produce a usage/parse error; stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );

    let stdout = String::from_utf8_lossy(&out.stdout);
    let trimmed = stdout.trim();
    if !trimmed.is_empty() {
        assert!(
            trimmed.starts_with('{') || trimmed.starts_with('['),
            "--json stdout must be a JSON object or array; got: {}",
            &trimmed[..trimmed.len().min(200)]
        );
        // Verify that all opening brackets have matching closing brackets.
        let opens: usize = trimmed
            .chars()
            .filter(|&c| c == '{' || c == '[')
            .count();
        let closes: usize = trimmed
            .chars()
            .filter(|&c| c == '}' || c == ']')
            .count();
        assert_eq!(
            opens, closes,
            "--json output must have balanced braces; stdout: {}",
            &trimmed[..trimmed.len().min(200)]
        );
    }

    let _ = std::fs::remove_dir_all(&dir);
}

/// MUST support `--junit <path>` flag that writes JUnit XML results to the given file
#[test]
fn test_cli__global_flags__must_support_junit_path_flag_that_writes_junit_xml_results_to_the() {
    let dir = std::env::temp_dir()
        .join(format!("ought_junit_flag_{}", std::process::id()));
    let junit_path = dir.join("results.xml");
    std::fs::create_dir_all(&dir).unwrap();

    let bin = ought_bin();

    // Initialise a minimal project.
    let init = std::process::Command::new(&bin)
        .arg("init")
        .current_dir(&dir)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .output()
        .expect("ought init");
    assert!(
        init.status.success(),
        "init must succeed to set up the test project; stderr: {}",
        String::from_utf8_lossy(&init.stderr)
    );

    // Run with --junit; the file must be created at the given path.
    let out = std::process::Command::new(&bin)
        .args(["--junit", junit_path.to_str().unwrap(), "run"])
        .current_dir(&dir)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .output()
        .expect("ought --junit run");

    assert_ne!(
        out.status.code(),
        Some(2),
        "--junit must not produce a usage/parse error; stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    assert!(
        junit_path.exists(),
        "--junit must create the output file at the specified path ({})",
        junit_path.display()
    );

    let xml_content = std::fs::read_to_string(&junit_path)
        .expect("--junit output file must be readable");
    assert!(
        xml_content.trim().starts_with('<'),
        "--junit file must contain XML; first 200 chars: {}",
        &xml_content[..xml_content.len().min(200)]
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// MUST support `--quiet` flag that suppresses all output except errors and the final summary
#[test]
fn test_cli__global_flags__must_support_quiet_flag_that_suppresses_all_output_except_errors() {
    let bin = ought_bin();

    let dir_loud = std::env::temp_dir()
        .join(format!("ought_quiet_loud_{}", std::process::id()));
    let dir_quiet = std::env::temp_dir()
        .join(format!("ought_quiet_silent_{}", std::process::id()));
    std::fs::create_dir_all(&dir_loud).unwrap();
    std::fs::create_dir_all(&dir_quiet).unwrap();

    // Run `ought init` (produces informational output) without --quiet.
    let loud = std::process::Command::new(&bin)
        .arg("init")
        .current_dir(&dir_loud)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .output()
        .expect("ought init (loud)");

    // Run the same command with --quiet.
    let quiet = std::process::Command::new(&bin)
        .args(["--quiet", "init"])
        .current_dir(&dir_quiet)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .output()
        .expect("ought --quiet init");

    // --quiet must be a recognised flag (not a usage error).
    assert_ne!(
        quiet.status.code(),
        Some(2),
        "--quiet must not produce a usage/parse error; stderr: {}",
        String::from_utf8_lossy(&quiet.stderr)
    );

    // --quiet must suppress stdout relative to the normal invocation.
    assert!(
        quiet.stdout.len() <= loud.stdout.len(),
        "--quiet must produce no more stdout than default; quiet={} bytes, loud={} bytes",
        quiet.stdout.len(),
        loud.stdout.len()
    );

    let _ = std::fs::remove_dir_all(&dir_loud);
    let _ = std::fs::remove_dir_all(&dir_quiet);
}

/// SHOULD support `--verbose` flag for debug-level output
#[test]
fn test_cli__global_flags__should_support_verbose_flag_for_debug_level_output() {
    let bin = ought_bin();

    // Set up two identical projects so we can compare output side-by-side.
    let dir_normal = std::env::temp_dir()
        .join(format!("ought_verbose_normal_{}", std::process::id()));
    let dir_verbose = std::env::temp_dir()
        .join(format!("ought_verbose_verbose_{}", std::process::id()));
    std::fs::create_dir_all(&dir_normal).unwrap();
    std::fs::create_dir_all(&dir_verbose).unwrap();

    for d in [&dir_normal, &dir_verbose] {
        let init = std::process::Command::new(&bin)
            .arg("init")
            .current_dir(d)
            .stdin(std::process::Stdio::null())
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::piped())
            .output()
            .expect("ought init");
        assert!(
            init.status.success(),
            "init must succeed; stderr: {}",
            String::from_utf8_lossy(&init.stderr)
        );
    }

    let normal = std::process::Command::new(&bin)
        .arg("check")
        .current_dir(&dir_normal)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .output()
        .expect("ought check (normal)");

    let verbose = std::process::Command::new(&bin)
        .args(["--verbose", "check"])
        .current_dir(&dir_verbose)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .output()
        .expect("ought --verbose check");

    // --verbose must be a recognised flag (not a usage error).
    assert_ne!(
        verbose.status.code(),
        Some(2),
        "--verbose must not produce a usage/parse error; stderr: {}",
        String::from_utf8_lossy(&verbose.stderr)
    );

    // --verbose must produce at least as much total output as the default invocation,
    // since debug-level lines are added on top of the normal output.
    let normal_total = normal.stdout.len() + normal.stderr.len();
    let verbose_total = verbose.stdout.len() + verbose.stderr.len();
    assert!(
        verbose_total >= normal_total,
        "--verbose must produce at least as much output as the default; \
         verbose={verbose_total} bytes, normal={normal_total} bytes"
    );

    let _ = std::fs::remove_dir_all(&dir_normal);
    let _ = std::fs::remove_dir_all(&dir_verbose);
}

