//! Generated tests for the `init` subsection of the `cli` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use ought_cli::config::Config;
use ought_spec::{OughtMdParser, Parser, SpecGraph};
use ought_spec::types::*;

use crate::helpers::{
    ought_bin, scaffold_project, unique_dir, walkdir, write_spec, write_test,
};

/// MAY prompt the user interactively for generator provider and model preferences.
/// When stdin is not a terminal (piped from /dev/null), the command must not hang
/// indefinitely; it must terminate with a defined exit code.
#[test]
fn test_cli__init__may_prompt_the_user_interactively_for_generator_provider_and_mod() {
    let dir = std::env::temp_dir()
        .join(format!("ought_init_noninteractive_{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();

    let bin = ought_bin();

    let output = std::process::Command::new(&bin)
        .arg("init")
        .current_dir(&dir)
        // Provide a closed stdin to simulate a non-interactive environment.
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .output()
        .expect("ought init must not hang — process must return");

    // The command MAY prompt interactively, but must not block indefinitely on
    // null stdin. Any definite exit code is acceptable (success or graceful error).
    assert!(
        output.status.code().is_some(),
        "process must terminate with an exit code and not be killed by a signal"
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// MUST detect the project language from existing config files (Cargo.toml, package.json,
/// pyproject.toml, go.mod) and set defaults accordingly.
#[test]
fn test_cli__init__must_detect_the_project_language_from_existing_config_files_cargo() {
    let bin = ought_bin();

    // (marker file, expected language key)
    // The generated `ought.toml` selects a language by writing the matching
    // `[runner.<lang>]` section. That section resolves to a built-in preset
    // (pytest, nextest, jest, gotestsum), so the scaffold does not need to
    // hard-code a harness command string.
    let cases: &[(&str, &str)] = &[
        ("Cargo.toml", "rust"),
        ("package.json", "typescript"),
        ("pyproject.toml", "python"),
        ("go.mod", "go"),
    ];

    for (marker, lang) in cases {
        let dir = std::env::temp_dir().join(format!(
            "ought_init_lang_{}_{}_{}",
            lang,
            std::process::id(),
            // extra entropy so parallel tests on the same pid don't collide
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .subsec_nanos()
        ));
        std::fs::create_dir_all(&dir).unwrap();

        // Write the language marker file with minimal valid content.
        let content = match *marker {
            "Cargo.toml" => "[package]\nname = \"proj\"\nversion = \"0.1.0\"\n",
            "package.json" => "{\"name\":\"proj\"}\n",
            "pyproject.toml" => "[tool.poetry]\nname = \"proj\"\n",
            "go.mod" => "module proj\n\ngo 1.21\n",
            _ => "",
        };
        std::fs::write(dir.join(marker), content).unwrap();

        let output = std::process::Command::new(&bin)
            .arg("init")
            .current_dir(&dir)
            .output()
            .unwrap_or_else(|e| panic!("failed to run ought init for {}: {}", lang, e));

        assert!(
            output.status.success(),
            "ought init should succeed for {} project; stderr: {}",
            lang,
            String::from_utf8_lossy(&output.stderr)
        );

        let config =
            std::fs::read_to_string(dir.join("ought.toml")).expect("ought.toml must be created");

        assert!(
            config.contains(&format!("[runner.{}]", lang)),
            "ought.toml must contain [runner.{}] for a {} project; got:\n{}",
            lang,
            lang,
            config
        );

        let _ = std::fs::remove_dir_all(&dir);
    }
}

/// MUST NOT overwrite an existing `ought.toml`.
#[test]
fn test_cli__init__must_not_overwrite_an_existing_ought_toml() {
    let dir = std::env::temp_dir()
        .join(format!("ought_init_no_overwrite_{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();

    let original_content =
        "# pre-existing config\n[project]\nname = \"existing\"\nversion = \"9.9.9\"\n";
    std::fs::write(dir.join("ought.toml"), original_content).unwrap();

    let bin = ought_bin();

    let output = std::process::Command::new(&bin)
        .arg("init")
        .current_dir(&dir)
        .output()
        .expect("failed to run ought init");

    assert!(
        !output.status.success(),
        "ought init must exit non-zero when ought.toml already exists"
    );

    let after = std::fs::read_to_string(dir.join("ought.toml"))
        .expect("ought.toml must still exist after the failed init");

    assert_eq!(
        after, original_content,
        "ought.toml content must be unchanged when init is refused"
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// MUST scaffold an `ought.toml`, an `ought/` directory, and an example spec file inside it
/// when run in a project directory.
#[test]
fn test_cli__init__must_scaffold_an_ought_toml_an_ought_directory_and_an_example_spe() {
    let dir = std::env::temp_dir()
        .join(format!("ought_init_scaffold_{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();

    let bin = ought_bin();

    let output = std::process::Command::new(&bin)
        .arg("init")
        .current_dir(&dir)
        .output()
        .expect("failed to run ought init");

    assert!(
        output.status.success(),
        "ought init should exit 0; stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );

    assert!(
        dir.join("ought.toml").exists(),
        "ought.toml must be created by ought init"
    );

    assert!(
        dir.join("ought").is_dir(),
        "ought/ directory must be created by ought init"
    );

    let spec_files: Vec<_> = std::fs::read_dir(dir.join("ought"))
        .expect("ought/ must be readable")
        .filter_map(|e| e.ok())
        .filter(|e| {
            e.path()
                .extension()
                .map(|x| x == "md")
                .unwrap_or(false)
        })
        .collect();

    assert!(
        !spec_files.is_empty(),
        "at least one example spec file must exist inside ought/"
    );

    let _ = std::fs::remove_dir_all(&dir);
}

