//! Generated tests for the `inspect` subsection of the `cli` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use ought_cli::config::Config;
use ought_spec::{OughtMdParser, Parser, SpecGraph};
use ought_spec::types::*;

use crate::helpers::{
    ought_bin, scaffold_project, unique_dir, walkdir, write_spec, write_test,
};

/// MUST accept clause identifiers in the form `file::section::clause`
/// (e.g. `auth::login::must_return_jwt`)
#[test]
fn test_cli__inspect__must_accept_clause_identifiers_in_the_form_file_section_clause_e() {
    let dir = std::env::temp_dir()
        .join(format!("ought_inspect_idform_{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();

    std::fs::write(
        dir.join("ought.toml"),
        "[project]\nname = \"test\"\nversion = \"0.1.0\"\n\n\
         [specs]\nroots = [\"ought/\"]\n\n\
         [context]\nsearch_paths = [\"src/\"]\nexclude = []\n\n\
         [generator]\nprovider = \"anthropic\"\n\n\
         [runner.rust]\ncommand = \"cargo test\"\ntest_dir = \"ought/ought-gen/\"\n",
    )
    .unwrap();

    let gen_dir = dir.join("ought/ought-gen/auth/login");
    std::fs::create_dir_all(&gen_dir).unwrap();
    std::fs::write(
        gen_dir.join("must_return_jwt.rs"),
        "#[test]\nfn test_auth__login__must_return_jwt() {}\n",
    )
    .unwrap();

    let bin = ought_bin();

    // Pass a three-part `file::section::clause` identifier — must not be rejected
    // with a usage error (exit code 2).
    let output = std::process::Command::new(&bin)
        .arg("inspect")
        .arg("auth::login::must_return_jwt")
        .current_dir(&dir)
        .output()
        .expect("failed to invoke ought inspect");

    assert_ne!(
        output.status.code(),
        Some(2),
        "ought inspect must not reject a `file::section::clause` identifier as a usage error; \
         stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(
        output.status.success(),
        "ought inspect must exit 0 for a well-formed `file::section::clause` identifier \
         when the generated file exists; stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// MUST print the generated test code for a given clause identifier
#[test]
fn test_cli__inspect__must_print_the_generated_test_code_for_a_given_clause_identifier() {
    let dir = std::env::temp_dir()
        .join(format!("ought_inspect_print_{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();

    std::fs::write(
        dir.join("ought.toml"),
        "[project]\nname = \"test\"\nversion = \"0.1.0\"\n\n\
         [specs]\nroots = [\"ought/\"]\n\n\
         [context]\nsearch_paths = [\"src/\"]\nexclude = []\n\n\
         [generator]\nprovider = \"anthropic\"\n\n\
         [runner.rust]\ncommand = \"cargo test\"\ntest_dir = \"ought/ought-gen/\"\n",
    )
    .unwrap();

    let gen_dir = dir.join("ought/ought-gen/auth/login");
    std::fs::create_dir_all(&gen_dir).unwrap();
    let expected_code =
        "#[test]\nfn test_auth__login__must_return_jwt() {\n    assert!(true);\n}\n";
    std::fs::write(gen_dir.join("must_return_jwt.rs"), expected_code).unwrap();

    let bin = ought_bin();

    let output = std::process::Command::new(&bin)
        .arg("inspect")
        .arg("auth::login::must_return_jwt")
        .current_dir(&dir)
        .output()
        .expect("failed to invoke ought inspect");

    assert!(
        output.status.success(),
        "ought inspect must exit 0 when the clause file exists; stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );

    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(
        stdout.contains("test_auth__login__must_return_jwt"),
        "ought inspect must print the generated test code to stdout; got:\n{stdout}"
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// SHOULD show the clause text alongside the generated code for easy comparison
#[test]
fn test_cli__inspect__should_show_the_clause_text_alongside_the_generated_code_for_easy_c() {
    let dir = std::env::temp_dir()
        .join(format!("ought_inspect_clause_text_{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();

    std::fs::write(
        dir.join("ought.toml"),
        "[project]\nname = \"test\"\nversion = \"0.1.0\"\n\n\
         [specs]\nroots = [\"ought/\"]\n\n\
         [context]\nsearch_paths = [\"src/\"]\nexclude = []\n\n\
         [generator]\nprovider = \"anthropic\"\n\n\
         [runner.rust]\ncommand = \"cargo test\"\ntest_dir = \"ought/ought-gen/\"\n",
    )
    .unwrap();

    // Write a spec file that contains the clause under test.
    let spec_dir = dir.join("ought");
    std::fs::create_dir_all(&spec_dir).unwrap();
    std::fs::write(
        spec_dir.join("auth.ought.md"),
        "# Auth\n\n## Login\n\n- **MUST** return a JWT token\n",
    )
    .unwrap();

    // Write the corresponding generated test file.
    let gen_dir = dir.join("ought/ought-gen/auth/login");
    std::fs::create_dir_all(&gen_dir).unwrap();
    let test_code =
        "#[test]\nfn test_auth__login__must_return_jwt() {\n    assert!(true);\n}\n";
    std::fs::write(gen_dir.join("must_return_jwt.rs"), test_code).unwrap();

    let bin = ought_bin();

    let output = std::process::Command::new(&bin)
        .arg("inspect")
        .arg("auth::login::must_return_jwt")
        .current_dir(&dir)
        .output()
        .expect("failed to invoke ought inspect");

    assert!(
        output.status.success(),
        "ought inspect must exit 0; stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );

    let combined = format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );

    // The clause text ("return a JWT token") should appear alongside the code so
    // the developer can compare the spec intent with the generated test.
    assert!(
        combined.contains("return a JWT token"),
        "ought inspect should show the clause text alongside the generated code for \
         easy comparison; output was:\n{combined}"
    );

    // The generated code must also be present.
    assert!(
        combined.contains("test_auth__login__must_return_jwt"),
        "ought inspect must always include the generated test code; output was:\n{combined}"
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// SHOULD syntax-highlight the output when stdout is a terminal
#[test]
fn test_cli__inspect__should_syntax_highlight_the_output_when_stdout_is_a_terminal() {
    // When stdout is piped (non-terminal), the command must still produce plain
    // readable output.  Syntax highlighting, if supported, must be suppressed in
    // that case so downstream tools are not polluted with ANSI escape sequences.
    // When `--color=always` is requested the output MAY contain highlighting,
    // but must still contain the test code.
    let dir = std::env::temp_dir()
        .join(format!("ought_inspect_hl_{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();

    std::fs::write(
        dir.join("ought.toml"),
        "[project]\nname = \"test\"\nversion = \"0.1.0\"\n\n\
         [specs]\nroots = [\"ought/\"]\n\n\
         [context]\nsearch_paths = [\"src/\"]\nexclude = []\n\n\
         [generator]\nprovider = \"anthropic\"\n\n\
         [runner.rust]\ncommand = \"cargo test\"\ntest_dir = \"ought/ought-gen/\"\n",
    )
    .unwrap();

    let gen_dir = dir.join("ought/ought-gen/auth/login");
    std::fs::create_dir_all(&gen_dir).unwrap();
    let test_code =
        "#[test]\nfn test_auth__login__must_return_jwt() {\n    assert!(true);\n}\n";
    std::fs::write(gen_dir.join("must_return_jwt.rs"), test_code).unwrap();

    let bin = ought_bin();

    // Without a terminal (piped), output must not contain ANSI escape codes so
    // the raw test code is machine-readable.
    let plain_output = std::process::Command::new(&bin)
        .arg("--color=never")
        .arg("inspect")
        .arg("auth::login::must_return_jwt")
        .current_dir(&dir)
        .output()
        .expect("failed to invoke ought inspect --color=never");

    assert!(
        plain_output.status.success(),
        "ought inspect must succeed with --color=never; stderr: {}",
        String::from_utf8_lossy(&plain_output.stderr)
    );

    let plain_stdout = String::from_utf8_lossy(&plain_output.stdout);
    assert!(
        !plain_stdout.contains('\x1b'),
        "ought inspect must not emit ANSI escape sequences when --color=never is set; \
         got:\n{plain_stdout}"
    );
    assert!(
        plain_stdout.contains("test_auth__login__must_return_jwt"),
        "ought inspect must still print the test code when --color=never; got:\n{plain_stdout}"
    );

    // With `--color=always`, the test code must still be present in the output
    // (even if highlighting is not yet implemented).
    let color_output = std::process::Command::new(&bin)
        .arg("--color=always")
        .arg("inspect")
        .arg("auth::login::must_return_jwt")
        .current_dir(&dir)
        .output()
        .expect("failed to invoke ought inspect --color=always");

    assert!(
        color_output.status.success(),
        "ought inspect must succeed with --color=always; stderr: {}",
        String::from_utf8_lossy(&color_output.stderr)
    );

    let color_stdout = String::from_utf8_lossy(&color_output.stdout);
    assert!(
        color_stdout.contains("test_auth__login__must_return_jwt"),
        "ought inspect must include the test code in --color=always output; got:\n{color_stdout}"
    );

    let _ = std::fs::remove_dir_all(&dir);
}

