//! Generated tests for the `run` subsection of the `cli` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use ought_cli::config::Config;
use ought_spec::{OughtMdParser, Parser, SpecGraph};
use ought_spec::types::*;

use crate::helpers::{
    ought_bin, scaffold_project, unique_dir, walkdir, write_spec, write_test,
};

/// MUST accept a glob pattern to run a subset:
/// `ought run "ought/auth*.ought.md"`
#[test]
fn test_cli__run__must_accept_a_glob_pattern_to_run_a_subset_ought_run_ought_auth_o() {
    let dir = unique_dir("glob_arg");
    scaffold_project(&dir);
    std::fs::write(
        dir.join("ought/auth.ought.md"),
        "# Auth\n\ncontext: test\n\n## Login\n\n- **MUST** authenticate users\n",
    )
    .unwrap();
    write_test(&dir, "auth__login__must_authenticate_users", true);

    let out = std::process::Command::new(ought_bin())
        .arg("run")
        .arg("ought/auth*.ought.md")
        .current_dir(&dir)
        .output()
        .expect("failed to invoke ought run with glob pattern");

    // The glob pattern is a string positional argument; must not produce a usage error.
    assert_ne!(
        out.status.code(),
        Some(2),
        "ought run must accept a glob pattern without a usage error; stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// MUST accept a path argument to run a specific spec file:
/// `ought run ought/auth.ought.md`
#[test]
fn test_cli__run__must_accept_a_path_argument_to_run_a_specific_spec_file_ought_run() {
    let dir = unique_dir("path_arg");
    scaffold_project(&dir);
    std::fs::write(
        dir.join("ought/auth.ought.md"),
        "# Auth\n\ncontext: test\n\n## Login\n\n- **MUST** authenticate users\n",
    )
    .unwrap();
    write_test(&dir, "auth__login__must_authenticate_users", true);

    let out = std::process::Command::new(ought_bin())
        .arg("run")
        .arg("ought/auth.ought.md")
        .current_dir(&dir)
        .output()
        .expect("failed to invoke ought run with path argument");

    // clap exits 2 for unrecognised arguments; a path is a positional value and
    // must be accepted without triggering a usage error.
    assert_ne!(
        out.status.code(),
        Some(2),
        "ought run must accept a path argument without a usage error; stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// MUST exit with code 0 if any OTHERWISE clause in the chain passes
/// (graceful degradation accepted).
/// GIVEN: a clause has an OTHERWISE chain and the primary obligation fails.
#[test]
fn test_cli__run__must_exit_with_code_0_if_any_otherwise_clause_in_the_chain_passes() {
    let dir = unique_dir("otherwise_pass");
    scaffold_project(&dir);
    // Spec: MUST with an OTHERWISE fallback
    std::fs::write(
        dir.join("ought/spec.ought.md"),
        "# Spec\n\ncontext: test\n\n## Section\n\n\
         - **MUST** respond in under 100ms\n  \
         - **OTHERWISE** respond in under 1s\n",
    )
    .unwrap();

    // Primary obligation fails
    write_test(
        &dir,
        "spec__section__must_respond_in_under_100ms",
        false,
    );
    // OTHERWISE fallback passes — the degradation chain is satisfied
    write_test(
        &dir,
        "spec__section__must_respond_in_under_100ms__otherwise_respond_in_under_1s",
        true,
    );

    let out = std::process::Command::new(ought_bin())
        .arg("run")
        .current_dir(&dir)
        .output()
        .expect("failed to invoke ought run");

    assert_eq!(
        out.status.code(),
        Some(0),
        "ought run must exit 0 when the primary MUST fails but an OTHERWISE \
         fallback passes (graceful degradation is accepted); \
         stderr: {} stdout: {}",
        String::from_utf8_lossy(&out.stderr),
        String::from_utf8_lossy(&out.stdout)
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// MUST exit with code 0 if only SHOULD or MAY clauses fail.
#[test]
fn test_cli__run__must_exit_with_code_0_if_only_should_or_may_clauses_fail() {
    let dir = unique_dir("exit0_should");
    scaffold_project(&dir);
    // Spec has only a SHOULD-level clause, no MUST
    write_spec(&dir, "SHOULD", "log access attempts");
    // Test for the SHOULD clause fails — this must not trigger exit 1
    write_test(&dir, "spec__section__should_log_access_attempts", false);

    let out = std::process::Command::new(ought_bin())
        .arg("run")
        .current_dir(&dir)
        .output()
        .expect("failed to invoke ought run");

    assert_eq!(
        out.status.code(),
        Some(0),
        "ought run must exit 0 when only SHOULD-level tests fail \
         (SHOULD failures must not count as hard failures); \
         stderr: {} stdout: {}",
        String::from_utf8_lossy(&out.stderr),
        String::from_utf8_lossy(&out.stdout)
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// MUST exit with code 1 if all OTHERWISE clauses also fail
/// (full degradation chain exhausted).
/// GIVEN: a clause has an OTHERWISE chain and the primary obligation fails.
#[test]
fn test_cli__run__must_exit_with_code_1_if_all_otherwise_clauses_also_fail_full_deg() {
    let dir = unique_dir("otherwise_all_fail");
    scaffold_project(&dir);
    // Spec: MUST with an OTHERWISE fallback
    std::fs::write(
        dir.join("ought/spec.ought.md"),
        "# Spec\n\ncontext: test\n\n## Section\n\n\
         - **MUST** respond in under 100ms\n  \
         - **OTHERWISE** respond in under 1s\n",
    )
    .unwrap();

    // Both the primary and the OTHERWISE fallback fail — full chain exhausted
    write_test(
        &dir,
        "spec__section__must_respond_in_under_100ms",
        false,
    );
    write_test(
        &dir,
        "spec__section__must_respond_in_under_100ms__otherwise_respond_in_under_1s",
        false,
    );

    let out = std::process::Command::new(ought_bin())
        .arg("run")
        .current_dir(&dir)
        .output()
        .expect("failed to invoke ought run");

    assert_eq!(
        out.status.code(),
        Some(1),
        "ought run must exit 1 when the primary MUST and every OTHERWISE fallback \
         all fail (degradation chain exhausted); stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// MUST exit with code 1 if any MUST, MUST NOT, MUST ALWAYS, or MUST BY clause fails.
#[test]
fn test_cli__run__must_exit_with_code_1_if_any_must_must_not_must_always_or_must_by() {
    let dir = unique_dir("exit1_must");
    scaffold_project(&dir);
    write_spec(&dir, "MUST", "authenticate users");
    // Deliberately failing test for the MUST clause
    write_test(&dir, "spec__section__must_authenticate_users", false);

    let out = std::process::Command::new(ought_bin())
        .arg("run")
        .current_dir(&dir)
        .output()
        .expect("failed to invoke ought run");

    assert_eq!(
        out.status.code(),
        Some(1),
        "ought run must exit 1 when a MUST clause test fails; stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// MUST NOT trigger test generation — `ought run` only executes existing generated tests.
#[test]
fn test_cli__run__must_not_trigger_test_generation_ought_run_only_executes_existing_gen() {
    let dir = unique_dir("no_generate");
    scaffold_project(&dir);
    write_spec(&dir, "MUST", "return HTTP 200");
    write_test(&dir, "spec__section__must_return_http_200", true);

    // Snapshot the ought/ought-gen/ directory before running
    let gen_dir = dir.join("ought/ought-gen");
    let before: std::collections::BTreeSet<_> = walkdir(&gen_dir);

    // Run without any LLM API credentials; generation would fail loudly if attempted
    let out = std::process::Command::new(ought_bin())
        .arg("run")
        .current_dir(&dir)
        .env_remove("ANTHROPIC_API_KEY")
        .env_remove("OPENAI_API_KEY")
        .output()
        .expect("failed to invoke ought run");

    // Must not print an API-key complaint (which would only appear if generation ran)
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(
        !stderr.to_lowercase().contains("api key"),
        "ought run must not attempt LLM generation; stderr contained an API key \
         reference: {stderr}"
    );

    // No new test files must have been created
    let after: std::collections::BTreeSet<_> = walkdir(&gen_dir);
    assert_eq!(
        before, after,
        "ought run must not create new test files (generation must not be triggered)"
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// MUST parse all spec files, execute generated tests, and report results
/// mapped back to clauses.
#[test]
fn test_cli__run__must_parse_all_spec_files_execute_generated_tests_and_report_resu() {
    let dir = unique_dir("parse_all");
    scaffold_project(&dir);
    write_spec(&dir, "MUST", "authenticate users");
    write_test(&dir, "spec__section__must_authenticate_users", true);

    let out = std::process::Command::new(ought_bin())
        .arg("run")
        .current_dir(&dir)
        .output()
        .expect("failed to invoke ought run");

    assert_eq!(
        out.status.code(),
        Some(0),
        "ought run must exit 0 when all tests pass; stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );

    // Some output must be produced reporting on the results
    let combined = format!(
        "{}{}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );
    assert!(
        !combined.trim().is_empty(),
        "ought run must produce output reporting test results"
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// SHOULD print a summary at the end showing pass/fail counts by severity level.
#[test]
fn test_cli__run__should_print_a_summary_at_the_end_showing_pass_fail_counts_by_sever() {
    let dir = unique_dir("summary");
    scaffold_project(&dir);
    write_spec(&dir, "MUST", "authenticate users");
    write_test(&dir, "spec__section__must_authenticate_users", true);

    let out = std::process::Command::new(ought_bin())
        .arg("run")
        .current_dir(&dir)
        .output()
        .expect("failed to invoke ought run");

    let stdout = String::from_utf8_lossy(&out.stdout);
    // The summary must contain at least one count keyword.
    // The terminal reporter emits lines like "1 passed", "MUST coverage: 1/1 (100%)"
    assert!(
        stdout.contains("passed")
            || stdout.contains("failed")
            || stdout.contains("coverage"),
        "ought run must print a summary with pass/fail counts; stdout was:\n{stdout}"
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// SHOULD support `--fail-on-should` flag to also fail on SHOULD clause failures.
#[test]
fn test_cli__run__should_support_fail_on_should_flag_to_also_fail_on_should_clause_fa() {
    let dir = unique_dir("fail_on_should");
    scaffold_project(&dir);
    // Only a SHOULD clause — would normally be a soft failure
    write_spec(&dir, "SHOULD", "emit telemetry events");
    write_test(&dir, "spec__section__should_emit_telemetry_events", false);

    let out = std::process::Command::new(ought_bin())
        .arg("run")
        .arg("--fail-on-should")
        .current_dir(&dir)
        .output()
        .expect("failed to invoke ought run --fail-on-should");

    // Flag must be recognised by clap (not a usage error)
    assert_ne!(
        out.status.code(),
        Some(2),
        "--fail-on-should must be a recognised flag; stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );

    // With the flag set, a failing SHOULD test must cause exit 1
    assert_eq!(
        out.status.code(),
        Some(1),
        "ought run --fail-on-should must exit 1 when a SHOULD-level test fails; \
         stderr: {} stdout: {}",
        String::from_utf8_lossy(&out.stderr),
        String::from_utf8_lossy(&out.stdout)
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// WONT execute tests in parallel by default in v0.1 (sequential is fine to start).
/// Absence test: the CLI must not expose a `--parallel` flag.
#[test]
fn test_cli__run__wont_execute_tests_in_parallel_by_default_in_v0_1_sequential_is_f() {
    // Invoke without a project directory; clap argument parsing happens before
    // config is loaded, so an unknown flag is rejected immediately with exit 2.
    let out = std::process::Command::new(ought_bin())
        .arg("run")
        .arg("--parallel")
        .output()
        .expect("failed to invoke ought run --parallel");

    // clap returns exit code 2 for unrecognised flags.
    assert_eq!(
        out.status.code(),
        Some(2),
        "ought run must NOT expose a --parallel flag in v0.1 \
         (parallel test execution is intentionally absent); stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
}

