//! Generated tests for the `watch` subsection of the `cli` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use ought_cli::config::Config;
use ought_spec::{OughtMdParser, Parser, SpecGraph};
use ought_spec::types::*;

use crate::helpers::{
    ought_bin, scaffold_project, unique_dir, walkdir, write_spec, write_test,
};

/// MUST re-run affected specs when a change is detected
#[test]
fn test_cli__watch__must_re_run_affected_specs_when_a_change_is_detected() {
    let dir = unique_dir("watch_rerun");
    scaffold_project(&dir);
    write_spec(&dir, "MUST", "process items");
    write_test(&dir, "spec__section__must_process_items", true);

    let mut child = std::process::Command::new(ought_bin())
        .arg("watch")
        .current_dir(&dir)
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .expect("failed to spawn ought watch");

    // Allow the initial run to complete before triggering a change.
    std::thread::sleep(std::time::Duration::from_millis(1000));

    // Modify the spec file to trigger a re-run.
    let spec_path = dir.join("ought/spec.ought.md");
    let original = std::fs::read_to_string(&spec_path).unwrap_or_default();
    std::fs::write(&spec_path, format!("{}\n<!-- re-run trigger -->", original)).unwrap();

    // Wait long enough for the watcher to detect the change and complete a cycle.
    std::thread::sleep(std::time::Duration::from_millis(2000));

    let _ = child.kill();
    let output = child.wait_with_output().expect("failed to collect watch output");

    let combined = format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );

    // After the change the watcher must have re-run and reported results.
    // Look for markers that a test run occurred: "passed", "failed", or a clause id.
    let ran_again = combined.contains("passed")
        || combined.contains("failed")
        || combined.contains("must_process_items")
        || combined.contains("spec.ought.md");

    assert!(
        ran_again,
        "ought watch must re-run affected specs when a file change is detected; \
         output:\n{combined}"
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// MUST watch `ought.md` files and source files for changes
#[test]
fn test_cli__watch__must_watch_ought_md_files_and_source_files_for_changes() {
    let dir = unique_dir("watch_files");
    scaffold_project(&dir);
    write_spec(&dir, "MUST", "handle requests");

    // Create a source file that the watcher should also monitor.
    std::fs::create_dir_all(dir.join("src")).unwrap();
    std::fs::write(dir.join("src/lib.rs"), "// source file for watch test\n").unwrap();

    // Spawn ought watch as a long-running process.
    let mut child = std::process::Command::new(ought_bin())
        .arg("watch")
        .current_dir(&dir)
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .expect("failed to spawn ought watch");

    // Give the watcher time to start and establish file watches.
    std::thread::sleep(std::time::Duration::from_millis(400));

    // The process must not have exited with a usage error (code 2).
    if let Some(status) = child.try_wait().expect("failed to check child status") {
        assert_ne!(
            status.code(),
            Some(2),
            "ought watch must accept the `watch` subcommand without a usage error"
        );
    }
    // If still running, the watcher is active — expected behaviour.

    // Touch the spec file; a file watcher must pick this up.
    let spec_path = dir.join("ought/spec.ought.md");
    let original = std::fs::read_to_string(&spec_path).unwrap_or_default();
    std::fs::write(&spec_path, format!("{}\n<!-- touched -->", original)).unwrap();

    std::thread::sleep(std::time::Duration::from_millis(800));

    // Touch a source file; the watcher must monitor source paths too.
    std::fs::write(dir.join("src/lib.rs"), "// touched\n").unwrap();

    std::thread::sleep(std::time::Duration::from_millis(800));

    let _ = child.kill();
    let output = child.wait_with_output().expect("failed to collect watch output");

    // The watcher must have produced output, confirming it is actively watching.
    let combined = format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(
        !combined.trim().is_empty(),
        "ought watch must produce output while watching ought.md and source files; got nothing"
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// SHOULD clear the terminal and reprint results on each cycle
#[test]
fn test_cli__watch__should_clear_the_terminal_and_reprint_results_on_each_cycle() {
    let dir = unique_dir("watch_clear");
    scaffold_project(&dir);
    write_spec(&dir, "MUST", "return results");
    write_test(&dir, "spec__section__must_return_results", true);

    let mut child = std::process::Command::new(ought_bin())
        .arg("watch")
        .current_dir(&dir)
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .expect("failed to spawn ought watch");

    // Allow the first cycle to complete.
    std::thread::sleep(std::time::Duration::from_millis(1000));

    // Trigger a second cycle by modifying the spec.
    let spec_path = dir.join("ought/spec.ought.md");
    let original = std::fs::read_to_string(&spec_path).unwrap_or_default();
    std::fs::write(&spec_path, format!("{}\n<!-- cycle 2 -->", original)).unwrap();

    std::thread::sleep(std::time::Duration::from_millis(1500));

    let _ = child.kill();
    let output = child.wait_with_output().expect("failed to collect watch output");

    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);
    let combined = format!("{stdout}{stderr}");

    // A terminal clear is signalled by the ANSI escape sequence ESC[2J (erase
    // display) or the common ESC[H ESC[2J (move-home + erase) pattern.
    // Either form satisfies the "clear the terminal" requirement.
    let has_clear = combined.contains("\x1b[2J")
        || combined.contains("\x1b[H")
        || combined.contains("\x1bc"); // full terminal reset

    assert!(
        has_clear,
        "ought watch should emit an ANSI clear-screen sequence (ESC[2J or equivalent) \
         before reprinting results on each cycle; stdout was:\n{stdout}"
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// SHOULD debounce rapid file changes (at least 500ms)
#[test]
fn test_cli__watch__should_debounce_rapid_file_changes_at_least_500ms() {
    let dir = unique_dir("watch_debounce");
    scaffold_project(&dir);
    write_spec(&dir, "MUST", "validate input");
    write_test(&dir, "spec__section__must_validate_input", true);

    let mut child = std::process::Command::new(ought_bin())
        .arg("watch")
        .current_dir(&dir)
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .expect("failed to spawn ought watch");

    // Let the watcher initialise.
    std::thread::sleep(std::time::Duration::from_millis(800));

    // Fire five rapid spec-file changes within ~100 ms — well inside the 500 ms
    // debounce window.  A correct implementation collapses these into one run.
    let spec_path = dir.join("ought/spec.ought.md");
    for i in 0..5u8 {
        let base = std::fs::read_to_string(&spec_path).unwrap_or_default();
        std::fs::write(&spec_path, format!("{}\n<!-- burst {} -->", base, i)).unwrap();
        std::thread::sleep(std::time::Duration::from_millis(50));
    }

    // Wait long enough for exactly one debounced cycle to finish.
    std::thread::sleep(std::time::Duration::from_millis(1500));

    let _ = child.kill();
    let output = child.wait_with_output().expect("failed to collect watch output");

    let combined = format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );

    // Count cycle-start markers. `ought watch` emits "ought watch: checking N
    // spec(s)..." exactly once per cycle (initial + each debounced burst), so
    // it's a deterministic per-cycle marker — unlike words like "passed" or
    // "running" which appear multiple times within a single cycle's output and
    // cause the test to be flaky depending on output flush timing.
    // A debounced watcher fires at most once for the burst, so we accept up to
    // 2 cycles (initial + 1 debounced); we must not see 5.
    let run_count = combined.matches("ought watch: checking").count();

    assert!(
        run_count <= 2,
        "ought watch should debounce rapid changes into at most 1 re-run cycle \
         (got {} apparent run markers); debounce window must be ≥500 ms\noutput:\n{combined}",
        run_count
    );

    let _ = std::fs::remove_dir_all(&dir);
}

