//! Generated tests for the `agent_assignment` subsection of the `generator` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

#![allow(dead_code, clippy::all)]
#![allow(non_snake_case, unused_imports)]
use std::path::{Path, PathBuf};
use std::fs;
use std::time::Duration;
use std::collections::HashMap;
use ought_spec::types::*;
use ought_spec::parser::{OughtMdParser, Parser};
use ought_gen::generator::*;
use ought_gen::manifest::*;

// ============================================================================
// manifest_and_hashing (6 tests)
// ============================================================================

/// MUST compute a clause hash from the keyword + clause text + context metadata

/// AgentAssignment must serialize and deserialize via serde_json
#[test]
fn test_generator__agent_assignment__must_round_trip_through_json() {
    use ought_gen::{AgentAssignment, AssignmentGroup, AssignmentClause};

    let assignment = AgentAssignment {
        id: "agent_0".to_string(),
        project_root: "/tmp/project".to_string(),
        config_path: "/tmp/project/ought.toml".to_string(),
        test_dir: "/tmp/project/ought/ought-gen".to_string(),
        target_language: "rust".to_string(),
        source_paths: vec!["src/auth/".to_string()],
        groups: vec![
            AssignmentGroup {
                section_path: "Auth > Login".to_string(),
                clauses: vec![
                    AssignmentClause {
                        id: "auth::login::must_return_jwt".to_string(),
                        keyword: "MUST".to_string(),
                        text: "return a JWT on success".to_string(),
                        condition: None,
                        temporal: None,
                        content_hash: "abc123".to_string(),
                        hints: vec![],
                        otherwise: vec![],
                    },
                ],
                conditions: vec!["the user provides valid credentials".to_string()],
            },
        ],
    };

    let json = serde_json::to_string(&assignment).expect("serialization must succeed");
    let deserialized: AgentAssignment =
        serde_json::from_str(&json).expect("deserialization must succeed");

    assert_eq!(deserialized.id, "agent_0");
    assert_eq!(deserialized.groups.len(), 1);
    assert_eq!(deserialized.groups[0].clauses.len(), 1);
    assert_eq!(
        deserialized.groups[0].clauses[0].id,
        "auth::login::must_return_jwt"
    );
}

