//! Generated tests for the `agent_report` subsection of the `generator` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

#![allow(dead_code, clippy::all)]
#![allow(non_snake_case, unused_imports)]
use std::path::{Path, PathBuf};
use std::fs;
use std::time::Duration;
use std::collections::HashMap;
use ought_spec::types::*;
use ought_spec::parser::{OughtMdParser, Parser};
use ought_gen::generator::*;
use ought_gen::manifest::*;

// ============================================================================
// manifest_and_hashing (6 tests)
// ============================================================================

/// MUST compute a clause hash from the keyword + clause text + context metadata

/// AgentReport tracks generated count and errors
#[test]
fn test_generator__agent_report__tracks_generated_and_errors() {
    use ought_gen::AgentReport;

    let report = AgentReport {
        generated: 5,
        errors: vec!["clause X failed".to_string()],
    };
    assert_eq!(report.generated, 5);
    assert_eq!(report.errors.len(), 1);

    let empty_report = AgentReport::default();
    assert_eq!(empty_report.generated, 0);
    assert!(empty_report.errors.is_empty());
}

// ============================================================================
// error_handling: manifest consistency (1 test)
// ============================================================================

