//! Generated tests for the `error_handling` subsection of the `generator` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

#![allow(dead_code, clippy::all)]
#![allow(non_snake_case, unused_imports)]
use std::path::{Path, PathBuf};
use std::fs;
use std::time::Duration;
use std::collections::HashMap;
use ought_spec::types::*;
use ought_spec::parser::{OughtMdParser, Parser};
use ought_gen::generator::*;
use ought_gen::manifest::*;

// ============================================================================
// manifest_and_hashing (6 tests)
// ============================================================================

/// MUST compute a clause hash from the keyword + clause text + context metadata

/// MUST NOT leave the manifest in an inconsistent state if generation is interrupted
#[test]
fn test_generator__error_handling__must_not_leave_the_manifest_in_an_inconsistent_state_if_generation_is() {
    use chrono::Utc;

    let dir = std::env::temp_dir().join(format!(
        "ought_manifest_consistency_{}",
        std::process::id()
    ));
    std::fs::create_dir_all(&dir).unwrap();
    let manifest_path = dir.join("manifest.toml");

    // Phase 1: successful generation of clause_a; manifest saved
    let mut manifest = Manifest { entries: HashMap::new() };
    manifest.entries.insert(
        "generator::error_handling::clause_a".to_string(),
        ManifestEntry {
            clause_hash: "abc123".to_string(),
            source_hash: "src456".to_string(),
            generated_at: Utc::now(),
            model: "claude-sonnet-4-6".to_string(),
        },
    );
    manifest.save(&manifest_path).expect("save after clause_a must succeed");

    // Phase 2: generation of clause_b is interrupted before manifest save
    // (we never call manifest.save again)

    // Phase 3: load the manifest and verify it is well-formed
    let loaded = Manifest::load(&manifest_path)
        .expect("manifest must load cleanly after interrupted generation");

    assert_eq!(
        loaded.entries.len(),
        1,
        "must_not_leave_manifest_inconsistent: only committed entries must appear; \
         got {} entries, want 1",
        loaded.entries.len()
    );
    assert!(
        loaded.entries.contains_key("generator::error_handling::clause_a"),
        "must_not_leave_manifest_inconsistent: committed clause_a must be present"
    );
    assert!(
        !loaded.entries.contains_key("generator::error_handling::clause_b"),
        "must_not_leave_manifest_inconsistent: clause_b (never saved) must not appear"
    );

    // Each present entry must be fully populated
    let entry = &loaded.entries["generator::error_handling::clause_a"];
    assert!(
        !entry.clause_hash.is_empty(),
        "must_not_leave_manifest_inconsistent: clause_hash must not be empty"
    );
    assert!(
        !entry.source_hash.is_empty(),
        "must_not_leave_manifest_inconsistent: source_hash must not be empty"
    );
    assert!(
        !entry.model.is_empty(),
        "must_not_leave_manifest_inconsistent: model must not be empty"
    );

    // Idempotent reload
    let reloaded = Manifest::load(&manifest_path)
        .expect("manifest must be loadable a second time");
    assert_eq!(
        reloaded.entries.len(),
        loaded.entries.len(),
        "must_not_leave_manifest_inconsistent: re-loading must return same entry count"
    );

    let _ = std::fs::remove_dir_all(&dir);
}

