//! Generated tests for the `given_block_display` subsection of the `reporter` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

#![allow(dead_code, clippy::all)]
#![allow(non_snake_case)]

//! Generated tests for ought-report, rewritten to use the real API.
//!
//! Categories covered:
//!   - terminal_output (10 tests)
//!   - failure_details (4 tests)
//!   - given_block_display (4 tests)
//!   - json_output (3 tests -- diagnosis/grade test removed since those features are stubbed)
//!   - junit_xml_output (5 tests)
//!   - otherwise_chain_display (5 tests)
//!   - temporal_result_display (3 tests)
//!
//! Removed categories (stubbed/non-reporter functionality):
//!   - failure_narratives_llm_powered (7 tests) -- diagnosis is stubbed
//!   - test_quality_grading (6 tests) -- grading is stubbed
//!   - progress_during_generation (3 tests) -- not part of reporter

use std::path::PathBuf;
use std::time::Duration;

use ought_report::types::{ColorChoice, ReportOptions};
use ought_run::{RunResult, TestDetails, TestResult, TestStatus};
use ought_spec::{Clause, ClauseId, Keyword, Metadata, Section, SourceLocation, Spec, Temporal};

// ── Test data builders ──────────────────────────────────────────────────────

fn make_clause(keyword: Keyword, text: &str, id: &str) -> Clause {
    Clause {
        id: ClauseId(id.to_string()),
        keyword,
        severity: keyword.severity(),
        text: text.to_string(),
        condition: None,
        otherwise: vec![],
        temporal: None,
        hints: vec![],
        source_location: SourceLocation {
            file: PathBuf::from("test.ought.md"),
            line: 1,
        },
        content_hash: "test".to_string(),
        pending: false,
    }
}

fn make_section(title: &str, clauses: Vec<Clause>) -> Section {
    Section {
        title: title.to_string(),
        depth: 1,
        prose: String::new(),
        clauses,
        subsections: vec![],
    }
}

fn make_spec(name: &str, sections: Vec<Section>) -> Spec {
    Spec {
        name: name.to_string(),
        metadata: Metadata::default(),
        sections,
        source_path: PathBuf::from("test.ought.md"),
    }
}

fn make_result(clause_id: &str, status: TestStatus) -> TestResult {
    TestResult {
        clause_id: ClauseId(clause_id.to_string()),
        status,
        message: None,
        duration: Duration::from_millis(10),
        details: TestDetails::default(),
    }
}

fn make_result_with_message(clause_id: &str, status: TestStatus, msg: &str) -> TestResult {
    TestResult {
        clause_id: ClauseId(clause_id.to_string()),
        status,
        message: Some(msg.to_string()),
        duration: Duration::from_millis(10),
        details: TestDetails::default(),
    }
}

fn make_result_with_failure_detail(clause_id: &str, status: TestStatus, failure_msg: &str) -> TestResult {
    TestResult {
        clause_id: ClauseId(clause_id.to_string()),
        status,
        message: None,
        duration: Duration::from_millis(10),
        details: TestDetails {
            failure_message: Some(failure_msg.to_string()),
            ..Default::default()
        },
    }
}

fn make_run_result(results: Vec<TestResult>) -> RunResult {
    let total: Duration = results.iter().map(|r| r.duration).sum();
    RunResult {
        results,
        total_duration: total,
    }
}

fn no_color_options() -> ReportOptions {
    ReportOptions {
        color: ColorChoice::Never,
        ..Default::default()
    }
}

fn color_options() -> ReportOptions {
    ReportOptions {
        color: ColorChoice::Always,
        ..Default::default()
    }
}

fn render_terminal(run: &RunResult, specs: &[Spec], opts: &ReportOptions) -> String {
    let mut buf: Vec<u8> = Vec::new();
    ought_report::terminal::report_to_writer(&mut buf, run, specs, opts)
        .expect("report_to_writer should succeed");
    String::from_utf8(buf).expect("output should be valid UTF-8")
}

// ── ANSI escape code constants ──────────────────────────────────────────────

const RED: &str = "\x1b[31m";
const YELLOW: &str = "\x1b[33m";
const DIM: &str = "\x1b[2m";
const BOLD: &str = "\x1b[1m";
#[allow(dead_code)]
const RESET: &str = "\x1b[0m";

// ═══════════════════════════════════════════════════════════════════════════
// TERMINAL OUTPUT TESTS
// ═══════════════════════════════════════════════════════════════════════════

/// MUST show each clause with its keyword, text, and pass/fail status

/// MUST display GIVEN blocks as a visual group with the condition as a header line
#[test]
fn test_reporter__given_block_display__must_display_given_as_visual_group() {
    let mut given_clause = make_clause(Keyword::Given, "the user is authenticated", "given::auth");
    // GIVEN clauses contain their children in `otherwise` in the current data model.
    given_clause.otherwise = vec![
        make_clause(Keyword::Must, "return their profile data", "given::auth::must_profile"),
        make_clause(Keyword::Must, "NOT return other users' data", "given::auth::must_not_leak"),
    ];

    let specs = vec![make_spec(
        "GIVEN Spec",
        vec![make_section("Access", vec![given_clause])],
    )];

    let run = make_run_result(vec![
        make_result("given::auth::must_profile", TestStatus::Passed),
        make_result("given::auth::must_not_leak", TestStatus::Failed),
    ]);

    let text = render_terminal(&run, &specs, &no_color_options());

    // The GIVEN condition must appear as a header.
    assert!(
        text.contains("GIVEN the user is authenticated"),
        "GIVEN header must appear in output; got:\n{text}"
    );

    // Both child clauses must follow the GIVEN header.
    let header_pos = text.find("GIVEN the user is authenticated").unwrap();
    let clause1_pos = text.find("return their profile data").unwrap();
    let clause2_pos = text.find("NOT return other users' data").unwrap();
    assert!(header_pos < clause1_pos, "GIVEN header must precede first child clause");
    assert!(header_pos < clause2_pos, "GIVEN header must precede second child clause");
}


/// MUST indent clauses under their GIVEN condition to show the relationship
#[test]
fn test_reporter__given_block_display__must_indent_clauses_under_given() {
    let mut given_clause = make_clause(Keyword::Given, "the token is expired", "given::token");
    given_clause.otherwise = vec![
        make_clause(Keyword::Must, "return 401", "given::token::must_401"),
        make_clause(Keyword::Should, "include WWW-Authenticate", "given::token::should_www"),
    ];

    let specs = vec![make_spec(
        "GIVEN Indent Spec",
        vec![make_section("Auth", vec![given_clause])],
    )];

    let run = make_run_result(vec![
        make_result("given::token::must_401", TestStatus::Passed),
        make_result("given::token::should_www", TestStatus::Passed),
    ]);

    let text = render_terminal(&run, &specs, &no_color_options());

    let given_line = text
        .lines()
        .find(|l| l.contains("GIVEN the token is expired"))
        .expect("GIVEN header must be present");

    let child_line = text
        .lines()
        .find(|l| l.contains("return 401"))
        .expect("child clause must be present");

    // Leading whitespace on the child must be >= header (child is rendered at depth+1).
    let given_indent = given_line.len() - given_line.trim_start().len();
    let child_indent = child_line.len() - child_line.trim_start().len();
    assert!(
        child_indent >= given_indent,
        "child clause indent ({child_indent}) must be >= GIVEN header indent ({given_indent})"
    );
}


/// SHOULD dim the GIVEN condition line when all nested clauses pass
#[test]
fn test_reporter__given_block_display__should_dim_when_all_nested_pass() {
    let mut given_clause = make_clause(Keyword::Given, "the token is expired", "given::dim");
    given_clause.otherwise = vec![
        make_clause(Keyword::Must, "return 401", "given::dim::must_401"),
        make_clause(Keyword::Should, "include WWW-Authenticate", "given::dim::should_www"),
    ];

    let specs = vec![make_spec(
        "GIVEN Dim Spec",
        vec![make_section("Auth", vec![given_clause])],
    )];

    let run = make_run_result(vec![
        make_result("given::dim::must_401", TestStatus::Passed),
        make_result("given::dim::should_www", TestStatus::Passed),
    ]);

    let text = render_terminal(&run, &specs, &color_options());

    let given_line = text
        .lines()
        .find(|l| l.contains("GIVEN the token is expired"))
        .expect("GIVEN header must be present");

    // When all children pass, the GIVEN header should be dimmed (not bold).
    assert!(
        given_line.contains(DIM),
        "GIVEN header must carry DIM when all nested clauses pass, got: {given_line:?}"
    );
    assert!(
        !given_line.contains(BOLD),
        "GIVEN header must NOT be bold when all nested clauses pass, got: {given_line:?}"
    );
}


/// SHOULD highlight the GIVEN condition line when any nested clause fails
#[test]
fn test_reporter__given_block_display__should_highlight_when_nested_fails() {
    let mut given_clause = make_clause(Keyword::Given, "the user is authenticated", "given::hl");
    given_clause.otherwise = vec![
        make_clause(Keyword::Must, "return profile", "given::hl::must_profile"),
        make_clause(Keyword::Must, "NOT leak data", "given::hl::must_not_leak"),
    ];

    let specs = vec![make_spec(
        "GIVEN HL Spec",
        vec![make_section("Access", vec![given_clause])],
    )];

    let run = make_run_result(vec![
        make_result("given::hl::must_profile", TestStatus::Passed),
        make_result("given::hl::must_not_leak", TestStatus::Failed),
    ]);

    let text = render_terminal(&run, &specs, &color_options());

    let given_line = text
        .lines()
        .find(|l| l.contains("GIVEN the user is authenticated"))
        .expect("GIVEN header must be present");

    assert!(
        given_line.contains(BOLD),
        "GIVEN header must be bold when any nested clause fails, got: {given_line:?}"
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// JSON OUTPUT TESTS
// ═══════════════════════════════════════════════════════════════════════════

