//! Generated tests for the `json_output` subsection of the `reporter` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

#![allow(dead_code, clippy::all)]
#![allow(non_snake_case)]

//! Generated tests for ought-report, rewritten to use the real API.
//!
//! Categories covered:
//!   - terminal_output (10 tests)
//!   - failure_details (4 tests)
//!   - given_block_display (4 tests)
//!   - json_output (3 tests -- diagnosis/grade test removed since those features are stubbed)
//!   - junit_xml_output (5 tests)
//!   - otherwise_chain_display (5 tests)
//!   - temporal_result_display (3 tests)
//!
//! Removed categories (stubbed/non-reporter functionality):
//!   - failure_narratives_llm_powered (7 tests) -- diagnosis is stubbed
//!   - test_quality_grading (6 tests) -- grading is stubbed
//!   - progress_during_generation (3 tests) -- not part of reporter

use std::path::PathBuf;
use std::time::Duration;

use ought_report::types::{ColorChoice, ReportOptions};
use ought_run::{RunResult, TestDetails, TestResult, TestStatus};
use ought_spec::{Clause, ClauseId, Keyword, Metadata, Section, SourceLocation, Spec, Temporal};

// ── Test data builders ──────────────────────────────────────────────────────

fn make_clause(keyword: Keyword, text: &str, id: &str) -> Clause {
    Clause {
        id: ClauseId(id.to_string()),
        keyword,
        severity: keyword.severity(),
        text: text.to_string(),
        condition: None,
        otherwise: vec![],
        temporal: None,
        hints: vec![],
        source_location: SourceLocation {
            file: PathBuf::from("test.ought.md"),
            line: 1,
        },
        content_hash: "test".to_string(),
        pending: false,
    }
}

fn make_section(title: &str, clauses: Vec<Clause>) -> Section {
    Section {
        title: title.to_string(),
        depth: 1,
        prose: String::new(),
        clauses,
        subsections: vec![],
    }
}

fn make_spec(name: &str, sections: Vec<Section>) -> Spec {
    Spec {
        name: name.to_string(),
        metadata: Metadata::default(),
        sections,
        source_path: PathBuf::from("test.ought.md"),
    }
}

fn make_result(clause_id: &str, status: TestStatus) -> TestResult {
    TestResult {
        clause_id: ClauseId(clause_id.to_string()),
        status,
        message: None,
        duration: Duration::from_millis(10),
        details: TestDetails::default(),
    }
}

fn make_result_with_message(clause_id: &str, status: TestStatus, msg: &str) -> TestResult {
    TestResult {
        clause_id: ClauseId(clause_id.to_string()),
        status,
        message: Some(msg.to_string()),
        duration: Duration::from_millis(10),
        details: TestDetails::default(),
    }
}

fn make_result_with_failure_detail(clause_id: &str, status: TestStatus, failure_msg: &str) -> TestResult {
    TestResult {
        clause_id: ClauseId(clause_id.to_string()),
        status,
        message: None,
        duration: Duration::from_millis(10),
        details: TestDetails {
            failure_message: Some(failure_msg.to_string()),
            ..Default::default()
        },
    }
}

fn make_run_result(results: Vec<TestResult>) -> RunResult {
    let total: Duration = results.iter().map(|r| r.duration).sum();
    RunResult {
        results,
        total_duration: total,
    }
}

fn no_color_options() -> ReportOptions {
    ReportOptions {
        color: ColorChoice::Never,
        ..Default::default()
    }
}

fn color_options() -> ReportOptions {
    ReportOptions {
        color: ColorChoice::Always,
        ..Default::default()
    }
}

fn render_terminal(run: &RunResult, specs: &[Spec], opts: &ReportOptions) -> String {
    let mut buf: Vec<u8> = Vec::new();
    ought_report::terminal::report_to_writer(&mut buf, run, specs, opts)
        .expect("report_to_writer should succeed");
    String::from_utf8(buf).expect("output should be valid UTF-8")
}

// ── ANSI escape code constants ──────────────────────────────────────────────

const RED: &str = "\x1b[31m";
const YELLOW: &str = "\x1b[33m";
const DIM: &str = "\x1b[2m";
const BOLD: &str = "\x1b[1m";
#[allow(dead_code)]
const RESET: &str = "\x1b[0m";

// ═══════════════════════════════════════════════════════════════════════════
// TERMINAL OUTPUT TESTS
// ═══════════════════════════════════════════════════════════════════════════

/// MUST show each clause with its keyword, text, and pass/fail status

/// MUST support --json flag that outputs structured results as JSON
#[test]
fn test_reporter__json_output__must_support_json_flag() {
    let specs = vec![make_spec(
        "API Spec",
        vec![make_section(
            "Endpoints",
            vec![make_clause(Keyword::Must, "return HTTP 200", "api::endpoints::200")],
        )],
    )];

    let run = make_run_result(vec![make_result("api::endpoints::200", TestStatus::Passed)]);

    let output = ought_report::json::report(&run, &specs).expect("json::report must not fail");

    assert!(!output.is_empty(), "JSON output must not be empty");

    let parsed: serde_json::Value =
        serde_json::from_str(&output).expect("output must be valid JSON");

    assert!(parsed.is_object(), "JSON output must be a top-level object");

    assert!(
        parsed.get("specs").map_or(false, |v| v.is_array()),
        "JSON report must contain a 'specs' array"
    );
    assert!(
        parsed.get("summary").map_or(false, |v| v.is_object()),
        "JSON report must contain a 'summary' object"
    );
    assert!(
        parsed.get("total_duration_ms").map_or(false, |v| v.is_number()),
        "JSON report must contain a 'total_duration_ms' number"
    );
}


/// MUST include all fields: clause identifier, keyword, severity, status, failure message, duration
#[test]
fn test_reporter__json_output__must_include_all_fields() {
    let clause_id_str = "auth::login::must_return_401";
    let failure_msg = "expected status 401, got 200";

    let specs = vec![make_spec(
        "Auth Spec",
        vec![make_section(
            "Login",
            vec![make_clause(Keyword::Must, "return 401 for invalid credentials", clause_id_str)],
        )],
    )];

    let run = make_run_result(vec![TestResult {
        clause_id: ClauseId(clause_id_str.to_string()),
        status: TestStatus::Failed,
        message: Some(failure_msg.to_string()),
        duration: Duration::from_millis(22),
        details: TestDetails::default(),
    }]);

    let output = ought_report::json::report(&run, &specs).expect("json::report must not fail");
    let parsed: serde_json::Value = serde_json::from_str(&output).expect("valid JSON");

    let results = parsed["specs"][0]["results"]
        .as_array()
        .expect("specs[0].results must be a JSON array");
    assert_eq!(results.len(), 1, "must emit exactly one clause result entry");

    let entry = &results[0];

    // clause identifier
    assert_eq!(entry["clause_id"].as_str().unwrap(), clause_id_str);
    // keyword
    assert_eq!(entry["keyword"].as_str().unwrap(), "MUST");
    // severity
    assert_eq!(entry["severity"].as_str().unwrap(), "required");
    // status
    assert_eq!(entry["status"].as_str().unwrap(), "failed");
    // failure message
    assert_eq!(entry["message"].as_str().unwrap(), failure_msg);
    // duration
    let dur = entry["duration_ms"].as_f64().expect("duration_ms must be a number");
    assert!(dur > 0.0, "duration_ms must be positive, got {dur}");
    assert!(
        (dur - 22.0).abs() < 1.0,
        "duration_ms must approximate 22ms, got {dur}"
    );
}


/// MUST NOT mix JSON output with human-readable output
#[test]
fn test_reporter__json_output__must_not_mix_with_human_readable() {
    let specs = vec![make_spec(
        "DB Spec",
        vec![make_section(
            "Query",
            vec![make_clause(Keyword::Should, "return results within 100ms", "db::query::sla")],
        )],
    )];

    let run = make_run_result(vec![make_result("db::query::sla", TestStatus::Passed)]);

    let json_output = ought_report::json::report(&run, &specs).expect("json::report must not fail");

    // The entire output string must parse as JSON.
    let _parsed: serde_json::Value =
        serde_json::from_str(&json_output).expect("must be valid JSON");

    // No ANSI escape codes.
    assert!(!json_output.contains("\x1b["), "JSON must not contain ANSI escape codes");

    // No terminal status icons.
    for indicator in &["\u{2713}", "\u{2717}", "\u{2298}"] {
        assert!(
            !json_output.contains(indicator),
            "JSON must not contain terminal indicator '{indicator}'"
        );
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// JUNIT XML OUTPUT TESTS
// ═══════════════════════════════════════════════════════════════════════════

