//! Generated tests for the `otherwise_chain` subsection of the `reporter` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

#![allow(dead_code, clippy::all)]
#![allow(non_snake_case)]

//! Generated tests for ought-report, rewritten to use the real API.
//!
//! Categories covered:
//!   - terminal_output (10 tests)
//!   - failure_details (4 tests)
//!   - given_block_display (4 tests)
//!   - json_output (3 tests -- diagnosis/grade test removed since those features are stubbed)
//!   - junit_xml_output (5 tests)
//!   - otherwise_chain_display (5 tests)
//!   - temporal_result_display (3 tests)
//!
//! Removed categories (stubbed/non-reporter functionality):
//!   - failure_narratives_llm_powered (7 tests) -- diagnosis is stubbed
//!   - test_quality_grading (6 tests) -- grading is stubbed
//!   - progress_during_generation (3 tests) -- not part of reporter

use std::path::PathBuf;
use std::time::Duration;

use ought_report::types::{ColorChoice, ReportOptions};
use ought_run::{RunResult, TestDetails, TestResult, TestStatus};
use ought_spec::{Clause, ClauseId, Keyword, Metadata, Section, SourceLocation, Spec, Temporal};

// ── Test data builders ──────────────────────────────────────────────────────

fn make_clause(keyword: Keyword, text: &str, id: &str) -> Clause {
    Clause {
        id: ClauseId(id.to_string()),
        keyword,
        severity: keyword.severity(),
        text: text.to_string(),
        condition: None,
        otherwise: vec![],
        temporal: None,
        hints: vec![],
        source_location: SourceLocation {
            file: PathBuf::from("test.ought.md"),
            line: 1,
        },
        content_hash: "test".to_string(),
        pending: false,
    }
}

fn make_section(title: &str, clauses: Vec<Clause>) -> Section {
    Section {
        title: title.to_string(),
        depth: 1,
        prose: String::new(),
        clauses,
        subsections: vec![],
    }
}

fn make_spec(name: &str, sections: Vec<Section>) -> Spec {
    Spec {
        name: name.to_string(),
        metadata: Metadata::default(),
        sections,
        source_path: PathBuf::from("test.ought.md"),
    }
}

fn make_result(clause_id: &str, status: TestStatus) -> TestResult {
    TestResult {
        clause_id: ClauseId(clause_id.to_string()),
        status,
        message: None,
        duration: Duration::from_millis(10),
        details: TestDetails::default(),
    }
}

fn make_result_with_message(clause_id: &str, status: TestStatus, msg: &str) -> TestResult {
    TestResult {
        clause_id: ClauseId(clause_id.to_string()),
        status,
        message: Some(msg.to_string()),
        duration: Duration::from_millis(10),
        details: TestDetails::default(),
    }
}

fn make_result_with_failure_detail(clause_id: &str, status: TestStatus, failure_msg: &str) -> TestResult {
    TestResult {
        clause_id: ClauseId(clause_id.to_string()),
        status,
        message: None,
        duration: Duration::from_millis(10),
        details: TestDetails {
            failure_message: Some(failure_msg.to_string()),
            ..Default::default()
        },
    }
}

fn make_run_result(results: Vec<TestResult>) -> RunResult {
    let total: Duration = results.iter().map(|r| r.duration).sum();
    RunResult {
        results,
        total_duration: total,
    }
}

fn no_color_options() -> ReportOptions {
    ReportOptions {
        color: ColorChoice::Never,
        ..Default::default()
    }
}

fn color_options() -> ReportOptions {
    ReportOptions {
        color: ColorChoice::Always,
        ..Default::default()
    }
}

fn render_terminal(run: &RunResult, specs: &[Spec], opts: &ReportOptions) -> String {
    let mut buf: Vec<u8> = Vec::new();
    ought_report::terminal::report_to_writer(&mut buf, run, specs, opts)
        .expect("report_to_writer should succeed");
    String::from_utf8(buf).expect("output should be valid UTF-8")
}

// ── ANSI escape code constants ──────────────────────────────────────────────

const RED: &str = "\x1b[31m";
const YELLOW: &str = "\x1b[33m";
const DIM: &str = "\x1b[2m";
const BOLD: &str = "\x1b[1m";
#[allow(dead_code)]
const RESET: &str = "\x1b[0m";

// ═══════════════════════════════════════════════════════════════════════════
// TERMINAL OUTPUT TESTS
// ═══════════════════════════════════════════════════════════════════════════

/// MUST show each clause with its keyword, text, and pass/fail status

/// MUST display OTHERWISE clauses indented under their parent obligation
#[test]
fn test_reporter__otherwise_chain__must_display_indented_under_parent() {
    let mut parent = make_clause(Keyword::Must, "respond within 200ms", "ow::parent");
    parent.otherwise = vec![
        make_clause(Keyword::Otherwise, "return a cached response", "ow::cached"),
        make_clause(Keyword::Otherwise, "return 504", "ow::504"),
    ];

    let specs = vec![make_spec(
        "OW Spec",
        vec![make_section("Performance", vec![parent])],
    )];

    let run = make_run_result(vec![
        make_result("ow::parent", TestStatus::Failed),
        make_result("ow::cached", TestStatus::Passed),
        make_result("ow::504", TestStatus::Skipped),
    ]);

    let text = render_terminal(&run, &specs, &no_color_options());

    // OTHERWISE clause text must appear after parent.
    let parent_pos = text.find("respond within 200ms").expect("parent must be in output");
    let ow1_pos = text.find("return a cached response").expect("first OTHERWISE must be in output");
    let ow2_pos = text.find("return 504").expect("second OTHERWISE must be in output");
    assert!(parent_pos < ow1_pos, "parent must precede first OTHERWISE");
    assert!(parent_pos < ow2_pos, "parent must precede second OTHERWISE");

    // OTHERWISE lines must carry strictly more leading whitespace than parent.
    let parent_line = text.lines().find(|l| l.contains("respond within 200ms")).unwrap();
    let ow1_line = text.lines().find(|l| l.contains("return a cached response")).unwrap();

    let parent_indent = parent_line.len() - parent_line.trim_start().len();
    let ow1_indent = ow1_line.len() - ow1_line.trim_start().len();
    assert!(
        ow1_indent > parent_indent,
        "OTHERWISE indent ({ow1_indent}) must exceed parent indent ({parent_indent})"
    );
}


/// MUST use a distinct indicator for OTHERWISE results: arrow prefix
#[test]
fn test_reporter__otherwise_chain__must_use_arrow_indicator() {
    let mut parent = make_clause(Keyword::Must, "respond within 200ms", "ow2::parent");
    parent.otherwise = vec![
        make_clause(Keyword::Otherwise, "return a cached response", "ow2::cached"),
        make_clause(Keyword::Otherwise, "return 504", "ow2::504"),
    ];

    let specs = vec![make_spec(
        "OW Arrow Spec",
        vec![make_section("Performance", vec![parent])],
    )];

    let run = make_run_result(vec![
        make_result("ow2::parent", TestStatus::Failed),
        make_result("ow2::cached", TestStatus::Passed),
        make_result("ow2::504", TestStatus::Skipped),
    ]);

    let text = render_terminal(&run, &specs, &no_color_options());

    // Every OTHERWISE line must include the arrow prefix.
    for clause_text in &["return a cached response", "return 504"] {
        let ow_line = text
            .lines()
            .find(|l| l.contains(clause_text))
            .unwrap_or_else(|| panic!("OTHERWISE clause '{clause_text}' must be in output"));
        assert!(
            ow_line.contains("\u{21b3}"),
            "OTHERWISE line must carry the arrow prefix, got: {ow_line:?}"
        );
    }

    // The parent obligation line must NOT carry the arrow.
    let parent_line = text.lines().find(|l| l.contains("respond within 200ms")).unwrap();
    assert!(
        !parent_line.contains("\u{21b3}"),
        "parent clause line must NOT carry the arrow, got: {parent_line:?}"
    );
}


/// MUST show the full chain status: if parent passes, OTHERWISE shows as ~ (not needed)
#[test]
fn test_reporter__otherwise_chain__must_show_skipped_when_parent_passes() {
    let mut parent = make_clause(Keyword::Must, "respond within 200ms", "ow3::parent");
    parent.otherwise = vec![
        make_clause(Keyword::Otherwise, "return a cached response", "ow3::cached"),
        make_clause(Keyword::Otherwise, "return 504", "ow3::504"),
    ];

    let specs = vec![make_spec(
        "OW Pass Spec",
        vec![make_section("Performance", vec![parent])],
    )];

    let run = make_run_result(vec![
        make_result("ow3::parent", TestStatus::Passed),
        make_result("ow3::cached", TestStatus::Skipped),
        make_result("ow3::504", TestStatus::Skipped),
    ]);

    let text = render_terminal(&run, &specs, &no_color_options());

    // Parent must show checkmark.
    let parent_line = text.lines().find(|l| l.contains("respond within 200ms")).unwrap();
    assert!(parent_line.contains("\u{2713}"), "passing parent must show checkmark, got: {parent_line:?}");

    // OTHERWISE clauses must show ~.
    for clause_text in &["return a cached response", "return 504"] {
        let ow_line = text.lines().find(|l| l.contains(clause_text)).unwrap();
        assert!(ow_line.contains("~"), "OTHERWISE must show ~ when parent passes, got: {ow_line:?}");
    }
}


/// MUST show which OTHERWISE level caught the failure
#[test]
fn test_reporter__otherwise_chain__must_show_which_level_caught_failure() {
    // Scenario: first OTHERWISE catches the failure
    let mut parent = make_clause(Keyword::Must, "respond within 200ms", "ow4::parent");
    parent.otherwise = vec![
        make_clause(Keyword::Otherwise, "return a cached response", "ow4::cached"),
        make_clause(Keyword::Otherwise, "return 504", "ow4::504"),
    ];

    let specs = vec![make_spec(
        "OW Catch Spec",
        vec![make_section("Performance", vec![parent])],
    )];

    let run = make_run_result(vec![
        make_result("ow4::parent", TestStatus::Failed),
        make_result("ow4::cached", TestStatus::Passed),
        make_result("ow4::504", TestStatus::Skipped),
    ]);

    let text = render_terminal(&run, &specs, &no_color_options());

    let ow1 = text.lines().find(|l| l.contains("return a cached response")).unwrap();
    let ow2 = text.lines().find(|l| l.contains("return 504")).unwrap();

    assert!(
        ow1.contains("\u{2713}"),
        "first OTHERWISE (caught failure) must show checkmark, got: {ow1:?}"
    );
    assert!(
        ow2.contains("~"),
        "second OTHERWISE (not reached) must show ~, got: {ow2:?}"
    );
}


/// SHOULD visually distinguish the active fallback from lower ones
#[test]
fn test_reporter__otherwise_chain__should_distinguish_active_from_unreached() {
    let mut parent = make_clause(Keyword::Must, "respond within 200ms", "ow5::parent");
    parent.otherwise = vec![
        make_clause(Keyword::Otherwise, "return a cached response", "ow5::cached"),
        make_clause(Keyword::Otherwise, "return 504", "ow5::504"),
    ];

    let specs = vec![make_spec(
        "OW Distinguish Spec",
        vec![make_section("Performance", vec![parent])],
    )];

    let run = make_run_result(vec![
        make_result("ow5::parent", TestStatus::Failed),
        make_result("ow5::cached", TestStatus::Passed),
        make_result("ow5::504", TestStatus::Skipped),
    ]);

    let text = render_terminal(&run, &specs, &color_options());

    let active_line = text.lines().find(|l| l.contains("return a cached response")).unwrap();
    let not_reached_line = text.lines().find(|l| l.contains("return 504")).unwrap();

    // Not-reached line should contain "not reached" annotation.
    assert!(
        not_reached_line.contains("not reached"),
        "not-reached fallback must carry 'not reached' annotation, got: {not_reached_line:?}"
    );

    // Active line should NOT say "not reached".
    assert!(
        !active_line.contains("not reached"),
        "active fallback must NOT carry 'not reached', got: {active_line:?}"
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// TEMPORAL RESULT DISPLAY TESTS
// ═══════════════════════════════════════════════════════════════════════════

