//! Generated tests for the `temporal` subsection of the `reporter` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

#![allow(dead_code, clippy::all)]
#![allow(non_snake_case)]

//! Generated tests for ought-report, rewritten to use the real API.
//!
//! Categories covered:
//!   - terminal_output (10 tests)
//!   - failure_details (4 tests)
//!   - given_block_display (4 tests)
//!   - json_output (3 tests -- diagnosis/grade test removed since those features are stubbed)
//!   - junit_xml_output (5 tests)
//!   - otherwise_chain_display (5 tests)
//!   - temporal_result_display (3 tests)
//!
//! Removed categories (stubbed/non-reporter functionality):
//!   - failure_narratives_llm_powered (7 tests) -- diagnosis is stubbed
//!   - test_quality_grading (6 tests) -- grading is stubbed
//!   - progress_during_generation (3 tests) -- not part of reporter

use std::path::PathBuf;
use std::time::Duration;

use ought_report::types::{ColorChoice, ReportOptions};
use ought_run::{RunResult, TestDetails, TestResult, TestStatus};
use ought_spec::{Clause, ClauseId, Keyword, Metadata, Section, SourceLocation, Spec, Temporal};

// ── Test data builders ──────────────────────────────────────────────────────

fn make_clause(keyword: Keyword, text: &str, id: &str) -> Clause {
    Clause {
        id: ClauseId(id.to_string()),
        keyword,
        severity: keyword.severity(),
        text: text.to_string(),
        condition: None,
        otherwise: vec![],
        temporal: None,
        hints: vec![],
        source_location: SourceLocation {
            file: PathBuf::from("test.ought.md"),
            line: 1,
        },
        content_hash: "test".to_string(),
        pending: false,
    }
}

fn make_section(title: &str, clauses: Vec<Clause>) -> Section {
    Section {
        title: title.to_string(),
        depth: 1,
        prose: String::new(),
        clauses,
        subsections: vec![],
    }
}

fn make_spec(name: &str, sections: Vec<Section>) -> Spec {
    Spec {
        name: name.to_string(),
        metadata: Metadata::default(),
        sections,
        source_path: PathBuf::from("test.ought.md"),
    }
}

fn make_result(clause_id: &str, status: TestStatus) -> TestResult {
    TestResult {
        clause_id: ClauseId(clause_id.to_string()),
        status,
        message: None,
        duration: Duration::from_millis(10),
        details: TestDetails::default(),
    }
}

fn make_result_with_message(clause_id: &str, status: TestStatus, msg: &str) -> TestResult {
    TestResult {
        clause_id: ClauseId(clause_id.to_string()),
        status,
        message: Some(msg.to_string()),
        duration: Duration::from_millis(10),
        details: TestDetails::default(),
    }
}

fn make_result_with_failure_detail(clause_id: &str, status: TestStatus, failure_msg: &str) -> TestResult {
    TestResult {
        clause_id: ClauseId(clause_id.to_string()),
        status,
        message: None,
        duration: Duration::from_millis(10),
        details: TestDetails {
            failure_message: Some(failure_msg.to_string()),
            ..Default::default()
        },
    }
}

fn make_run_result(results: Vec<TestResult>) -> RunResult {
    let total: Duration = results.iter().map(|r| r.duration).sum();
    RunResult {
        results,
        total_duration: total,
    }
}

fn no_color_options() -> ReportOptions {
    ReportOptions {
        color: ColorChoice::Never,
        ..Default::default()
    }
}

fn color_options() -> ReportOptions {
    ReportOptions {
        color: ColorChoice::Always,
        ..Default::default()
    }
}

fn render_terminal(run: &RunResult, specs: &[Spec], opts: &ReportOptions) -> String {
    let mut buf: Vec<u8> = Vec::new();
    ought_report::terminal::report_to_writer(&mut buf, run, specs, opts)
        .expect("report_to_writer should succeed");
    String::from_utf8(buf).expect("output should be valid UTF-8")
}

// ── ANSI escape code constants ──────────────────────────────────────────────

const RED: &str = "\x1b[31m";
const YELLOW: &str = "\x1b[33m";
const DIM: &str = "\x1b[2m";
const BOLD: &str = "\x1b[1m";
#[allow(dead_code)]
const RESET: &str = "\x1b[0m";

// ═══════════════════════════════════════════════════════════════════════════
// TERMINAL OUTPUT TESTS
// ═══════════════════════════════════════════════════════════════════════════

/// MUST show each clause with its keyword, text, and pass/fail status

/// MUST display MUST ALWAYS results with the number of iterations/inputs tested
#[test]
fn test_reporter__temporal__must_display_must_always_with_iterations() {
    let mut clause = make_clause(Keyword::MustAlways, "return valid JSON", "inv::must_always_json");
    clause.temporal = Some(Temporal::Invariant);

    let specs = vec![make_spec(
        "Invariant Spec",
        vec![make_section("Invariants", vec![clause])],
    )];

    let run = make_run_result(vec![TestResult {
        clause_id: ClauseId("inv::must_always_json".to_string()),
        status: TestStatus::Passed,
        message: None,
        duration: Duration::from_millis(50),
        details: TestDetails {
            iterations: Some(1000),
            ..Default::default()
        },
    }]);

    let text = render_terminal(&run, &specs, &no_color_options());

    let clause_line = text
        .lines()
        .find(|l| l.contains("return valid JSON"))
        .expect("MUST ALWAYS clause line must appear");

    assert!(
        clause_line.contains("1000"),
        "MUST ALWAYS line must include iteration count; got: {clause_line:?}"
    );
    assert!(
        clause_line.contains("tested") || clause_line.contains("inputs"),
        "MUST ALWAYS line must describe what was tested; got: {clause_line:?}"
    );
}


/// MUST display MUST BY results with the measured duration alongside the deadline
#[test]
fn test_reporter__temporal__must_display_must_by_with_duration_and_deadline() {
    let deadline = Duration::from_millis(200);
    let measured = Duration::from_millis(47);

    let mut clause = make_clause(Keyword::MustBy, "return a response", "perf::must_by_response");
    clause.temporal = Some(Temporal::Deadline(deadline));

    let specs = vec![make_spec(
        "Perf Spec",
        vec![make_section("Performance", vec![clause])],
    )];

    let run = make_run_result(vec![TestResult {
        clause_id: ClauseId("perf::must_by_response".to_string()),
        status: TestStatus::Passed,
        message: None,
        duration: measured,
        details: TestDetails {
            measured_duration: Some(measured),
            ..Default::default()
        },
    }]);

    let text = render_terminal(&run, &specs, &no_color_options());

    let clause_line = text
        .lines()
        .find(|l| l.contains("return a response"))
        .expect("MUST BY clause line must appear");

    assert!(
        clause_line.contains("47ms"),
        "MUST BY line must show measured duration (47ms); got: {clause_line:?}"
    );
    assert!(
        clause_line.contains("200ms"),
        "MUST BY line must show deadline (200ms); got: {clause_line:?}"
    );
}


/// SHOULD show a timing ratio for MUST BY clauses: [47ms / 200ms]
#[test]
fn test_reporter__temporal__should_show_timing_ratio_for_must_by() {
    let passing_clause = {
        let mut c = make_clause(Keyword::MustBy, "return a response", "perf::pass");
        c.temporal = Some(Temporal::Deadline(Duration::from_millis(200)));
        c
    };
    let failing_clause = {
        let mut c = make_clause(Keyword::MustBy, "acknowledge the write", "perf::fail");
        c.temporal = Some(Temporal::Deadline(Duration::from_millis(100)));
        c
    };

    let specs = vec![make_spec(
        "Timing Spec",
        vec![make_section("Performance", vec![passing_clause, failing_clause])],
    )];

    let run = make_run_result(vec![
        TestResult {
            clause_id: ClauseId("perf::pass".to_string()),
            status: TestStatus::Passed,
            message: None,
            duration: Duration::from_millis(47),
            details: TestDetails {
                measured_duration: Some(Duration::from_millis(47)),
                ..Default::default()
            },
        },
        TestResult {
            clause_id: ClauseId("perf::fail".to_string()),
            status: TestStatus::Failed,
            message: None,
            duration: Duration::from_millis(230),
            details: TestDetails {
                measured_duration: Some(Duration::from_millis(230)),
                ..Default::default()
            },
        },
    ]);

    let text = render_terminal(&run, &specs, &no_color_options());

    // Passing clause: [47ms / 200ms]
    let passing_line = text
        .lines()
        .find(|l| l.contains("return a response"))
        .expect("passing MUST BY clause line must appear");
    assert!(
        passing_line.contains("47ms") && passing_line.contains("200ms"),
        "passing MUST BY must show both durations; got: {passing_line:?}"
    );
    assert!(
        passing_line.contains('/'),
        "ratio must include a '/' separator; got: {passing_line:?}"
    );

    // Failing clause: [230ms / 100ms]
    let failing_line = text
        .lines()
        .find(|l| l.contains("acknowledge the write"))
        .expect("failing MUST BY clause line must appear");
    assert!(
        failing_line.contains("230ms") && failing_line.contains("100ms"),
        "failing MUST BY must show both durations; got: {failing_line:?}"
    );
}

