//! Generated tests for the `terminal_output` subsection of the `reporter` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

#![allow(dead_code, clippy::all)]
#![allow(non_snake_case)]

//! Generated tests for ought-report, rewritten to use the real API.
//!
//! Categories covered:
//!   - terminal_output (10 tests)
//!   - failure_details (4 tests)
//!   - given_block_display (4 tests)
//!   - json_output (3 tests -- diagnosis/grade test removed since those features are stubbed)
//!   - junit_xml_output (5 tests)
//!   - otherwise_chain_display (5 tests)
//!   - temporal_result_display (3 tests)
//!
//! Removed categories (stubbed/non-reporter functionality):
//!   - failure_narratives_llm_powered (7 tests) -- diagnosis is stubbed
//!   - test_quality_grading (6 tests) -- grading is stubbed
//!   - progress_during_generation (3 tests) -- not part of reporter

use std::path::PathBuf;
use std::time::Duration;

use ought_report::types::{ColorChoice, ReportOptions};
use ought_run::{RunResult, TestDetails, TestResult, TestStatus};
use ought_spec::{Clause, ClauseId, Keyword, Metadata, Section, SourceLocation, Spec, Temporal};

// ── Test data builders ──────────────────────────────────────────────────────

fn make_clause(keyword: Keyword, text: &str, id: &str) -> Clause {
    Clause {
        id: ClauseId(id.to_string()),
        keyword,
        severity: keyword.severity(),
        text: text.to_string(),
        condition: None,
        otherwise: vec![],
        temporal: None,
        hints: vec![],
        source_location: SourceLocation {
            file: PathBuf::from("test.ought.md"),
            line: 1,
        },
        content_hash: "test".to_string(),
        pending: false,
    }
}

fn make_section(title: &str, clauses: Vec<Clause>) -> Section {
    Section {
        title: title.to_string(),
        depth: 1,
        prose: String::new(),
        clauses,
        subsections: vec![],
    }
}

fn make_spec(name: &str, sections: Vec<Section>) -> Spec {
    Spec {
        name: name.to_string(),
        metadata: Metadata::default(),
        sections,
        source_path: PathBuf::from("test.ought.md"),
    }
}

fn make_result(clause_id: &str, status: TestStatus) -> TestResult {
    TestResult {
        clause_id: ClauseId(clause_id.to_string()),
        status,
        message: None,
        duration: Duration::from_millis(10),
        details: TestDetails::default(),
    }
}

fn make_result_with_message(clause_id: &str, status: TestStatus, msg: &str) -> TestResult {
    TestResult {
        clause_id: ClauseId(clause_id.to_string()),
        status,
        message: Some(msg.to_string()),
        duration: Duration::from_millis(10),
        details: TestDetails::default(),
    }
}

fn make_result_with_failure_detail(clause_id: &str, status: TestStatus, failure_msg: &str) -> TestResult {
    TestResult {
        clause_id: ClauseId(clause_id.to_string()),
        status,
        message: None,
        duration: Duration::from_millis(10),
        details: TestDetails {
            failure_message: Some(failure_msg.to_string()),
            ..Default::default()
        },
    }
}

fn make_run_result(results: Vec<TestResult>) -> RunResult {
    let total: Duration = results.iter().map(|r| r.duration).sum();
    RunResult {
        results,
        total_duration: total,
    }
}

fn no_color_options() -> ReportOptions {
    ReportOptions {
        color: ColorChoice::Never,
        ..Default::default()
    }
}

fn color_options() -> ReportOptions {
    ReportOptions {
        color: ColorChoice::Always,
        ..Default::default()
    }
}

fn render_terminal(run: &RunResult, specs: &[Spec], opts: &ReportOptions) -> String {
    let mut buf: Vec<u8> = Vec::new();
    ought_report::terminal::report_to_writer(&mut buf, run, specs, opts)
        .expect("report_to_writer should succeed");
    String::from_utf8(buf).expect("output should be valid UTF-8")
}

// ── ANSI escape code constants ──────────────────────────────────────────────

const RED: &str = "\x1b[31m";
const YELLOW: &str = "\x1b[33m";
const DIM: &str = "\x1b[2m";
const BOLD: &str = "\x1b[1m";
#[allow(dead_code)]
const RESET: &str = "\x1b[0m";

// ═══════════════════════════════════════════════════════════════════════════
// TERMINAL OUTPUT TESTS
// ═══════════════════════════════════════════════════════════════════════════

/// MUST show each clause with its keyword, text, and pass/fail status

/// MUST show each clause with its keyword, text, and pass/fail status
#[test]
fn test_reporter__terminal_output__must_show_each_clause_with_keyword_text_and_status() {
    let specs = vec![make_spec(
        "Auth Spec",
        vec![make_section(
            "Auth",
            vec![
                make_clause(Keyword::Must, "return a token", "auth::must_return_token"),
                make_clause(Keyword::Should, "log the attempt", "auth::should_log"),
                make_clause(Keyword::May, "set a cookie", "auth::may_cookie"),
            ],
        )],
    )];

    let run = make_run_result(vec![
        make_result("auth::must_return_token", TestStatus::Passed),
        make_result("auth::should_log", TestStatus::Failed),
        make_result("auth::may_cookie", TestStatus::Skipped),
    ]);

    let text = render_terminal(&run, &specs, &no_color_options());

    // Each clause line must carry the keyword label and clause text.
    let must_line = text.lines().find(|l| l.contains("return a token")).expect("MUST clause line missing");
    let should_line = text.lines().find(|l| l.contains("log the attempt")).expect("SHOULD clause line missing");
    let may_line = text.lines().find(|l| l.contains("set a cookie")).expect("MAY clause line missing");

    assert!(must_line.contains("MUST"), "MUST keyword must appear on clause line");
    assert!(must_line.contains("\u{2713}"), "passed indicator must appear on MUST line");

    assert!(should_line.contains("SHOULD"), "SHOULD keyword must appear on clause line");
    assert!(should_line.contains("\u{2717}"), "failed indicator must appear on SHOULD line");

    assert!(may_line.contains("MAY"), "MAY keyword must appear on clause line");
    assert!(may_line.contains("~"), "skipped indicator must appear on MAY line");
}


/// MUST use status indicators: checkmark passed, X failed, ! errored, circle-slash confirmed absent (WONT), ~ skipped
#[test]
fn test_reporter__terminal_output__must_use_status_indicators() {
    let specs = vec![make_spec(
        "Status Spec",
        vec![make_section(
            "All statuses",
            vec![
                make_clause(Keyword::Must, "clause-passed", "s::passed"),
                make_clause(Keyword::Must, "clause-failed", "s::failed"),
                make_clause(Keyword::Must, "clause-errored", "s::errored"),
                make_clause(Keyword::Wont, "clause-absent", "s::absent"),
                make_clause(Keyword::Should, "clause-skipped", "s::skipped"),
            ],
        )],
    )];

    let run = make_run_result(vec![
        make_result("s::passed", TestStatus::Passed),
        make_result("s::failed", TestStatus::Failed),
        make_result("s::errored", TestStatus::Errored),
        make_result("s::absent", TestStatus::Passed), // WONT + Passed = confirmed absent
        make_result("s::skipped", TestStatus::Skipped),
    ]);

    let text = render_terminal(&run, &specs, &no_color_options());

    // Verify each indicator appears on the correct clause's line.
    for line in text.lines() {
        if line.contains("clause-passed") {
            assert!(line.contains("\u{2713}"), "passed clause line must show checkmark, got: {line:?}");
        }
        if line.contains("clause-failed") {
            assert!(line.contains("\u{2717}"), "failed clause line must show X, got: {line:?}");
        }
        if line.contains("clause-errored") {
            assert!(line.contains("!"), "errored clause line must show !, got: {line:?}");
        }
        if line.contains("clause-absent") {
            assert!(line.contains("\u{2298}"), "absent clause line must show circle-slash, got: {line:?}");
        }
        if line.contains("clause-skipped") {
            assert!(line.contains("~"), "skipped clause line must show ~, got: {line:?}");
        }
    }
}


/// MUST display results grouped by spec file, then by section, then by clause
#[test]
fn test_reporter__terminal_output__must_display_grouped_by_spec_section_clause() {
    let specs = vec![
        make_spec(
            "Auth Spec",
            vec![
                make_section("Login", vec![make_clause(Keyword::Must, "issue JWT", "auth::login::jwt")]),
                make_section("Logout", vec![make_clause(Keyword::Must, "invalidate token", "auth::logout::token")]),
            ],
        ),
        make_spec(
            "API Spec",
            vec![make_section("Endpoints", vec![make_clause(Keyword::Must, "return 200", "api::endpoints::200")])],
        ),
    ];

    let run = make_run_result(vec![
        make_result("auth::login::jwt", TestStatus::Passed),
        make_result("auth::logout::token", TestStatus::Passed),
        make_result("api::endpoints::200", TestStatus::Passed),
    ]);

    let text = render_terminal(&run, &specs, &no_color_options());

    // Spec ordering
    let pos_auth = text.find("Auth Spec").expect("Auth Spec not found");
    let pos_api = text.find("API Spec").expect("API Spec not found");
    assert!(pos_auth < pos_api, "Auth Spec should precede API Spec");

    // Section ordering within a single spec
    let pos_login = text.find("Login").expect("Login section not found");
    let pos_logout = text.find("Logout").expect("Logout section not found");
    assert!(pos_login < pos_logout, "Login section should appear before Logout section");

    // Section header must precede its own clauses
    let pos_login_header = text.find("Login").unwrap();
    let pos_jwt_clause = text.find("issue JWT").expect("JWT clause not found");
    assert!(pos_login_header < pos_jwt_clause, "section header must precede its clauses");
}


/// MUST print a summary line at the end with total passed, failed, errored
#[test]
fn test_reporter__terminal_output__must_print_summary_line() {
    let specs = vec![make_spec(
        "Summary Spec",
        vec![make_section(
            "S",
            vec![
                make_clause(Keyword::Must, "p1", "sum::p1"),
                make_clause(Keyword::Must, "p2", "sum::p2"),
                make_clause(Keyword::Must, "f1", "sum::f1"),
                make_clause(Keyword::Should, "e1", "sum::e1"),
            ],
        )],
    )];

    let run = make_run_result(vec![
        make_result("sum::p1", TestStatus::Passed),
        make_result("sum::p2", TestStatus::Passed),
        make_result("sum::f1", TestStatus::Failed),
        make_result("sum::e1", TestStatus::Errored),
    ]);

    let text = render_terminal(&run, &specs, &no_color_options());

    // Summary must contain correct aggregate counts.
    assert!(text.contains("2 passed"), "summary must state '2 passed', got:\n{text}");
    assert!(text.contains("1 failed"), "summary must state '1 failed', got:\n{text}");
    assert!(text.contains("1 errored"), "summary must state '1 errored', got:\n{text}");

    // Clause content must appear before the summary.
    let pos_clause = text.find("p1").expect("clause text not found");
    let pos_passed = text.rfind("2 passed").expect("summary not found");
    assert!(pos_clause < pos_passed, "clause content must appear before the summary line");
}


/// MUST show MUST coverage percentage in the summary
#[test]
fn test_reporter__terminal_output__must_show_must_coverage_percentage() {
    // 2 of 3 MUST clauses pass -> 67%
    let specs = vec![make_spec(
        "Coverage Spec",
        vec![make_section(
            "S",
            vec![
                make_clause(Keyword::Must, "m1", "cov::m1"),
                make_clause(Keyword::Must, "m2", "cov::m2"),
                make_clause(Keyword::Must, "m3", "cov::m3"),
                make_clause(Keyword::Should, "s1", "cov::s1"), // SHOULD must not affect MUST %
            ],
        )],
    )];

    let run = make_run_result(vec![
        make_result("cov::m1", TestStatus::Passed),
        make_result("cov::m2", TestStatus::Passed),
        make_result("cov::m3", TestStatus::Failed),
        make_result("cov::s1", TestStatus::Passed),
    ]);

    let text = render_terminal(&run, &specs, &no_color_options());
    // 2/3 = 66.666...% -> displayed as 67%
    assert!(
        text.contains("2/3") || text.contains("67%") || text.contains("67 %") || text.contains("66%"),
        "summary must show MUST coverage, got:\n{text}"
    );

    // The label must mention MUST
    assert!(
        text.to_uppercase().contains("MUST"),
        "summary must mention MUST in coverage label, got:\n{text}"
    );
}


/// MUST color-code by severity: MUST failures in red, SHOULD failures in yellow
#[test]
fn test_reporter__terminal_output__must_color_code_by_severity() {
    let specs = vec![make_spec(
        "Severity Spec",
        vec![make_section(
            "Severity",
            vec![
                make_clause(Keyword::Must, "must-fail", "sev::must"),
                make_clause(Keyword::Should, "should-fail", "sev::should"),
                make_clause(Keyword::May, "may-fail", "sev::may"),
            ],
        )],
    )];

    let run = make_run_result(vec![
        make_result("sev::must", TestStatus::Failed),
        make_result("sev::should", TestStatus::Failed),
        make_result("sev::may", TestStatus::Failed),
    ]);

    let text = render_terminal(&run, &specs, &color_options());

    let must_line = text.lines().find(|l| l.contains("must-fail")).expect("MUST failure line missing");
    let should_line = text.lines().find(|l| l.contains("should-fail")).expect("SHOULD failure line missing");
    let may_line = text.lines().find(|l| l.contains("may-fail")).expect("MAY failure line missing");

    assert!(
        must_line.contains(RED),
        "MUST failures must be colored red, got: {must_line:?}"
    );
    assert!(
        should_line.contains(YELLOW),
        "SHOULD failures must be colored yellow, got: {should_line:?}"
    );
    // MAY failures use yellow in the actual implementation
    assert!(
        may_line.contains(YELLOW),
        "MAY failures must be colored yellow, got: {may_line:?}"
    );
}


/// SHOULD dim passing clauses and highlight failures for visual scanning
#[test]
fn test_reporter__terminal_output__should_dim_passing_and_highlight_failures() {
    let specs = vec![make_spec(
        "Dim Spec",
        vec![make_section(
            "S",
            vec![
                make_clause(Keyword::Must, "passing clause", "dim::pass"),
                make_clause(Keyword::Must, "failing clause", "dim::fail"),
            ],
        )],
    )];

    let run = make_run_result(vec![
        make_result("dim::pass", TestStatus::Passed),
        make_result("dim::fail", TestStatus::Failed),
    ]);

    let text_color = render_terminal(&run, &specs, &color_options());
    let text_nocolor = render_terminal(&run, &specs, &no_color_options());

    // With color: passing clause line must carry the dim code.
    let passing_line = text_color.lines().find(|l| l.contains("passing clause")).expect("passing clause missing");
    assert!(
        passing_line.contains(DIM),
        "passing clause must be dimmed, got: {passing_line:?}"
    );

    // With color: failing MUST clause must be highlighted (red or bold).
    let failing_line = text_color.lines().find(|l| l.contains("failing clause")).expect("failing clause missing");
    assert!(
        failing_line.contains(RED) || failing_line.contains(BOLD),
        "failing clause must be highlighted (red or bold), got: {failing_line:?}"
    );

    // Without color: no ANSI escape codes should appear.
    assert!(
        !text_nocolor.contains("\x1b["),
        "color-disabled output must contain no ANSI escape sequences"
    );
}


/// WONT use animated spinners or progress bars in non-TTY mode (pipe-friendly)
#[test]
fn test_reporter__terminal_output__wont_use_spinners_in_non_tty_mode() {
    let specs = vec![make_spec(
        "Pipe Spec",
        vec![make_section(
            "S",
            vec![
                make_clause(Keyword::Must, "clause a", "pipe::a"),
                make_clause(Keyword::Must, "clause b", "pipe::b"),
            ],
        )],
    )];

    let run = make_run_result(vec![
        make_result("pipe::a", TestStatus::Passed),
        make_result("pipe::b", TestStatus::Failed),
    ]);

    let text = render_terminal(&run, &specs, &no_color_options());

    // Output must not be empty.
    assert!(!text.trim().is_empty(), "non-TTY output must not be empty");

    // Braille spinner characters must be absent.
    let braille_spinners = ['\u{280B}', '\u{2819}', '\u{2839}', '\u{2838}', '\u{283C}', '\u{2834}', '\u{2826}', '\u{2827}', '\u{2807}', '\u{280F}'];
    for ch in &braille_spinners {
        assert!(!text.contains(*ch), "non-TTY output must not contain braille spinner char '{ch}'");
    }

    // Block-fill progress-bar characters must be absent.
    let progress_bar_chars = ['\u{2588}', '\u{2591}', '\u{2593}', '\u{2592}'];
    for ch in &progress_bar_chars {
        assert!(!text.contains(*ch), "non-TTY output must not contain progress bar character '{ch}'");
    }

    // ANSI cursor-control escapes must be absent.
    assert!(!text.contains("\x1b[?25l"), "cursor-hide escape must not appear");
    assert!(!text.contains("\x1b[1A"), "cursor-up escape must not appear");
    assert!(!text.contains("\x1b[2K"), "erase-line escape must not appear");
}


/// Terminal report should not panic with empty specs
#[test]
fn test_reporter__terminal_output__no_panic_with_empty_specs() {
    let specs: Vec<Spec> = vec![];
    let run = RunResult {
        results: vec![],
        total_duration: Duration::from_millis(0),
    };
    // Should not panic.
    let text = render_terminal(&run, &specs, &no_color_options());
    assert!(!text.is_empty(), "output should contain at least a header");
}


/// Terminal report should not panic with no results for clauses
#[test]
fn test_reporter__terminal_output__no_panic_with_missing_results() {
    let specs = vec![make_spec(
        "Missing Spec",
        vec![make_section(
            "S",
            vec![make_clause(Keyword::Must, "no result for this", "missing::clause")],
        )],
    )];
    let run = RunResult {
        results: vec![],
        total_duration: Duration::from_millis(0),
    };
    // Should not panic even though clause has no matching test result.
    let text = render_terminal(&run, &specs, &no_color_options());
    assert!(text.contains("no result for this"), "clause text should still appear");
}

// ═══════════════════════════════════════════════════════════════════════════
// FAILURE DETAILS TESTS
// ═══════════════════════════════════════════════════════════════════════════

