//! Generated tests for the `conditional_blocks_given` subsection of the parser spec.
//!
//! Each test verifies a single clause from `ought/engine/parser.ought.md`.
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

use std::fs;
use std::path::{Path, PathBuf};
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use ought_spec::graph::SpecGraph;
use ought_spec::parser::{OughtMdParser, Parser};
use ought_spec::types::*;

// --- must_attach_the_given_condition_text_to_all_clauses_nested_within_test.rs ---
/// MUST attach the GIVEN condition text to all clauses nested within it
#[test]
fn test_parser__conditional_blocks_given__must_attach_the_given_condition_text_to_all_clauses_nested_within() {

    fn parse(md: &str) -> Spec {
        OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed")
    }

    let md = r#"# Svc

## Access

- **GIVEN** the request carries a valid token:
  - **MUST** allow the request through
  - **MUST NOT** log the token value
  - **SHOULD** refresh the token if near expiry
"#;
    let spec = parse(md);
    let clauses = &spec.sections[0].clauses;
    assert_eq!(clauses.len(), 3, "all three nested clauses should be emitted");
    for clause in clauses {
        assert_eq!(
            clause.condition.as_deref(),
            Some("the request carries a valid token:"),
            "every nested clause must carry the GIVEN condition text; clause '{}' did not",
            clause.text
        );
    }
}

// --- must_not_treat_given_itself_as_a_testable_clause_it_is_a_grouping_con_test.rs ---
/// MUST NOT treat GIVEN itself as a testable clause — it is a grouping construct with a precondition
#[test]
fn test_parser__conditional_blocks_given__must_not_treat_given_itself_as_a_testable_clause_it_is_a_grouping_con() {

    fn parse(md: &str) -> Spec {
        OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed")
    }

    let md = r#"# Svc

## Access

- **GIVEN** the user is authenticated:
  - **MUST** return their profile data
"#;
    let spec = parse(md);
    let clauses = &spec.sections[0].clauses;

    // GIVEN itself must not appear as a clause
    let given_clauses: Vec<_> = clauses.iter()
        .filter(|c| c.keyword == Keyword::Given)
        .collect();
    assert!(
        given_clauses.is_empty(),
        "GIVEN must not appear as a testable clause in the IR; found {} Given clause(s)",
        given_clauses.len()
    );

    // Only the nested MUST should be present
    assert_eq!(clauses.len(), 1);
    assert_eq!(clauses[0].keyword, Keyword::Must);
}

// --- must_parse_given_as_a_block_level_keyword_that_contains_nested_cl_test.rs ---
/// MUST parse `**GIVEN**` as a block-level keyword that contains nested clauses
#[test]
fn test_parser__conditional_blocks_given__must_parse_given_as_a_block_level_keyword_that_contains_nested_cl() {

    fn parse(md: &str) -> Spec {
        OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed")
    }

    let md = r#"# Svc

## Access

- **GIVEN** the user is authenticated:
  - **MUST** return their profile data
  - **SHOULD** include last-login timestamp
"#;
    let spec = parse(md);
    let clauses = &spec.sections[0].clauses;
    // GIVEN is a block-level grouping; its two children become the clauses
    assert_eq!(clauses.len(), 2);
    assert_eq!(clauses[0].keyword, Keyword::Must);
    assert!(clauses[0].text.contains("return their profile data"));
    assert_eq!(clauses[1].keyword, Keyword::Should);
    assert!(clauses[1].text.contains("include last-login timestamp"));
}

// --- must_require_nested_clauses_to_be_indented_under_the_given_bullet_test.rs ---
/// MUST require nested clauses to be indented under the GIVEN bullet (standard markdown nesting)
#[test]
fn test_parser__conditional_blocks_given__must_require_nested_clauses_to_be_indented_under_the_given_bullet() {

    fn parse(md: &str) -> Spec {
        OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed")
    }

    // The MUST is at the same indentation level as the GIVEN — not nested under it.
    // It should be treated as a top-level clause with no condition.
    let md = r#"# Svc

## Rules

- **GIVEN** user is admin:
- **MUST** do something important
"#;
    let spec = parse(md);
    let clauses = &spec.sections[0].clauses;
    // The MUST is a sibling of GIVEN, not a child — it gets no condition
    let must_clause = clauses.iter().find(|c| c.keyword == Keyword::Must)
        .expect("expected a MUST clause");
    assert!(
        must_clause.condition.is_none(),
        "un-indented MUST after GIVEN must not inherit the GIVEN condition"
    );
}

// --- must_support_given_blocks_containing_any_keyword_must_should_may_test.rs ---
/// MUST support GIVEN blocks containing any keyword (MUST, SHOULD, MAY, WONT, OTHERWISE, etc.)
#[test]
fn test_parser__conditional_blocks_given__must_support_given_blocks_containing_any_keyword_must_should_may() {

    fn parse(md: &str) -> Spec {
        OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed")
    }

    let md = r#"# Svc

## Behaviour

- **GIVEN** the feature flag is enabled:
  - **MUST** activate the new code path
  - **MUST NOT** fall back to the legacy path
  - **SHOULD** emit a telemetry event
  - **SHOULD NOT** cache the result
  - **MAY** log additional debug info
  - **WONT** support IE11 in this mode
"#;
    let spec = parse(md);
    let clauses = &spec.sections[0].clauses;
    assert_eq!(clauses.len(), 6);

    let keywords: Vec<Keyword> = clauses.iter().map(|c| c.keyword).collect();
    assert!(keywords.contains(&Keyword::Must),      "MUST inside GIVEN");
    assert!(keywords.contains(&Keyword::MustNot),   "MUST NOT inside GIVEN");
    assert!(keywords.contains(&Keyword::Should),    "SHOULD inside GIVEN");
    assert!(keywords.contains(&Keyword::ShouldNot), "SHOULD NOT inside GIVEN");
    assert!(keywords.contains(&Keyword::May),       "MAY inside GIVEN");
    assert!(keywords.contains(&Keyword::Wont),      "WONT inside GIVEN");

    // All inherit the condition
    for clause in clauses {
        assert_eq!(
            clause.condition.as_deref(),
            Some("the feature flag is enabled:"),
            "clause '{}' missing condition", clause.text
        );
    }
}

// --- must_support_multiple_given_blocks_within_a_section_test.rs ---
/// MUST support multiple GIVEN blocks within a section
#[test]
fn test_parser__conditional_blocks_given__must_support_multiple_given_blocks_within_a_section() {

    fn parse(md: &str) -> Spec {
        OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed")
    }

    let md = r#"# Svc

## Auth

- **GIVEN** the user is an admin:
  - **MUST** allow access to the admin panel
  - **MAY** impersonate other users
- **GIVEN** the user is a guest:
  - **MUST NOT** access private resources
  - **SHOULD** be shown a login prompt
"#;
    let spec = parse(md);
    let clauses = &spec.sections[0].clauses;
    assert_eq!(clauses.len(), 4, "two GIVEN blocks with two children each = four clauses");

    let admin_clauses: Vec<_> = clauses.iter()
        .filter(|c| c.condition.as_deref() == Some("the user is an admin:"))
        .collect();
    assert_eq!(admin_clauses.len(), 2);
    assert!(admin_clauses.iter().any(|c| c.keyword == Keyword::Must));
    assert!(admin_clauses.iter().any(|c| c.keyword == Keyword::May));

    let guest_clauses: Vec<_> = clauses.iter()
        .filter(|c| c.condition.as_deref() == Some("the user is a guest:"))
        .collect();
    assert_eq!(guest_clauses.len(), 2);
    assert!(guest_clauses.iter().any(|c| c.keyword == Keyword::MustNot));
    assert!(guest_clauses.iter().any(|c| c.keyword == Keyword::Should));
}

// --- should_support_nested_given_blocks_conditions_that_narrow_further_test.rs ---
/// SHOULD support nested GIVEN blocks (conditions that narrow further)
#[test]
fn test_parser__conditional_blocks_given__should_support_nested_given_blocks_conditions_that_narrow_further() {

    fn parse(md: &str) -> Spec {
        OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed")
    }

    let md = r#"# Svc

## Permissions

- **GIVEN** the user is an admin:
  - **GIVEN** the user account is active:
    - **MUST** allow full access
"#;
    let spec = parse(md);
    let clauses = &spec.sections[0].clauses;
    // The innermost MUST should be emitted as a clause
    assert_eq!(clauses.len(), 1);
    assert_eq!(clauses[0].keyword, Keyword::Must);
    assert!(clauses[0].text.contains("allow full access"));
    // The clause carries a condition derived from the inner (narrowing) GIVEN
    assert!(
        clauses[0].condition.is_some(),
        "clause nested inside two GIVENs must carry a condition"
    );
}

