//! Generated tests for the `contrary_to_duty_chains_otherwise` subsection of the parser spec.
//!
//! Each test verifies a single clause from `ought/engine/parser.ought.md`.
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

use std::fs;
use std::path::{Path, PathBuf};
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use ought_spec::graph::SpecGraph;
use ought_spec::parser::{OughtMdParser, Parser};
use ought_spec::types::*;

// --- must_link_each_otherwise_clause_to_its_parent_obligation_in_the_c_test.rs ---
/// MUST link each OTHERWISE clause to its parent obligation in the clause IR
#[test]
fn test_parser__contrary_to_duty_chains_otherwise__must_link_each_otherwise_clause_to_its_parent_obligation_in_the_c() {

    let md = r#"# Svc

## Api

- **MUST** validate the request payload
  - **OTHERWISE** reject with 400 Bad Request

- **MUST** authenticate the caller
  - **OTHERWISE** reject with 401 Unauthorized
"#;
    let spec = OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed");
    let clauses = &spec.sections[0].clauses;
    assert_eq!(clauses.len(), 2);

    // Each OTHERWISE is reachable only through its parent's .otherwise field
    assert_eq!(clauses[0].keyword, Keyword::Must);
    assert_eq!(clauses[0].otherwise.len(), 1);
    assert!(clauses[0].otherwise[0].text.contains("400"));

    assert_eq!(clauses[1].keyword, Keyword::Must);
    assert_eq!(clauses[1].otherwise.len(), 1);
    assert!(clauses[1].otherwise[0].text.contains("401"));

    // No OTHERWISE appears as a standalone top-level clause
    assert!(
        clauses.iter().all(|c| c.keyword != Keyword::Otherwise),
        "OTHERWISE clauses must not appear as top-level section clauses"
    );
}

// --- must_not_allow_otherwise_at_the_top_level_it_must_have_a_parent_oblig_test.rs ---
/// MUST NOT allow OTHERWISE at the top level (it must have a parent obligation)
#[test]
fn test_parser__contrary_to_duty_chains_otherwise__must_not_allow_otherwise_at_the_top_level_it_must_have_a_parent_oblig() {

    let md = r#"# Svc

## Section

- **OTHERWISE** this has no parent obligation
"#;
    let result = OughtMdParser.parse_string(md, Path::new("test.ought.md"));
    assert!(
        result.is_err(),
        "OTHERWISE at the top level without a parent obligation must be a parse error"
    );
}

// --- must_not_allow_otherwise_under_may_wont_or_given_only_under_obligatio_test.rs ---
/// MUST NOT allow OTHERWISE under MAY, WONT, or GIVEN (only under obligations that can be violated)
#[test]
fn test_parser__contrary_to_duty_chains_otherwise__must_not_allow_otherwise_under_may_wont_or_given_only_under_obligatio() {

    // OTHERWISE under MAY is invalid — MAY cannot be violated
    let md_may = r#"# Svc

## Section

- **MAY** use optional feature
  - **OTHERWISE** do nothing
"#;
    assert!(
        OughtMdParser.parse_string(md_may, Path::new("test.ought.md")).is_err(),
        "OTHERWISE under MAY must be a parse error"
    );

    // OTHERWISE under WONT is invalid — WONT is a negative confirmation, not a violable obligation
    let md_wont = r#"# Svc

## Section

- **WONT** implement feature X
  - **OTHERWISE** implement feature Y instead
"#;
    assert!(
        OughtMdParser.parse_string(md_wont, Path::new("test.ought.md")).is_err(),
        "OTHERWISE under WONT must be a parse error"
    );

    // OTHERWISE under GIVEN is invalid — GIVEN is a grouping construct, not a violable obligation
    let md_given = r#"# Svc

## Section

- **GIVEN** some condition:
  - **OTHERWISE** fallback without an obligation
"#;
    assert!(
        OughtMdParser.parse_string(md_given, Path::new("test.ought.md")).is_err(),
        "OTHERWISE under GIVEN must be a parse error"
    );
}

// --- must_parse_otherwise_as_a_clause_nested_under_a_parent_obligation_test.rs ---
/// MUST parse `**OTHERWISE**` as a clause nested under a parent obligation
#[test]
fn test_parser__contrary_to_duty_chains_otherwise__must_parse_otherwise_as_a_clause_nested_under_a_parent_obligation() {

    let md = r#"# Svc

## Resilience

- **MUST** respond within 200ms
  - **OTHERWISE** return a cached response
"#;
    let spec = OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed");
    let clauses = &spec.sections[0].clauses;

    // The parent MUST is the only top-level clause; OTHERWISE is not promoted to the top level
    assert_eq!(clauses.len(), 1, "only the parent obligation should appear as a top-level clause");
    assert_eq!(clauses[0].keyword, Keyword::Must);

    let otherwise = &clauses[0].otherwise;
    assert_eq!(otherwise.len(), 1);
    assert_eq!(otherwise[0].keyword, Keyword::Otherwise);
    assert!(otherwise[0].text.contains("cached response"));
}

// --- must_preserve_the_ordering_of_otherwise_clauses_they_form_a_degra_test.rs ---
/// MUST preserve the ordering of OTHERWISE clauses (they form a degradation chain)
#[test]
fn test_parser__contrary_to_duty_chains_otherwise__must_preserve_the_ordering_of_otherwise_clauses_they_form_a_degra() {

    let md = r#"# Svc

## Resilience

- **MUST** respond with fresh data
  - **OTHERWISE** return stale cache
  - **OTHERWISE** return degraded placeholder
  - **OTHERWISE** return HTTP 503
"#;
    let spec = OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed");
    let otherwise = &spec.sections[0].clauses[0].otherwise;

    assert_eq!(otherwise.len(), 3);
    // Degradation chain order must match declaration order
    assert!(otherwise[0].text.contains("stale cache"),        "first fallback must be stale cache");
    assert!(otherwise[1].text.contains("degraded placeholder"), "second fallback must be degraded placeholder");
    assert!(otherwise[2].text.contains("503"),                "third fallback must be 503");
}

// --- must_support_multiple_otherwise_clauses_under_a_single_parent_ord_test.rs ---
/// MUST support multiple OTHERWISE clauses under a single parent (ordered fallback chain)
#[test]
fn test_parser__contrary_to_duty_chains_otherwise__must_support_multiple_otherwise_clauses_under_a_single_parent_ord() {

    let md = r#"# Svc

## Payments

- **MUST** charge the primary card
  - **OTHERWISE** charge the backup card
  - **OTHERWISE** add to pending queue
  - **OTHERWISE** reject with insufficient funds error
"#;
    let spec = OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed");
    let clauses = &spec.sections[0].clauses;

    assert_eq!(clauses.len(), 1, "only one top-level clause should exist");

    let otherwise = &clauses[0].otherwise;
    assert_eq!(otherwise.len(), 3, "all three fallbacks must be collected under the single parent");
    assert!(otherwise.iter().all(|c| c.keyword == Keyword::Otherwise));

    assert!(otherwise[0].text.contains("backup card"));
    assert!(otherwise[1].text.contains("pending queue"));
    assert!(otherwise[2].text.contains("insufficient funds"));
}

// --- must_support_otherwise_under_any_obligation_keyword_must_should_m_test.rs ---
/// MUST support OTHERWISE under any obligation keyword (MUST, SHOULD, MUST ALWAYS, MUST BY)
#[test]
fn test_parser__contrary_to_duty_chains_otherwise__must_support_otherwise_under_any_obligation_keyword_must_should_m() {

    let md = r#"# Svc

## Obligations

- **MUST** respond within 200ms
  - **OTHERWISE** return HTTP 503

- **SHOULD** include debug headers
  - **OTHERWISE** omit debug headers silently

- **MUST ALWAYS** maintain a live connection
  - **OTHERWISE** reconnect with exponential backoff

- **MUST BY 5s** complete the handshake
  - **OTHERWISE** abort and log timeout
"#;
    let spec = OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed");
    let clauses = &spec.sections[0].clauses;
    assert_eq!(clauses.len(), 4);

    assert_eq!(clauses[0].keyword, Keyword::Must);
    assert_eq!(clauses[0].otherwise.len(), 1, "MUST must support OTHERWISE");

    assert_eq!(clauses[1].keyword, Keyword::Should);
    assert_eq!(clauses[1].otherwise.len(), 1, "SHOULD must support OTHERWISE");

    assert_eq!(clauses[2].keyword, Keyword::MustAlways);
    assert_eq!(clauses[2].otherwise.len(), 1, "MUST ALWAYS must support OTHERWISE");

    assert_eq!(clauses[3].keyword, Keyword::MustBy);
    assert_eq!(clauses[3].otherwise.len(), 1, "MUST BY must support OTHERWISE");
}

// --- should_inherit_the_parent_s_severity_unless_the_otherwise_clause_sp_test.rs ---
/// SHOULD inherit the parent's severity unless the OTHERWISE clause specifies its own keyword
#[test]
fn test_parser__contrary_to_duty_chains_otherwise__should_inherit_the_parent_s_severity_unless_the_otherwise_clause_sp() {

    let md = r#"# Svc

## Graceful

- **MUST** return primary data
  - **OTHERWISE** return cached copy

- **SHOULD** include metadata
  - **OTHERWISE** omit metadata field
"#;
    let spec = OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed");
    let clauses = &spec.sections[0].clauses;
    assert_eq!(clauses.len(), 2);

    // OTHERWISE under MUST inherits Required severity
    assert_eq!(clauses[0].severity, Severity::Required);
    assert_eq!(
        clauses[0].otherwise[0].severity,
        Severity::Required,
        "OTHERWISE under MUST must inherit Required severity"
    );

    // OTHERWISE under SHOULD inherits Recommended severity
    assert_eq!(clauses[1].severity, Severity::Recommended);
    assert_eq!(
        clauses[1].otherwise[0].severity,
        Severity::Recommended,
        "OTHERWISE under SHOULD must inherit Recommended severity"
    );
}

