//! Generated tests for the `cross_file_references` subsection of the parser spec.
//!
//! Each test verifies a single clause from `ought/engine/parser.ought.md`.
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

use std::fs;
use std::path::{Path, PathBuf};
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use ought_spec::graph::SpecGraph;
use ought_spec::parser::{OughtMdParser, Parser};
use ought_spec::types::*;

// --- must_build_a_dependency_graph_from_cross_file_references_test.rs ---
/// MUST build a dependency graph from cross-file references
#[test]
fn test_parser__cross_file_references__must_build_a_dependency_graph_from_cross_file_references() {

    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let tmp = std::env::temp_dir().join(format!("ought_xref_graph_{nanos}"));
    std::fs::create_dir_all(&tmp).unwrap();

    // spec_b is the leaf — no requires of its own
    std::fs::write(
        tmp.join("spec_b.ought.md"),
        "# SpecB\n\n## Rules\n\n- **MUST** provide base data\n",
    )
    .unwrap();

    // spec_a depends on spec_b via a requires: link
    std::fs::write(
        tmp.join("spec_a.ought.md"),
        "# SpecA\n\nrequires: [SpecB](spec_b.ought.md)\n\n## Rules\n\n- **MUST** use SpecB data\n",
    )
    .unwrap();

    let graph =
        SpecGraph::from_roots(&[tmp.clone()]).expect("graph must build successfully with no cycles");

    assert_eq!(
        graph.specs().len(),
        2,
        "graph must contain all discovered spec files"
    );

    let order = graph.topological_order();
    assert_eq!(
        order.len(),
        2,
        "topological order must include every spec in the graph"
    );

    let pos_a = order
        .iter()
        .position(|s| s.name == "SpecA")
        .expect("SpecA must appear in topological order");
    let pos_b = order
        .iter()
        .position(|s| s.name == "SpecB")
        .expect("SpecB must appear in topological order");

    assert!(
        pos_b < pos_a,
        "dependency SpecB must appear before dependent SpecA in topological order \
         (got pos_b={pos_b}, pos_a={pos_a})"
    );

    let _ = std::fs::remove_dir_all(&tmp);
}

// --- must_detect_circular_dependencies_and_report_them_as_errors_test.rs ---
/// MUST detect circular dependencies and report them as errors
#[test]
fn test_parser__cross_file_references__must_detect_circular_dependencies_and_report_them_as_errors() {

    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let tmp = std::env::temp_dir().join(format!("ought_xref_cycle_{nanos}"));
    std::fs::create_dir_all(&tmp).unwrap();

    // a.ought.md requires b, and b.ought.md requires a — a direct mutual cycle
    std::fs::write(
        tmp.join("a.ought.md"),
        "# SpecA\n\nrequires: [SpecB](b.ought.md)\n\n## Rules\n\n- **MUST** do something\n",
    )
    .unwrap();
    std::fs::write(
        tmp.join("b.ought.md"),
        "# SpecB\n\nrequires: [SpecA](a.ought.md)\n\n## Rules\n\n- **MUST** do something\n",
    )
    .unwrap();

    let result = SpecGraph::from_roots(&[tmp.clone()]);

    assert!(
        result.is_err(),
        "a circular dependency must be reported as an error rather than silently accepted"
    );

    let errors = result.unwrap_err();
    let has_cycle_error = errors
        .iter()
        .any(|e| e.message.contains("circular dependency"));
    assert!(
        has_cycle_error,
        "error message must identify the circular dependency; got: {:?}",
        errors.iter().map(|e| &e.message).collect::<Vec<_>>()
    );

    let _ = std::fs::remove_dir_all(&tmp);
}

// --- must_parse_anchor_links_e_g_pricing_ought_md_discount_rules_as_re_test.rs ---
/// MUST parse anchor links (e.g. `pricing.ought.md#discount-rules`) as references to specific sections
#[test]
fn test_parser__cross_file_references__must_parse_anchor_links_e_g_pricing_ought_md_discount_rules_as_re() {
    let md = r#"# Checkout

requires: [Pricing](pricing.ought.md#discount-rules), [Auth](auth.ought.md#session-tokens)

## Payment

- **MUST** apply discount rules from the pricing spec
"#;
    let spec = OughtMdParser.parse_string(md, Path::new("checkout.ought.md"))
        .expect("parse failed");

    assert_eq!(
        spec.metadata.requires.len(),
        2,
        "anchor links must be parsed as cross-references"
    );

    let pricing = &spec.metadata.requires[0];
    assert_eq!(
        pricing.label, "Pricing",
        "link label must be captured from an anchor link"
    );
    assert_eq!(
        pricing.path.to_str().unwrap(),
        "pricing.ought.md",
        "file path must be extracted without the fragment"
    );
    assert_eq!(
        pricing.anchor.as_deref(),
        Some("discount-rules"),
        "URL fragment must be stored as the anchor field"
    );

    let auth = &spec.metadata.requires[1];
    assert_eq!(
        auth.path.to_str().unwrap(),
        "auth.ought.md",
        "second anchor link file path must be extracted correctly"
    );
    assert_eq!(
        auth.anchor.as_deref(),
        Some("session-tokens"),
        "second anchor must be extracted from the URL fragment"
    );
}

// --- must_parse_inline_markdown_links_to_other_ought_md_files_as_cross_test.rs ---
/// MUST parse inline markdown links to other .ought.md files as cross-references
#[test]
fn test_parser__cross_file_references__must_parse_inline_markdown_links_to_other_ought_md_files_as_cross() {
    let md = r#"# Checkout

requires: [Pricing](pricing.ought.md), [Users](users.ought.md)

## Payment

- **MUST** apply pricing rules
"#;
    let spec = OughtMdParser.parse_string(md, Path::new("checkout.ought.md"))
        .expect("parse failed");

    assert_eq!(
        spec.metadata.requires.len(),
        2,
        "each markdown link in requires: must become a separate cross-reference"
    );

    let pricing = &spec.metadata.requires[0];
    assert_eq!(
        pricing.label, "Pricing",
        "markdown link label must be captured as the SpecRef label"
    );
    assert_eq!(
        pricing.path.to_str().unwrap(),
        "pricing.ought.md",
        "markdown link URL must become the SpecRef path"
    );
    assert!(
        pricing.anchor.is_none(),
        "link without a URL fragment must have no anchor"
    );

    let users = &spec.metadata.requires[1];
    assert_eq!(
        users.label, "Users",
        "second link label must be captured"
    );
    assert_eq!(
        users.path.to_str().unwrap(),
        "users.ought.md",
        "second link URL must become the SpecRef path"
    );
    assert!(users.anchor.is_none());
}

// --- must_parse_requires_metadata_as_a_list_of_relative_paths_to_other_test.rs ---
/// MUST parse `requires:` metadata as a list of relative paths to other .ought.md files
#[test]
fn test_parser__cross_file_references__must_parse_requires_metadata_as_a_list_of_relative_paths_to_other() {
    let md = r#"# Billing

requires: pricing.ought.md
requires: users.ought.md

## Invoices

- **MUST** calculate totals correctly
"#;
    let spec = OughtMdParser.parse_string(md, Path::new("billing.ought.md"))
        .expect("parse failed");

    assert_eq!(
        spec.metadata.requires.len(),
        2,
        "requires: metadata must list all referenced spec files"
    );

    let first = &spec.metadata.requires[0];
    assert_eq!(
        first.path.to_str().unwrap(),
        "pricing.ought.md",
        "first requires: entry must carry the correct relative path"
    );
    assert!(
        first.anchor.is_none(),
        "plain path without a fragment must have no anchor"
    );

    let second = &spec.metadata.requires[1];
    assert_eq!(
        second.path.to_str().unwrap(),
        "users.ought.md",
        "second requires: entry must carry the correct relative path"
    );
    assert!(
        second.anchor.is_none(),
        "plain path without a fragment must have no anchor"
    );
}

// --- should_validate_that_all_cross_references_resolve_to_existing_files_test.rs ---
/// SHOULD validate that all cross-references resolve to existing files and sections
#[test]
fn test_parser__cross_file_references__should_validate_that_all_cross_references_resolve_to_existing_files() {

    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let tmp = std::env::temp_dir().join(format!("ought_xref_missing_{nanos}"));
    std::fs::create_dir_all(&tmp).unwrap();

    // spec_a references a file that is never written to disk
    std::fs::write(
        tmp.join("spec_a.ought.md"),
        "# SpecA\n\nrequires: [Missing](nonexistent.ought.md)\n\n## Rules\n\n- **MUST** reference real specs\n",
    )
    .unwrap();

    let result = SpecGraph::from_roots(&[tmp.clone()]);

    assert!(
        result.is_err(),
        "a requires: reference to a non-existent file must be reported as a validation error"
    );

    let errors = result.unwrap_err();
    let has_unresolved_error = errors.iter().any(|e| {
        e.message.contains("nonexistent.ought.md")
            || e.message.contains("unresolved")
            || e.message.contains("not found")
    });
    assert!(
        has_unresolved_error,
        "error must identify the unresolved cross-reference; got: {:?}",
        errors.iter().map(|e| &e.message).collect::<Vec<_>>()
    );

    let _ = std::fs::remove_dir_all(&tmp);
}

