//! Generated tests for the `error_handling` subsection of the parser spec.
//!
//! Each test verifies a single clause from `ought/engine/parser.ought.md`.
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

use std::fs;
use std::path::{Path, PathBuf};
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use ought_spec::graph::SpecGraph;
use ought_spec::parser::{OughtMdParser, Parser};
use ought_spec::types::*;

// --- must_continue_parsing_after_non_fatal_errors_collect_all_errors_d_test.rs ---
/// MUST continue parsing after non-fatal errors (collect all errors, don't stop at the first)
#[test]
fn test_parser__error_handling__must_continue_parsing_after_non_fatal_errors_collect_all_errors_d() {
    // Several keyword typos are interspersed with valid clauses. The parser must
    // not abort at the first unrecognized item — every valid clause that appears
    // later in the document must still be returned.
    let md = "\
# Svc

## Rules

- **MUTS** first typo — not a recognised keyword
- **MUST** first valid clause after typo
- **SHOLD** second typo
- **SHOULD** second valid clause after typo
- **MUST NOT** third valid clause at end of section
";
    let result = OughtMdParser.parse_string(md, Path::new("test.ought.md"));
    assert!(
        result.is_ok(),
        "unrecognised keyword typos must not cause a hard parse failure"
    );
    let spec = result.unwrap();
    let clauses = &spec.sections[0].clauses;

    // If the parser had stopped at the first bad item, only 0 or 1 clause would be
    // present. All three must be here to demonstrate full-document traversal.
    assert_eq!(
        clauses.len(),
        3,
        "parser must collect all valid clauses across the entire document, \
         not stop at the first unrecognised item"
    );
    assert_eq!(
        clauses[0].keyword,
        Keyword::Must,
        "valid MUST after first typo must be parsed"
    );
    assert_eq!(
        clauses[1].keyword,
        Keyword::Should,
        "valid SHOULD after second typo must be parsed"
    );
    assert_eq!(
        clauses[2].keyword,
        Keyword::MustNot,
        "valid MUST NOT at end of section must be parsed"
    );

    // Errors are returned as Vec<ParseError> — the whole collection, not just the first.
    // Verify the Vec type is used (not a single-error short-circuit) for file errors too.
    let file_result = OughtMdParser.parse_file(Path::new("/no/such/file.ought.md"));
    let errors = file_result.unwrap_err();
    // The Vec itself is the contract; callers can iterate all diagnostics.
    assert!(
        !errors.is_empty(),
        "errors must be returned in a Vec so callers see all diagnostics"
    );
}

// --- must_not_crash_on_malformed_markdown_degrade_gracefully_test.rs ---
/// MUST NOT crash on malformed markdown — degrade gracefully
#[test]
fn test_parser__error_handling__must_not_crash_on_malformed_markdown_degrade_gracefully() {
    // Empty document — must return a default Spec, not panic or error.
    let result = OughtMdParser.parse_string("", Path::new("empty.ought.md"));
    assert!(result.is_ok(), "empty input must parse without error");
    let spec = result.unwrap();
    assert_eq!(spec.name, "Untitled", "empty doc must default to 'Untitled'");
    assert!(spec.sections.is_empty(), "empty doc must have no sections");

    // Whitespace-only input.
    let result = OughtMdParser.parse_string("   \n\n   \n", Path::new("ws.ought.md"));
    assert!(result.is_ok(), "whitespace-only input must not fail");

    // H1-only, no sections.
    let result = OughtMdParser.parse_string("# Just a Title\n", Path::new("title_only.ought.md"));
    assert!(result.is_ok(), "H1-only doc must not fail");
    assert_eq!(result.unwrap().name, "Just a Title");

    // Missing H1 — valid clauses inside a section must still be parsed.
    let result = OughtMdParser.parse_string(
        "## Section\n\n- **MUST** do the thing\n",
        Path::new("no_h1.ought.md"),
    );
    assert!(result.is_ok(), "missing H1 must not crash the parser");
    let spec = result.unwrap();
    assert!(!spec.sections.is_empty(), "section must be parsed even without H1");
    assert_eq!(
        spec.sections[0].clauses.len(),
        1,
        "clause must be parsed when H1 is absent"
    );

    // Unclosed bold delimiter — CommonMark treats it as literal text.
    // The valid clause after the broken item must still be collected.
    let result = OughtMdParser.parse_string(
        "# Svc\n\n## S\n\n- **MUST unclosed bold marker\n- **MUST** valid after unclosed\n",
        Path::new("unclosed_bold.ought.md"),
    );
    // Must not panic; valid clause after the bad item must survive.
    if let Ok(spec) = result {
        assert!(
            !spec.sections[0].clauses.is_empty(),
            "valid clause after unclosed bold must be parsed"
        );
    }

    // Unclosed fenced code block.
    let _ = OughtMdParser.parse_string(
        "# Svc\n\n## S\n\n- **MUST** clause\n\n```\nno closing fence\n",
        Path::new("unclosed_fence.ought.md"),
    );

    // Markdown escape sequences and unusual characters inside clause text.
    let _ = OughtMdParser.parse_string(
        "# Svc\n\n## S\n\n- **MUST** handle \\* \\` \\[ edge chars\n",
        Path::new("escapes.ought.md"),
    );

    // Deeply nested lists beyond normal spec usage.
    let deep = format!(
        "# Svc\n\n## S\n\n- **MUST** top\n{}- nested\n{}- deeper\n{}- deepest\n",
        "  ".repeat(1),
        "  ".repeat(2),
        "  ".repeat(3),
    );
    let _ = OughtMdParser.parse_string(&deep, Path::new("deep_nesting.ought.md"));

    // Section heading with no body.
    let result = OughtMdParser.parse_string("# Svc\n\n## Empty Section\n\n## Next\n\n- **MUST** clause\n", Path::new("empty_sec.ought.md"));
    assert!(result.is_ok(), "empty section followed by valid section must not fail");
    let spec = result.unwrap();
    assert_eq!(
        spec.sections.iter().map(|s| s.clauses.len()).sum::<usize>(),
        1,
        "clause in section after an empty section must still be parsed"
    );
}

// --- must_report_parse_errors_with_the_file_path_line_number_and_a_cle_test.rs ---
/// MUST report parse errors with the file path, line number, and a clear message
#[test]
fn test_parser__error_handling__must_report_parse_errors_with_the_file_path_line_number_and_a_cle() {
    // Directly construct a ParseError and verify all three required fields are present
    // and surfaced by the Display implementation.
    let path = PathBuf::from("spec/auth.ought.md");
    let err = ParseError {
        file: path.clone(),
        line: 23,
        message: "unexpected token after MUST".to_string(),
    };

    assert_eq!(err.file, path, "error must carry the source file path");
    assert_eq!(err.line, 23, "error must carry the 1-based line number");
    assert!(!err.message.is_empty(), "error must include a non-empty human-readable message");

    // Display must render all three components so callers can show "file:line: msg"
    let display = format!("{}", err);
    assert!(
        display.contains("spec/auth.ought.md"),
        "display must include the file path; got: {display}"
    );
    assert!(
        display.contains("23"),
        "display must include the line number; got: {display}"
    );
    assert!(
        display.contains("unexpected token"),
        "display must include the message text; got: {display}"
    );

    // parse_file errors must embed the path that was attempted so the caller can
    // report "failed to read foo.ought.md" without extra bookkeeping.
    let missing = Path::new("/nonexistent/spec.ought.md");
    let result = OughtMdParser.parse_file(missing);
    assert!(result.is_err(), "parse_file must return Err for a missing file");
    let errors = result.unwrap_err();
    assert!(!errors.is_empty(), "errors Vec must be non-empty");
    assert_eq!(
        errors[0].file, missing,
        "parse_file error must record the path that was attempted"
    );
    assert!(
        !errors[0].message.is_empty(),
        "parse_file error must include a clear message describing the failure"
    );
}

// --- should_warn_on_likely_typos_e_g_muts_close_to_a_known_keyword_test.rs ---
/// SHOULD warn on likely typos (e.g. `**MUTS**` close to a known keyword)
#[test]
fn test_parser__error_handling__should_warn_on_likely_typos_e_g_muts_close_to_a_known_keyword() {
    // **MUTS** is an edit-distance-1 typo for **MUST**; **SHOLD** for **SHOULD**.
    // The parser must not silently accept them as valid keywords, and SHOULD
    // surface a diagnostic pointing to the likely correction.
    let md = "\
# Svc

## Rules

- **MUTS** typo for MUST — must not become a clause
- **MUST** the real keyword
- **SHOLD** typo for SHOULD — must not become a clause
- **SHOUD** another SHOULD variant — must not become a clause
";
    let spec = OughtMdParser.parse_string(md, Path::new("typos.ought.md"))
        .expect("keyword typos must not crash the parser");

    let clauses = &spec.sections[0].clauses;

    // Typo keywords must NOT be silently accepted and turned into clauses.
    assert!(
        !clauses.iter().any(|c| c.text.contains("typo for MUST")),
        "**MUTS** must not produce a clause — it is not a recognised keyword"
    );
    assert!(
        !clauses.iter().any(|c| c.text.contains("typo for SHOULD")),
        "**SHOLD** must not produce a clause — it is not a recognised keyword"
    );
    assert!(
        !clauses.iter().any(|c| c.text.contains("another SHOULD variant")),
        "**SHOUD** must not produce a clause — it is not a recognised keyword"
    );

    // The one genuinely valid keyword must still be recognised.
    assert_eq!(
        clauses.len(),
        1,
        "only the single valid **MUST** item must become a clause; typos become prose"
    );
    assert_eq!(
        clauses[0].keyword,
        Keyword::Must,
        "valid **MUST** must be recognised even when surrounded by typo items"
    );

    // TODO: when a warning/lint system is added, assert diagnostics such as:
    //   ParseWarning { file: "typos.ought.md", line: 5,
    //       message: "unknown keyword **MUTS** — did you mean **MUST**?" }
    //   ParseWarning { file: "typos.ought.md", line: 7,
    //       message: "unknown keyword **SHOLD** — did you mean **SHOULD**?" }
    // These could be surfaced via a `warnings: Vec<ParseWarning>` field on a
    // `ParseResult` wrapper or alongside `ParseError` in a `ParseDiagnostic` enum.
}

