//! Generated tests for the `keywords` subsection of the parser spec.
//!
//! Each test verifies a single clause from `ought/engine/parser.ought.md`.
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

use std::fs;
use std::path::{Path, PathBuf};
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use ought_spec::graph::SpecGraph;
use ought_spec::parser::{OughtMdParser, Parser};
use ought_spec::types::*;

// --- must_assign_severity_levels_must_must_not_must_always_must_by_req_test.rs ---
/// MUST assign severity levels: MUST/MUST NOT/MUST ALWAYS/MUST BY = required,
/// SHOULD/SHOULD NOT = recommended, MAY = optional, WONT = negative-confirmation
#[test]
fn test_parser__keywords__must_assign_severity_levels_must_must_not_must_always_must_by_req() {

    let md = r#"# Svc

## All Keywords

- **MUST** do something required
- **MUST NOT** skip something required
- **MUST ALWAYS** hold an invariant
- **MUST BY 1s** finish within deadline
- **SHOULD** follow recommendation
- **SHOULD NOT** violate recommendation
- **MAY** use optional feature
- **WONT** implement out-of-scope thing
"#;
    let spec = OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed");
    let clauses = &spec.sections[0].clauses;
    assert_eq!(clauses.len(), 8);

    // Required group
    assert_eq!(clauses[0].severity, Severity::Required,   "MUST → Required");
    assert_eq!(clauses[1].severity, Severity::Required,   "MUST NOT → Required");
    assert_eq!(clauses[2].severity, Severity::Required,   "MUST ALWAYS → Required");
    assert_eq!(clauses[3].severity, Severity::Required,   "MUST BY → Required");

    // Recommended group
    assert_eq!(clauses[4].severity, Severity::Recommended, "SHOULD → Recommended");
    assert_eq!(clauses[5].severity, Severity::Recommended, "SHOULD NOT → Recommended");

    // Optional
    assert_eq!(clauses[6].severity, Severity::Optional,   "MAY → Optional");

    // Negative confirmation
    assert_eq!(clauses[7].severity, Severity::NegativeConfirmation, "WONT → NegativeConfirmation");
}

// --- must_not_treat_bare_non_bold_keyword_occurrences_as_clauses_e_g_you_m_test.rs ---
/// MUST NOT treat bare (non-bold) keyword occurrences as clauses (e.g. "you must restart" in prose)
#[test]
fn test_parser__keywords__must_not_treat_bare_non_bold_keyword_occurrences_as_clauses_e_g_you_m() {

    let md = r#"# Svc

## Overview

This service must handle all requests. Operators should monitor memory usage.
You must not store credentials in logs. The system may cache responses.
Deployments wont need downtime. Given the above, otherwise consider alternatives.

- A plain list item that says you must restart after upgrade
- Another item: should not be mistaken for a clause
"#;
    let spec = OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed");
    assert!(
        spec.sections[0].clauses.is_empty(),
        "bare keywords in paragraphs and unbolded list items must not produce any clauses"
    );

    // Confirm that a bold keyword in the same section does produce a clause,
    // proving the parser is active and the above result is not a parser failure.
    let md_mixed = r#"# Svc

## Mixed

This service must handle all requests as described above.

- **MUST** actually validate the token
"#;
    let spec2 = OughtMdParser.parse_string(md_mixed, Path::new("test.ought.md")).expect("parse failed");
    let clauses = &spec2.sections[0].clauses;
    assert_eq!(clauses.len(), 1, "only the bold keyword item must become a clause");
    assert_eq!(clauses[0].keyword, Keyword::Must);
    assert!(clauses[0].text.contains("validate the token"));
}

// --- must_parse_keywords_case_insensitively_but_require_them_to_appear_test.rs ---
/// MUST parse keywords case-insensitively but require them to appear in bold (`**MUST**`, `**GIVEN**`, etc.)
#[test]
fn test_parser__keywords__must_parse_keywords_case_insensitively_but_require_them_to_appear() {

    // All casing variants in bold — all must be recognised
    let md_bold = r#"# Svc

## Rules

- **must** do something lowercase
- **Must** do something title-case
- **MUST** do something uppercase
- **must not** reject lowercase compound
- **Should** recommend title-case
- **may** allow lowercase optional
- **wont** refuse lowercase
"#;
    let spec = OughtMdParser.parse_string(md_bold, Path::new("test.ought.md")).expect("parse failed");
    let clauses = &spec.sections[0].clauses;
    assert_eq!(clauses.len(), 7, "all bold keyword variants must be parsed regardless of case");
    assert_eq!(clauses[0].keyword, Keyword::Must);
    assert_eq!(clauses[1].keyword, Keyword::Must);
    assert_eq!(clauses[2].keyword, Keyword::Must);
    assert_eq!(clauses[3].keyword, Keyword::MustNot);
    assert_eq!(clauses[4].keyword, Keyword::Should);
    assert_eq!(clauses[5].keyword, Keyword::May);
    assert_eq!(clauses[6].keyword, Keyword::Wont);

    // Non-bold keywords — must produce zero clauses
    let md_bare = r#"# Svc

## Prose

You must restart the service after upgrading.
The system should validate inputs.
"#;
    let spec2 = OughtMdParser.parse_string(md_bare, Path::new("test.ought.md")).expect("parse failed");
    assert!(
        spec2.sections[0].clauses.is_empty(),
        "bare (non-bold) keywords in prose must not produce clauses"
    );
}

// --- must_recognize_rfc_2119_keywords_must_must_not_should_should_not_test.rs ---
/// MUST recognize RFC 2119 keywords: MUST, MUST NOT, SHOULD, SHOULD NOT, MAY
#[test]
fn test_parser__keywords__must_recognize_rfc_2119_keywords_must_must_not_should_should_not() {

    let md = r#"# Svc

## Rules

- **MUST** perform authentication
- **MUST NOT** expose internal errors
- **SHOULD** log failed attempts
- **SHOULD NOT** cache sensitive tokens
- **MAY** support remember-me sessions
"#;
    let spec = OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed");
    let clauses = &spec.sections[0].clauses;
    assert_eq!(clauses.len(), 5);
    assert_eq!(clauses[0].keyword, Keyword::Must);
    assert!(clauses[0].text.contains("authentication"));
    assert_eq!(clauses[1].keyword, Keyword::MustNot);
    assert!(clauses[1].text.contains("internal errors"));
    assert_eq!(clauses[2].keyword, Keyword::Should);
    assert!(clauses[2].text.contains("failed attempts"));
    assert_eq!(clauses[3].keyword, Keyword::ShouldNot);
    assert!(clauses[3].text.contains("sensitive tokens"));
    assert_eq!(clauses[4].keyword, Keyword::May);
    assert!(clauses[4].text.contains("remember-me"));
}

// --- must_recognize_temporal_compound_keywords_must_always_must_by_test.rs ---
/// MUST recognize temporal compound keywords: MUST ALWAYS, MUST BY
#[test]
fn test_parser__keywords__must_recognize_temporal_compound_keywords_must_always_must_by() {

    let md = r#"# Svc

## Temporal

- **MUST ALWAYS** keep connection pool below maximum capacity
- **MUST BY 500ms** return a search result
- **MUST BY 10s** complete the checkout flow
- **MUST BY 2m** finish a background import job
"#;
    let spec = OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed");
    let clauses = &spec.sections[0].clauses;
    assert_eq!(clauses.len(), 4);

    assert_eq!(clauses[0].keyword, Keyword::MustAlways);
    assert!(
        matches!(clauses[0].temporal, Some(Temporal::Invariant)),
        "MUST ALWAYS must carry Temporal::Invariant"
    );

    assert_eq!(clauses[1].keyword, Keyword::MustBy);
    assert!(
        matches!(clauses[1].temporal, Some(Temporal::Deadline(d)) if d == Duration::from_millis(500)),
        "MUST BY 500ms must produce a 500ms deadline"
    );

    assert_eq!(clauses[2].keyword, Keyword::MustBy);
    assert!(
        matches!(clauses[2].temporal, Some(Temporal::Deadline(d)) if d == Duration::from_secs(10)),
        "MUST BY 10s must produce a 10s deadline"
    );

    assert_eq!(clauses[3].keyword, Keyword::MustBy);
    assert!(
        matches!(clauses[3].temporal, Some(Temporal::Deadline(d)) if d == Duration::from_secs(120)),
        "MUST BY 2m must produce a 120s deadline"
    );
}

// --- must_recognize_the_given_keyword_as_a_conditional_block_opener_fr_test.rs ---
/// MUST recognize the GIVEN keyword as a conditional block opener (from deontic logic)
#[test]
fn test_parser__keywords__must_recognize_the_given_keyword_as_a_conditional_block_opener_fr() {

    let md = r#"# Svc

## Access

- **GIVEN** the user holds an admin role:
  - **MUST** allow deletion of any record
  - **MUST NOT** expose other tenants' data
"#;
    let spec = OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed");
    let clauses = &spec.sections[0].clauses;
    // GIVEN groups its children; they become top-level clauses with the condition set
    assert_eq!(clauses.len(), 2);
    assert_eq!(clauses[0].keyword, Keyword::Must);
    let condition = clauses[0].condition.as_deref().expect("condition must be present");
    assert!(condition.contains("admin role"));
    assert_eq!(clauses[1].keyword, Keyword::MustNot);
    assert_eq!(clauses[1].condition, clauses[0].condition,
        "all children of the same GIVEN block share the same condition");
}

// --- must_recognize_the_otherwise_keyword_as_a_contrary_to_duty_fallba_test.rs ---
/// MUST recognize the OTHERWISE keyword as a contrary-to-duty fallback (from deontic logic)
#[test]
fn test_parser__keywords__must_recognize_the_otherwise_keyword_as_a_contrary_to_duty_fallba() {

    let md = r#"# Svc

## Resilience

- **MUST** respond within 100ms
  - **OTHERWISE** return a stale cached response
  - **OTHERWISE** return HTTP 503 with Retry-After header
"#;
    let spec = OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed");
    let clauses = &spec.sections[0].clauses;
    assert_eq!(clauses.len(), 1);
    assert_eq!(clauses[0].keyword, Keyword::Must);
    let otherwise = &clauses[0].otherwise;
    assert_eq!(otherwise.len(), 2);
    assert_eq!(otherwise[0].keyword, Keyword::Otherwise);
    assert!(otherwise[0].text.contains("stale cached"));
    assert_eq!(otherwise[1].keyword, Keyword::Otherwise);
    assert!(otherwise[1].text.contains("503"));
}

// --- must_recognize_the_wont_keyword_as_an_ought_extension_not_in_rfc_test.rs ---
/// MUST recognize the WONT keyword as an ought extension (not in RFC 2119)
#[test]
fn test_parser__keywords__must_recognize_the_wont_keyword_as_an_ought_extension_not_in_rfc() {

    let md = r#"# Svc

## Scope

- **WONT** support OAuth 1.0
- **WONT** implement SOAP endpoints
"#;
    let spec = OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed");
    let clauses = &spec.sections[0].clauses;
    assert_eq!(clauses.len(), 2);
    assert_eq!(clauses[0].keyword, Keyword::Wont);
    assert!(clauses[0].text.contains("OAuth 1.0"));
    assert_eq!(clauses[1].keyword, Keyword::Wont);
    assert!(clauses[1].text.contains("SOAP"));
}

