//! Generated tests for the `spec_file_structure` subsection of the parser spec.
//!
//! Each test verifies a single clause from `ought/engine/parser.ought.md`.
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

use std::fs;
use std::path::{Path, PathBuf};
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use ought_spec::graph::SpecGraph;
use ought_spec::parser::{OughtMdParser, Parser};
use ought_spec::types::*;

// --- must_not_fail_on_standard_markdown_that_doesn_t_contain_ought_keyword_test.rs ---
/// MUST NOT fail on standard markdown that doesn't contain ought keywords (just produce zero clauses)
#[test]
fn test_parser__spec_file_structure__must_not_fail_on_standard_markdown_that_doesn_t_contain_ought_keyword() {
    let md = r#"# Plain Spec

## Overview

This is a standard markdown document with no ought keywords whatsoever.

It has paragraphs, *italic text*, and `code spans`.

- A plain list item
- Another plain list item

## Details

More prose here. No deontic keywords appear in bold in any list items.

```python
def example():
    return True
```
"#;
    let result = OughtMdParser.parse_string(md, Path::new("test.ought.md"));
    assert!(
        result.is_ok(),
        "Parser must not fail on keyword-free markdown: {:?}",
        result.err()
    );
    let spec = result.unwrap();
    assert_eq!(spec.name, "Plain Spec");
    assert!(
        !spec.sections.is_empty(),
        "sections must still be parsed from headings"
    );
    let total_clauses: usize = spec.sections.iter().map(|s| s.clauses.len()).sum();
    assert_eq!(
        total_clauses, 0,
        "keyword-free markdown must produce zero clauses"
    );
}

// --- must_parse_frontmatter_style_metadata_at_the_top_of_the_file_cont_test.rs ---
/// MUST parse frontmatter-style metadata at the top of the file: `context:`, `source:`, `schema:`, `requires:`
#[test]
fn test_parser__spec_file_structure__must_parse_frontmatter_style_metadata_at_the_top_of_the_file_cont() {
    let md = r#"# Payments

context: Handles payment processing and invoicing
source: src/payments/, src/billing/
schema: schema/payments.graphql, schema/billing.graphql
requires: [Auth](auth.ought.md), [Users](users.ought.md#accounts)

## Checkout

- **MUST** process payments
"#;
    let spec = OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed");

    assert_eq!(
        spec.metadata.context.as_deref(),
        Some("Handles payment processing and invoicing"),
        "context: field must be parsed into metadata.context"
    );
    assert_eq!(
        spec.metadata.sources,
        vec!["src/payments/", "src/billing/"],
        "source: field must be parsed as a comma-separated list"
    );
    assert_eq!(
        spec.metadata.schemas,
        vec!["schema/payments.graphql", "schema/billing.graphql"],
        "schema: field must be parsed as a comma-separated list"
    );
    assert_eq!(
        spec.metadata.requires.len(),
        2,
        "requires: field must list all spec dependencies"
    );
    assert_eq!(spec.metadata.requires[0].label, "Auth");
    assert_eq!(
        spec.metadata.requires[0].path.to_str().unwrap(),
        "auth.ought.md"
    );
    assert_eq!(
        spec.metadata.requires[0].anchor,
        None,
        "link without fragment must have no anchor"
    );
    assert_eq!(spec.metadata.requires[1].label, "Users");
    assert_eq!(
        spec.metadata.requires[1].path.to_str().unwrap(),
        "users.ought.md"
    );
    assert_eq!(
        spec.metadata.requires[1].anchor.as_deref(),
        Some("accounts"),
        "link fragment must be captured as anchor"
    );
}

// --- must_parse_standard_markdown_commonmark_as_the_base_format_test.rs ---
/// MUST parse standard Markdown (CommonMark) as the base format
#[test]
fn test_parser__spec_file_structure__must_parse_standard_markdown_commonmark_as_the_base_format() {
    // Exercises headings, paragraphs, emphasis, inline code, fenced code blocks,
    // blockquotes, plain lists, and inline links — core CommonMark elements.
    let md = r#"# My Spec

## Intro

A paragraph with *italic*, ***bold italic***, and `inline code` text.

> A blockquote providing background context.

See also [the reference docs](http://example.com) for more detail.

- A plain list item
- Another informational bullet

```json
{"example": true}
```

## Rules

- **MUST** handle all CommonMark elements in surrounding prose
"#;
    let result = OughtMdParser.parse_string(md, Path::new("commonmark_test.ought.md"));
    assert!(
        result.is_ok(),
        "Parser must not fail on standard CommonMark: {:?}",
        result.err()
    );
    let spec = result.unwrap();
    assert_eq!(spec.name, "My Spec");
    let rules = spec.sections.iter().find(|s| s.title == "Rules").unwrap();
    assert_eq!(rules.clauses.len(), 1);
    assert_eq!(rules.clauses[0].keyword, Keyword::Must);
}

// --- must_preserve_all_non_clause_markdown_as_documentation_context_fo_test.rs ---
/// MUST preserve all non-clause markdown as documentation (context for the LLM, readable for humans)
#[test]
fn test_parser__spec_file_structure__must_preserve_all_non_clause_markdown_as_documentation_context_fo() {
    let md = r#"# Svc

## Security

This section describes the security requirements for the service.
Access control is enforced at the API boundary.

- Background: authentication uses bearer tokens
- Note: tokens expire after 24 hours

- **MUST** reject unauthenticated requests
"#;
    let spec = OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed");
    let section = &spec.sections[0];

    // The MUST clause is parsed correctly
    assert_eq!(section.clauses.len(), 1);
    assert_eq!(section.clauses[0].keyword, Keyword::Must);

    // All surrounding non-clause markdown is preserved in section.prose
    assert!(
        !section.prose.is_empty(),
        "non-clause markdown must be preserved in section.prose"
    );
    assert!(
        section.prose.contains("security requirements") || section.prose.contains("API boundary"),
        "paragraph text must appear in section.prose"
    );
}

// --- must_recognize_files_with_the_ought_md_extension_test.rs ---
/// MUST recognize files with the `.ought.md` extension
#[test]
fn test_parser__spec_file_structure__must_recognize_files_with_the_ought_md_extension() {

    let content = "# Ext Test\n\n## Section\n\n- **MUST** work\n";
    let path = std::env::temp_dir().join("ought_recognize_ext_test.ought.md");
    fs::write(&path, content).expect("failed to write temp .ought.md file");

    let result = OughtMdParser.parse_file(&path);
    fs::remove_file(&path).ok();

    assert!(
        result.is_ok(),
        "Parser must recognize and parse .ought.md files: {:?}",
        result.err()
    );
    let spec = result.unwrap();
    assert_eq!(spec.name, "Ext Test");
    assert_eq!(spec.sections[0].clauses.len(), 1);
    // source_path must reflect the .ought.md filename
    assert!(
        spec.source_path
            .file_name()
            .and_then(|n| n.to_str())
            .map(|n| n.ends_with(".ought.md"))
            .unwrap_or(false),
        "source_path must preserve the .ought.md extension"
    );
}

// --- must_treat_bullet_points_keyword_as_individual_clauses_test.rs ---
/// MUST treat bullet points (`- **KEYWORD**`) as individual clauses
#[test]
fn test_parser__spec_file_structure__must_treat_bullet_points_keyword_as_individual_clauses() {
    let md = r#"# Svc

## API

- **MUST** return a response body
- **MUST NOT** leak internal error details
- **SHOULD** include a request-id header
"#;
    let spec = OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed");
    let clauses = &spec.sections[0].clauses;

    assert_eq!(clauses.len(), 3, "each bold-keyword bullet must become exactly one clause");

    assert_eq!(clauses[0].keyword, Keyword::Must);
    assert_eq!(clauses[0].severity, Severity::Required);
    assert!(clauses[0].text.contains("return a response body"));

    assert_eq!(clauses[1].keyword, Keyword::MustNot);
    assert_eq!(clauses[1].severity, Severity::Required);
    assert!(clauses[1].text.contains("leak internal error details"));

    assert_eq!(clauses[2].keyword, Keyword::Should);
    assert_eq!(clauses[2].severity, Severity::Recommended);
    assert!(clauses[2].text.contains("request-id header"));

    // Each clause must have a non-empty, unique stable ID
    assert!(!clauses[0].id.0.is_empty());
    assert_ne!(clauses[0].id.0, clauses[1].id.0);
    assert_ne!(clauses[1].id.0, clauses[2].id.0);
}

// --- must_treat_h1_as_the_spec_name_test.rs ---
/// MUST treat H1 (`#`) as the spec name
#[test]
fn test_parser__spec_file_structure__must_treat_h1_as_the_spec_name() {
    let md = "# Payment Gateway\n\n## Rules\n\n- **MUST** work\n";
    let spec = OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed");

    assert_eq!(
        spec.name, "Payment Gateway",
        "H1 heading text must become spec.name"
    );
    // The H1 text must not also appear as a section title
    assert!(
        spec.sections.iter().all(|s| s.title != "Payment Gateway"),
        "H1 must not be duplicated as a top-level section"
    );
}

// --- must_treat_h2_etc_as_nested_test_groups_sections_test.rs ---
/// MUST treat H2+ (`##`, `###`, etc.) as nested test groups/sections
#[test]
fn test_parser__spec_file_structure__must_treat_h2_etc_as_nested_test_groups_sections() {
    let md = r#"# Svc

## Auth

### Login

#### Credentials

- **MUST** validate credentials

### Logout

- **SHOULD** clear session

## Billing

- **MUST** charge the correct amount
"#;
    let spec = OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed");

    // H2 headings produce top-level sections
    assert_eq!(spec.sections.len(), 2);
    assert_eq!(spec.sections[0].title, "Auth");
    assert_eq!(spec.sections[0].depth, 2);
    assert_eq!(spec.sections[1].title, "Billing");
    assert_eq!(spec.sections[1].depth, 2);

    // H3 headings become subsections of their enclosing H2
    let auth = &spec.sections[0];
    assert_eq!(auth.subsections.len(), 2);
    assert_eq!(auth.subsections[0].title, "Login");
    assert_eq!(auth.subsections[0].depth, 3);
    assert_eq!(auth.subsections[1].title, "Logout");
    assert_eq!(auth.subsections[1].depth, 3);

    // H4 headings become subsections of their enclosing H3
    let login = &auth.subsections[0];
    assert_eq!(login.subsections.len(), 1);
    assert_eq!(login.subsections[0].title, "Credentials");
    assert_eq!(login.subsections[0].depth, 4);
    assert_eq!(login.subsections[0].clauses.len(), 1);
}

