//! Generated tests for the `temporal_obligations` subsection of the parser spec.
//!
//! Each test verifies a single clause from `ought/engine/parser.ought.md`.
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

use std::fs;
use std::path::{Path, PathBuf};
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use ought_spec::graph::SpecGraph;
use ought_spec::parser::{OughtMdParser, Parser};
use ought_spec::types::*;

// --- must_assign_the_invariant_temporal_qualifier_to_the_clause_test.rs ---
/// MUST assign the `invariant` temporal qualifier to the clause
///
/// Verifies that the `temporal` field of a `**MUST ALWAYS**` clause is
/// `Some(Temporal::Invariant)` and not `None` or a `Deadline` variant.
#[test]
fn test_parser__temporal_obligations__must_always_invariant_must_assign_the_invariant_temporal_qualifier_to_the_clause() {

    fn parse(md: &str) -> Spec {
        OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed")
    }

    let md = r#"# Svc

## Invariants

- **MUST ALWAYS** hold the invariant that no account balance drops below zero
"#;
    let spec = parse(md);
    let clause = &spec.sections[0].clauses[0];

    // Temporal must be present and be the Invariant variant
    assert!(clause.temporal.is_some(), "temporal should be Some, not None");
    assert!(
        matches!(clause.temporal, Some(Temporal::Invariant)),
        "temporal should be Invariant, got {:?}",
        clause.temporal
    );

    // Must NOT be a deadline — Invariant and Deadline are mutually exclusive
    assert!(
        !matches!(clause.temporal, Some(Temporal::Deadline(_))),
        "MUST ALWAYS must not produce a Deadline temporal qualifier"
    );
}

// --- must_parse_must_always_as_a_single_compound_keyword_test.rs ---
/// MUST parse `**MUST ALWAYS**` as a single compound keyword
///
/// Verifies that `**MUST ALWAYS**` is recognized as the single compound keyword
/// `Keyword::MustAlways`, not treated as bare `MUST` or split into two tokens.
#[test]
fn test_parser__temporal_obligations__must_always_invariant_must_parse_must_always_as_a_single_compound_keyword() {

    fn parse(md: &str) -> Spec {
        OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed")
    }

    let md = r#"# Svc

## Invariants

- **MUST ALWAYS** keep connection count below the pool maximum
"#;
    let spec = parse(md);
    let clauses = &spec.sections[0].clauses;

    // Exactly one clause — not split into two items
    assert_eq!(clauses.len(), 1);

    // Keyword must be the compound MustAlways variant, not plain Must
    assert_eq!(clauses[0].keyword, Keyword::MustAlways);
    assert_ne!(clauses[0].keyword, Keyword::Must);

    // The word "ALWAYS" must not bleed into the clause text body
    assert!(!clauses[0].text.to_uppercase().starts_with("ALWAYS"));
    assert!(clauses[0].text.contains("keep connection count below the pool maximum"));
}

// --- must_represent_invariants_distinctly_in_the_clause_ir_they_genera_test.rs ---
/// MUST represent invariants distinctly in the clause IR (they generate different test patterns)
///
/// Verifies that `**MUST ALWAYS**` clauses are structurally distinct from plain
/// `**MUST**` clauses in the IR: different `keyword`, different `temporal` field,
/// and different stable `id`, ensuring downstream generators can tell them apart.
#[test]
fn test_parser__temporal_obligations__must_always_invariant_must_represent_invariants_distinctly_in_the_clause_ir_they_genera() {

    fn parse(md: &str) -> Spec {
        OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed")
    }

    let md = r#"# Svc

## Rules

- **MUST** validate the request before processing
- **MUST ALWAYS** reject requests that exceed the rate limit
"#;
    let spec = parse(md);
    let clauses = &spec.sections[0].clauses;
    assert_eq!(clauses.len(), 2);

    let plain_must = &clauses[0];
    let invariant = &clauses[1];

    // Keywords are distinct variants
    assert_eq!(plain_must.keyword, Keyword::Must);
    assert_eq!(invariant.keyword, Keyword::MustAlways);
    assert_ne!(plain_must.keyword, invariant.keyword);

    // Temporal field distinguishes them: plain MUST has none, invariant has Some(Invariant)
    assert!(
        plain_must.temporal.is_none(),
        "plain MUST should have no temporal qualifier"
    );
    assert!(
        matches!(invariant.temporal, Some(Temporal::Invariant)),
        "MUST ALWAYS should carry Temporal::Invariant"
    );

    // Stable IDs are distinct (generators key off these to pick test strategy)
    assert_ne!(
        plain_must.id, invariant.id,
        "plain MUST and MUST ALWAYS clauses must have different IDs"
    );

    // Both share Required severity — the distinction is keyword+temporal, not severity
    assert_eq!(plain_must.severity, Severity::Required);
    assert_eq!(invariant.severity, Severity::Required);
}

// --- must_not_accept_must_by_without_a_duration_it_is_a_parse_error_test.rs ---
/// MUST NOT accept MUST BY without a duration (it is a parse error)
///
/// Verifies that a `**MUST BY**` with no following duration token is rejected
/// by the parser and surfaced as an error, not silently swallowed or turned into
/// a bare `MUST` clause.
#[test]
fn test_parser__temporal_obligations__must_by_deadline_must_not_accept_must_by_without_a_duration_it_is_a_parse_error() {

    // No duration: "MUST BY" ends the bold span immediately
    let md_no_duration = r#"# Svc

## Rules

- **MUST BY** respond to every request
"#;
    let result = OughtMdParser.parse_string(md_no_duration, Path::new("test.ought.md"));
    assert!(
        result.is_err(),
        "parsing MUST BY with no duration should return Err, got Ok"
    );

    // Also check a variant where the bold span closes before the duration
    let md_early_close = r#"# Svc

## Rules

- **MUST BY** 30s respond to every request
"#;
    let result2 = OughtMdParser.parse_string(md_early_close, Path::new("test.ought.md"));
    assert!(
        result2.is_err(),
        "MUST BY with duration outside the bold span should return Err, got Ok"
    );
}

// --- must_parse_duration_suffixes_ms_milliseconds_s_seconds_m_minutes_test.rs ---
/// MUST parse duration suffixes: `ms` (milliseconds), `s` (seconds), `m` (minutes)
///
/// Verifies that all three recognised unit suffixes — `ms`, `s`, and `m` — are
/// accepted and round-trip correctly through the IR as their respective `DurationUnit`
/// variants.
#[test]
fn test_parser__temporal_obligations__must_by_deadline_must_parse_duration_suffixes_ms_milliseconds_s_seconds_m_minutes() {

    fn parse(md: &str) -> Spec {
        OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed")
    }

    // --- milliseconds ---
    let md_ms = r#"# Svc

## Deadlines

- **MUST BY 200ms** return a cached response
"#;
    let spec_ms = parse(md_ms);
    let clause_ms = &spec_ms.sections[0].clauses[0];
    assert_eq!(clause_ms.keyword, Keyword::MustBy);
    let temporal_ms = clause_ms.temporal.as_ref().expect("temporal must be Some for MUST BY");
    assert!(
        matches!(temporal_ms, Temporal::Deadline(d) if *d == Duration::from_millis(200)),
        "expected Temporal::Deadline(200ms), got {:?}", temporal_ms
    );

    // --- seconds ---
    let md_s = r#"# Svc

## Deadlines

- **MUST BY 5s** complete the database write
"#;
    let spec_s = parse(md_s);
    let clause_s = &spec_s.sections[0].clauses[0];
    assert_eq!(clause_s.keyword, Keyword::MustBy);
    let temporal_s = clause_s.temporal.as_ref().expect("temporal must be Some for MUST BY");
    assert!(
        matches!(temporal_s, Temporal::Deadline(d) if *d == Duration::from_secs(5)),
        "expected Temporal::Deadline(5s), got {:?}", temporal_s
    );

    // --- minutes ---
    let md_m = r#"# Svc

## Deadlines

- **MUST BY 10m** finish the batch export job
"#;
    let spec_m = parse(md_m);
    let clause_m = &spec_m.sections[0].clauses[0];
    assert_eq!(clause_m.keyword, Keyword::MustBy);
    let temporal_m = clause_m.temporal.as_ref().expect("temporal must be Some for MUST BY");
    assert!(
        matches!(temporal_m, Temporal::Deadline(d) if *d == Duration::from_secs(10 * 60)),
        "expected Temporal::Deadline(10m), got {:?}", temporal_m
    );
}

// --- must_parse_must_by_duration_as_a_compound_keyword_with_a_duration_test.rs ---
/// MUST parse `**MUST BY <duration>**` as a compound keyword with a duration parameter
///
/// Verifies that `**MUST BY 30s**` is recognized as the compound keyword
/// `Keyword::MustBy`, not split into bare `MUST` or an unknown token.
#[test]
fn test_parser__temporal_obligations__must_by_deadline_must_parse_must_by_duration_as_a_compound_keyword_with_a_duration() {

    fn parse(md: &str) -> Spec {
        OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed")
    }

    let md = r#"# Svc

## Deadlines

- **MUST BY 30s** respond to every health-check request
"#;
    let spec = parse(md);
    let clauses = &spec.sections[0].clauses;

    // Exactly one clause — not split
    assert_eq!(clauses.len(), 1, "expected exactly one clause");

    // Keyword must be the compound MustBy variant, not plain Must
    assert_eq!(clauses[0].keyword, Keyword::MustBy);
    assert_ne!(clauses[0].keyword, Keyword::Must);

    // The duration token must not bleed into the clause text body
    assert!(!clauses[0].text.trim_start().to_uppercase().starts_with("BY "));
    assert!(clauses[0].text.contains("respond to every health-check request"));
}

// --- must_store_the_duration_value_and_unit_in_the_clause_ir_test.rs ---
/// MUST store the duration value and unit in the clause IR
///
/// Verifies that the numeric value and the unit of a `**MUST BY**` clause are
/// faithfully preserved in `clause.temporal` as `Temporal::Deadline` with the
/// correct `value` and `unit` fields, and that the clause is otherwise well-formed.
#[test]
fn test_parser__temporal_obligations__must_by_deadline_must_store_the_duration_value_and_unit_in_the_clause_ir() {

    fn parse(md: &str) -> Spec {
        OughtMdParser.parse_string(md, Path::new("test.ought.md")).expect("parse failed")
    }

    let md = r#"# Svc

## SLAs

- **MUST BY 250ms** acknowledge every incoming message
"#;
    let spec = parse(md);
    let clause = &spec.sections[0].clauses[0];

    // Keyword is the compound MustBy variant
    assert_eq!(clause.keyword, Keyword::MustBy);

    // Temporal must be present and carry a Deadline
    let temporal = clause.temporal.as_ref().expect("temporal should be Some for MUST BY clause");
    assert!(
        matches!(temporal, Temporal::Deadline(d) if *d == Duration::from_millis(250)),
        "expected Temporal::Deadline(250ms), got {:?}", temporal
    );

    // Must NOT be an Invariant
    assert!(
        !matches!(clause.temporal, Some(Temporal::Invariant)),
        "MUST BY must not produce an Invariant temporal qualifier"
    );

    // Severity is Required (same as plain MUST / MUST ALWAYS)
    assert_eq!(clause.severity, Severity::Required);

    // Clause text body contains the obligation, not the duration token
    assert!(clause.text.contains("acknowledge every incoming message"));
    assert!(!clause.text.contains("250ms"));
}
// Removed: should_warn_if_the_duration_seems_unreasonably_small_1ms_or_large_1_test
// This test referenced DiagnosticLevel, Diagnostic, and parse_string_with_diagnostics
// which do not exist in the current API. The parser does not implement warnings yet.

