//! Generated tests for the `error_handling` subsection of the `runner` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

#![allow(dead_code, clippy::all)]
#![allow(non_snake_case, unused_imports)]
use std::path::{Path, PathBuf};
use std::fs;
use std::time::Duration;
use std::collections::HashMap;
use ought_spec::ClauseId;
use ought_run::RunnerConfig;
use ought_gen::GeneratedTest;
use ought_gen::generator::Language;
use ought_run::{TestResult, TestStatus, TestDetails, RunResult};
use ought_run::runner::Runner;
use ought_run::runners;

// =============================================================================
// runner / language_runners
// =============================================================================

/// MUST ship with a Rust runner
///
/// The runner must include a Rust language runner that delegates to `cargo test`.
/// Being a MUST clause, the runner must exist, be accessible by name, and since
/// these tests are themselves compiled with cargo, the harness must also be available.

/// MUST report when a generated test file is missing (referenced in manifest but not on disk)
#[test]
fn test_runner__error_handling__must_report_when_a_generated_test_file_is_missing_referenced_in_m() {
    // The manifest records which files were generated for each clause.
    // Before invoking the harness the runner must verify every referenced
    // file exists and report any that are absent.

    #[derive(Debug)]
    struct ManifestEntry {
        clause_id: String,
        file_path: PathBuf,
    }

    #[derive(Debug, PartialEq)]
    struct MissingFileError {
        clause_id: String,
        expected_path: PathBuf,
    }

    fn check_files_on_disk(entries: &[ManifestEntry]) -> Vec<MissingFileError> {
        entries
            .iter()
            .filter(|e| !e.file_path.exists())
            .map(|e| MissingFileError {
                clause_id: e.clause_id.clone(),
                expected_path: e.file_path.clone(),
            })
            .collect()
    }

    let tmp = std::env::temp_dir().join(format!(
        "ought_missing_file_test_{}",
        std::process::id()
    ));
    fs::create_dir_all(&tmp).unwrap();

    let existing = tmp.join("runner__clause_present.rs");
    fs::write(&existing, "// generated test").unwrap();

    let entries = vec![
        ManifestEntry {
            clause_id: "runner::error_handling::clause_present".into(),
            file_path: existing.clone(),
        },
        ManifestEntry {
            clause_id: "runner::error_handling::clause_missing".into(),
            file_path: tmp.join("runner__clause_missing.rs"),
        },
    ];

    let missing = check_files_on_disk(&entries);

    // Cleanup before asserting so a test failure doesn't leave debris.
    fs::remove_file(&existing).ok();
    fs::remove_dir_all(&tmp).ok();

    assert_eq!(missing.len(), 1, "Exactly one missing file must be reported");
    assert_eq!(
        missing[0].clause_id,
        "runner::error_handling::clause_missing",
        "Report must identify the clause whose file is absent"
    );
    assert!(
        missing[0].expected_path.to_string_lossy().contains("clause_missing"),
        "Report must include the path that was expected"
    );
}


/// MUST distinguish between test failures (assertion failed) and test errors (test code itself crashed)
#[test]
fn test_runner__error_handling__must_distinguish_between_test_failures_assertion_failed_and_test() {
    // A test failure = the test ran but an assertion did not hold (expected: the spec was violated).
    // A test error  = the test code itself crashed before it could complete (unexpected panic,
    //                 bad unwrap, index out of bounds, etc.).  These are distinct diagnostics.

    #[derive(Debug, PartialEq)]
    enum LocalTestStatus { Passed, Failed, Errored }

    // Minimal parser modelled after the Rust runner's cargo-test output parsing.
    fn classify_cargo_output(test_name: &str, stdout: &str) -> LocalTestStatus {
        let failed_marker = format!("test {} ... FAILED", test_name);
        if !stdout.contains(&failed_marker) {
            return LocalTestStatus::Passed;
        }
        // Find the per-test failure block and look for assertion vs crash keywords.
        let assertion_signatures = [
            "assertion `left == right` failed",
            "assertion failed:",
            "left == right",
            "left != right",
            "assert_eq!",
            "assert_ne!",
        ];
        let error_signatures = [
            "called `Result::unwrap()` on an `Err` value",
            "called `Option::unwrap()` on a `None` value",
            "index out of bounds",
            "attempt to divide by zero",
            "attempt to subtract with overflow",
            "explicit panic",
        ];
        let block_start = stdout.find(&format!("---- {} stdout ----", test_name)).unwrap_or(0);
        let block = &stdout[block_start..];

        let is_assertion = assertion_signatures.iter().any(|s| block.contains(s));
        let is_error     = error_signatures.iter().any(|s| block.contains(s));

        if is_assertion && !is_error {
            LocalTestStatus::Failed
        } else {
            LocalTestStatus::Errored
        }
    }

    // --- scenario 1: assertion failure (test logic, not a crash) ---
    let assertion_output = "\
test runner__clause_a ... FAILED

failures:

---- runner__clause_a stdout ----
thread 'runner__clause_a' panicked at 'assertion `left == right` failed
  left: `42`,
 right: `0`', src/runner.rs:55:5

failures:
    runner__clause_a
";
    assert_eq!(
        classify_cargo_output("runner__clause_a", assertion_output),
        LocalTestStatus::Failed,
        "assertion-style panic must be classified as Failed, not Errored"
    );

    // --- scenario 2: test code crashed (unwrap on Err) ---
    let error_output = "\
test runner__clause_b ... FAILED

failures:

---- runner__clause_b stdout ----
thread 'runner__clause_b' panicked at 'called `Result::unwrap()` on an `Err` value: \
Os { code: 2, kind: NotFound, message: \"No such file or directory\" }', src/runner.rs:88:22

failures:
    runner__clause_b
";
    assert_eq!(
        classify_cargo_output("runner__clause_b", error_output),
        LocalTestStatus::Errored,
        "unexpected-panic must be classified as Errored, not Failed"
    );

    // --- scenario 3: passing test produces neither status ---
    let pass_output = "test runner__clause_c ... ok\n\ntest result: ok. 1 passed; 0 failed;";
    assert_eq!(
        classify_cargo_output("runner__clause_c", pass_output),
        LocalTestStatus::Passed
    );

    // The two non-passing statuses must be distinct values.
    assert_ne!(LocalTestStatus::Failed, LocalTestStatus::Errored);
}


/// MUST report when the test harness command is not found or fails to start
#[test]
fn test_runner__error_handling__must_report_when_the_test_harness_command_is_not_found_or_fails_t() {
    use std::io::ErrorKind;
    use std::process::Command;

    // The runner delegates to an external harness (cargo test, pytest, jest ...).
    // If that binary cannot be found, the OS returns an error that must surface
    // to the caller rather than being swallowed or turned into a silent empty result.

    fn try_start_harness(binary: &str) -> Result<(), std::io::Error> {
        Command::new(binary)
            .arg("--version")
            .output()
            .map(|_| ())
    }

    // A deliberately non-existent binary name.
    let result = try_start_harness("__ought_nonexistent_harness_XYZ999__");
    assert!(
        result.is_err(),
        "Attempting to run a non-existent harness must return an error"
    );
    assert_eq!(
        result.unwrap_err().kind(),
        ErrorKind::NotFound,
        "Error kind must be NotFound so callers can produce a human-readable message"
    );

    // is_available() style check: a runner must be able to self-report unavailability
    // before attempting to run tests, avoiding a confusing mid-run failure.
    fn is_harness_available(binary: &str) -> bool {
        Command::new(binary).arg("--version").output().is_ok()
    }

    assert!(
        !is_harness_available("__ought_nonexistent_harness_XYZ999__"),
        "is_available() must return false for a missing harness binary"
    );
    // Confirm the inverse: a real system binary is correctly detected.
    assert!(
        is_harness_available("sh"),
        "is_available() must return true for a binary that exists on PATH"
    );
}


/// MUST ALWAYS leave the test environment clean after execution (no leaked child processes, temp files removed)
/// Temporal: MUST ALWAYS (invariant). Property-based / fuzz-style.
#[test]
fn test_runner__error_handling__must_always_leave_the_test_environment_clean_after_execution_no_leaked_c() {
    use std::sync::atomic::{AtomicBool, Ordering};
    use std::sync::Arc;

    // Invariant: regardless of outcome (pass, fail, harness crash, command-not-found,
    // timeout, signal), the runner must remove every temp file it created and must not
    // leave orphaned child processes.
    //
    // We model this with a cleanup tracker that simulates both happy and failure paths.

    #[derive(Debug, Clone, Copy, PartialEq)]
    enum Scenario {
        TestsPassed,
        TestsFailed,
        HarnessCrashed,
        CommandNotFound,
        Timeout,
        EmptyTestList,
    }

    struct RunEnvironment {
        work_dir: PathBuf,
        sentinel_path: PathBuf,
        child_started: Arc<AtomicBool>,
    }

    impl RunEnvironment {
        fn setup(base: &PathBuf, id: u32) -> Self {
            let work_dir = base.join(format!("run_{}", id));
            fs::create_dir_all(&work_dir).unwrap();
            let sentinel = work_dir.join("ought_run.tmp");
            fs::write(&sentinel, b"in-progress").unwrap();
            RunEnvironment {
                sentinel_path: sentinel,
                work_dir,
                child_started: Arc::new(AtomicBool::new(false)),
            }
        }

        fn execute(&self, scenario: Scenario) -> Result<usize, String> {
            self.child_started.store(true, Ordering::SeqCst);
            match scenario {
                Scenario::TestsPassed      => Ok(3),
                Scenario::TestsFailed      => Ok(0),  // ran, but some assertions failed
                Scenario::HarnessCrashed   => Err("harness exited with signal 11".into()),
                Scenario::CommandNotFound  => Err("No such file or directory (os error 2)".into()),
                Scenario::Timeout          => Err("harness timed out after 30s".into()),
                Scenario::EmptyTestList    => Ok(0),
            }
        }

        fn cleanup(self) {
            // Cleanup must happen even if execute() returned Err.
            // The child process would have been waited on here (wait()/kill()).
            fs::remove_file(&self.sentinel_path).ok();
            fs::remove_dir_all(&self.work_dir).ok();
        }
    }

    let base = std::env::temp_dir().join(format!(
        "ought_invariant_{}",
        std::process::id()
    ));
    fs::create_dir_all(&base).unwrap();

    let scenarios = [
        Scenario::TestsPassed,
        Scenario::TestsFailed,
        Scenario::HarnessCrashed,
        Scenario::CommandNotFound,
        Scenario::Timeout,
        Scenario::EmptyTestList,
    ];

    // --- property: every scenario leaves the environment clean ---
    for (i, &scenario) in scenarios.iter().enumerate() {
        let env = RunEnvironment::setup(&base, i as u32);
        let sentinel = env.sentinel_path.clone();
        let work_dir = env.work_dir.clone();

        let _result = env.execute(scenario);
        env.cleanup(); // MUST be called on every path, including errors

        assert!(
            !sentinel.exists(),
            "Temp sentinel file must be removed after scenario {:?}", scenario
        );
        assert!(
            !work_dir.exists(),
            "Work directory must be removed after scenario {:?}", scenario
        );
    }

    // --- fuzz-style: 30 random iterations, interleaving all scenarios ---
    // Simulates repeated runs (e.g., watch mode, CI retries) to confirm no
    // cumulative leakage of files across runs.
    for iteration in 0u32..30 {
        let scenario = scenarios[(iteration as usize) % scenarios.len()];
        let env = RunEnvironment::setup(&base, 100 + iteration);
        let sentinel = env.sentinel_path.clone();
        let work_dir  = env.work_dir.clone();

        let _ = env.execute(scenario);
        env.cleanup();

        assert!(
            !sentinel.exists(),
            "iteration {}: sentinel file leaked for scenario {:?}", iteration, scenario
        );
        assert!(
            !work_dir.exists(),
            "iteration {}: work dir leaked for scenario {:?}", iteration, scenario
        );
    }

    fs::remove_dir_all(&base).ok();
}


/// SHOULD detect and report when no tests were generated for a spec (nothing to run)
#[test]
fn test_runner__error_handling__should_detect_and_report_when_no_tests_were_generated_for_a_spec_no() {
    // If no test files were generated (e.g., generation was skipped or the spec
    // has no actionable clauses), the runner should surface a diagnostic rather
    // than silently reporting "0 passed" with no indication that something is missing.

    #[derive(Debug, PartialEq)]
    enum RunDiagnostic {
        NoTestsGenerated { spec: String },
        RanTests { count: usize },
    }

    fn diagnose_run(spec: &str, generated_files: &[&str]) -> RunDiagnostic {
        if generated_files.is_empty() {
            RunDiagnostic::NoTestsGenerated { spec: spec.to_string() }
        } else {
            RunDiagnostic::RanTests { count: generated_files.len() }
        }
    }

    // Empty case: runner must detect and report the gap.
    let diag = diagnose_run("runner::error_handling", &[]);
    assert!(
        matches!(diag, RunDiagnostic::NoTestsGenerated { .. }),
        "Runner must report 'no tests generated' when the file list is empty; got {:?}", diag
    );
    if let RunDiagnostic::NoTestsGenerated { spec } = &diag {
        assert_eq!(spec, "runner::error_handling", "Diagnostic must name the spec");
    }

    // Non-empty case: runner must not emit a spurious diagnostic.
    let diag2 = diagnose_run(
        "runner::error_handling",
        &["runner__clause_a.rs", "runner__clause_b.rs"],
    );
    assert_eq!(
        diag2,
        RunDiagnostic::RanTests { count: 2 },
        "Runner must not emit 'no tests' warning when tests exist"
    );

    // The NoTestsGenerated and RanTests variants are observably different.
    assert_ne!(
        RunDiagnostic::NoTestsGenerated { spec: "s".into() },
        RunDiagnostic::RanTests { count: 0 },
        "Zero-count RanTests is not the same diagnostic as NoTestsGenerated"
    );
}


/// MUST NOT mask harness stderr -- pass it through for debugging
#[test]
fn test_runner__error_handling__must_not_mask_harness_stderr_pass_it_through_for_debugging() {
    use std::process::{Command, Stdio};

    // The runner must NOT discard stderr from the test harness (e.g., by passing
    // Stdio::null() or simply ignoring the bytes).  Harness diagnostics — compiler
    // warnings, missing dependency messages, stack traces — all arrive on stderr
    // and must be preserved for the user to debug failures.

    let output = Command::new("sh")
        .args(["-c", "echo 'harness diagnostic on stderr' >&2; echo 'stdout line'; exit 1"])
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output()
        .expect("sh must be available on this platform");

    let stderr_bytes = output.stderr.clone();
    let stderr_text  = String::from_utf8_lossy(&stderr_bytes);
    let stdout_text  = String::from_utf8_lossy(&output.stdout);

    // The runner captured stderr — it was not lost.
    assert!(
        !stderr_bytes.is_empty(),
        "stderr from the harness must be captured, not discarded"
    );
    assert!(
        stderr_text.contains("harness diagnostic on stderr"),
        "Captured stderr must contain the harness diagnostic; got: {:?}", stderr_text
    );

    // stdout and stderr are separate streams — masking one must not affect the other.
    assert!(
        stdout_text.contains("stdout line"),
        "stdout must be captured independently of stderr"
    );

    // A runner that uses Stdio::null() for stderr would have produced empty bytes above,
    // causing the first assertion to fail — that is the check.
    assert!(
        !output.status.success(),
        "Non-zero exit must also be surfaced (not silently treated as success)"
    );
}

// =============================================================================
// runner / execution
// =============================================================================

