//! Generated tests for the `execution` subsection of the `runner` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

#![allow(dead_code, clippy::all)]
#![allow(non_snake_case, unused_imports)]
use std::path::{Path, PathBuf};
use std::fs;
use std::time::Duration;
use std::collections::HashMap;
use ought_spec::ClauseId;
use ought_run::RunnerConfig;
use ought_gen::GeneratedTest;
use ought_gen::generator::Language;
use ought_run::{TestResult, TestStatus, TestDetails, RunResult};
use ought_run::runner::Runner;
use ought_run::runners;

// =============================================================================
// runner / language_runners
// =============================================================================

/// MUST ship with a Rust runner
///
/// The runner must include a Rust language runner that delegates to `cargo test`.
/// Being a MUST clause, the runner must exist, be accessible by name, and since
/// these tests are themselves compiled with cargo, the harness must also be available.

/// MUST support running tests for a single spec file (filtering generated tests by origin spec)
#[test]
fn test_runner__execution__must_support_running_tests_for_a_single_spec_file_filtering_gener() {
    use std::sync::{Arc, Mutex};

    // Tests generated from two distinct spec files.
    // Spec A: auth.ought.md -> clause IDs prefixed "auth::"
    // Spec B: runner.ought.md -> clause IDs prefixed "runner::"
    let all_tests = vec![
        GeneratedTest {
            clause_id: ClauseId("auth::login::must_return_jwt".to_string()),
            code: String::new(),
            language: Language::Rust,
            file_path: PathBuf::from("auth/login/must_return_jwt_test.rs"),
        },
        GeneratedTest {
            clause_id: ClauseId("auth::login::must_reject_expired_token".to_string()),
            code: String::new(),
            language: Language::Rust,
            file_path: PathBuf::from("auth/login/must_reject_expired_token_test.rs"),
        },
        GeneratedTest {
            clause_id: ClauseId("runner::execution::must_invoke_command".to_string()),
            code: String::new(),
            language: Language::Rust,
            file_path: PathBuf::from("runner/execution/must_invoke_command_test.rs"),
        },
    ];

    // A runner that records which clause IDs it was asked to execute.
    struct RecordingRunner {
        seen_ids: Arc<Mutex<Vec<String>>>,
    }
    impl Runner for RecordingRunner {
        fn run(&self, tests: &[GeneratedTest], _test_dir: &Path) -> anyhow::Result<RunResult> {
            let mut ids = self.seen_ids.lock().unwrap();
            for t in tests {
                ids.push(t.clause_id.0.clone());
            }
            Ok(RunResult { results: vec![], total_duration: Duration::ZERO })
        }
        fn is_available(&self) -> bool { true }
        fn name(&self) -> &str { "recording" }
    }

    let tmp = std::env::temp_dir()
        .join(format!("ought_filter_spec_{}", std::process::id()));
    std::fs::create_dir_all(&tmp).unwrap();

    let seen = Arc::new(Mutex::new(Vec::<String>::new()));
    let runner = RecordingRunner { seen_ids: Arc::clone(&seen) };

    // Filter to only the auth spec tests before invoking the runner.
    let auth_only: Vec<_> = all_tests.iter()
        .filter(|t| t.clause_id.0.starts_with("auth::"))
        .cloned()
        .collect();
    assert_eq!(auth_only.len(), 2,
        "test setup: should have exactly 2 auth tests to pass to the runner");

    runner.run(&auth_only, &tmp).expect("runner must not error");

    let seen_ids = seen.lock().unwrap().clone();
    assert_eq!(seen_ids.len(), 2,
        "runner must execute exactly the 2 tests from the filtered spec file, \
         not all 3 tests; got {seen_ids:?}");
    for id in &seen_ids {
        assert!(
            id.starts_with("auth::"),
            "runner must only execute clauses from the targeted spec file; \
             found unexpected clause: {id}"
        );
    }
    assert!(
        !seen_ids.iter().any(|id| id.starts_with("runner::")),
        "clauses from runner.ought.md must not be executed when only auth.ought.md is targeted"
    );

    let _ = std::fs::remove_dir_all(&tmp);
}


/// MUST BY 300s complete a full test suite execution (configurable via `ought.toml`)
#[test]
fn test_runner__execution__must_by_complete_a_full_test_suite_execution_configurable_via_ought() {
    use std::time::Instant;

    // A realistic runner that returns promptly — simulates a well-behaved harness.
    struct TimedRunner {
        simulated_duration: Duration,
    }
    impl Runner for TimedRunner {
        fn run(&self, tests: &[GeneratedTest], _test_dir: &Path) -> anyhow::Result<RunResult> {
            let results = tests.iter().map(|t| TestResult {
                clause_id: t.clause_id.clone(),
                status: TestStatus::Passed,
                message: None,
                duration: self.simulated_duration,
                details: TestDetails { measured_duration: Some(self.simulated_duration), ..Default::default() },
            }).collect();
            Ok(RunResult {
                results,
                total_duration: self.simulated_duration,
            })
        }
        fn is_available(&self) -> bool { true }
        fn name(&self) -> &str { "timed" }
    }

    let deadline = Duration::from_secs(300); // MUST BY deadline from the spec
    let tmp = std::env::temp_dir()
        .join(format!("ought_mustby_{}", std::process::id()));
    std::fs::create_dir_all(&tmp).unwrap();

    let tests: Vec<GeneratedTest> = (0..5).map(|i| GeneratedTest {
        clause_id: ClauseId(format!("runner::execution::clause_{i}")),
        code: String::new(),
        language: Language::Rust,
        file_path: PathBuf::from(format!("clause_{i}_test.rs")),
    }).collect();

    let wall_start = Instant::now();
    let result = TimedRunner { simulated_duration: Duration::from_millis(1) }
        .run(&tests, &tmp)
        .expect("runner must succeed");
    let wall_elapsed = wall_start.elapsed();

    // The suite must complete within the 300s MUST BY deadline.
    assert!(
        wall_elapsed < deadline,
        "full test suite execution must complete within 300s; elapsed: {wall_elapsed:?}"
    );

    // RunResult must carry a total_duration so the caller can enforce the deadline.
    assert!(
        result.total_duration <= deadline,
        "RunResult::total_duration must be within the 300s MUST BY deadline; got: {:?}",
        result.total_duration
    );

    // Per-result measured_duration must be populated for MUST BY clauses.
    for r in &result.results {
        assert!(
            r.details.measured_duration.is_some(),
            "each MUST BY clause result must carry TestDetails::measured_duration; \
             missing for clause {:?}", r.clause_id
        );
        let measured = r.details.measured_duration.unwrap();
        assert!(
            measured <= deadline,
            "per-clause measured_duration must be within the 300s deadline; \
             clause {:?} reported {measured:?}", r.clause_id
        );
    }

    let _ = std::fs::remove_dir_all(&tmp);
}


/// MUST NOT trigger generation -- the runner only executes existing generated tests
#[test]
fn test_runner__execution__must_not_trigger_generation_the_runner_only_executes_existing_generat() {
    // Set up an isolated temp directory that mimics the generated-test directory.
    let tmp = std::env::temp_dir()
        .join(format!("ought_no_gen_{}", std::process::id()));
    std::fs::create_dir_all(&tmp).unwrap();

    // Write a pre-existing generated test file.
    let existing_file = tmp.join("runner__execution__example_test.rs");
    let existing_code = "/// pre-generated\n\
        #[test]\n\
        fn test_runner__execution__example() { assert!(true); }\n";
    std::fs::write(&existing_file, existing_code).unwrap();

    // Snapshot the directory before running.
    let before_files: std::collections::BTreeSet<String> = std::fs::read_dir(&tmp)
        .unwrap()
        .filter_map(|e| e.ok())
        .map(|e| e.file_name().to_string_lossy().to_string())
        .collect();

    // A runner that only executes — never invokes a generator or LLM.
    struct ExecuteOnlyRunner;
    impl Runner for ExecuteOnlyRunner {
        fn run(&self, tests: &[GeneratedTest], test_dir: &Path) -> anyhow::Result<RunResult> {
            // Verify that the test files it is given already exist on disk;
            // if the runner were generating, they would not need to pre-exist.
            for t in tests {
                let full_path = test_dir.join(&t.file_path);
                assert!(
                    full_path.exists(),
                    "runner must execute pre-existing test files; \
                     if generation were triggered, this file would not yet exist: {full_path:?}"
                );
            }
            let results = tests.iter().map(|t| TestResult {
                clause_id: t.clause_id.clone(),
                status: TestStatus::Passed,
                message: None,
                duration: Duration::ZERO,
                details: TestDetails::default(),
            }).collect();
            Ok(RunResult { results, total_duration: Duration::ZERO })
        }
        fn is_available(&self) -> bool { true }
        fn name(&self) -> &str { "execute-only" }
    }

    let tests = vec![GeneratedTest {
        clause_id: ClauseId("runner::execution::example".to_string()),
        code: existing_code.to_string(),
        language: Language::Rust,
        file_path: PathBuf::from("runner__execution__example_test.rs"),
    }];

    ExecuteOnlyRunner.run(&tests, &tmp).expect("runner must not error");

    // After execution the directory must be identical to before: no new files,
    // no files removed — generation must not have been triggered.
    let after_files: std::collections::BTreeSet<String> = std::fs::read_dir(&tmp)
        .unwrap()
        .filter_map(|e| e.ok())
        .map(|e| e.file_name().to_string_lossy().to_string())
        .collect();

    assert_eq!(
        before_files, after_files,
        "runner must not create or remove any files (generation must not be triggered); \
         before: {before_files:?}, after: {after_files:?}"
    );

    // No ought.toml, manifest, or spec file must have been written.
    let generation_artifacts = ["ought.toml", "manifest.toml"];
    for artifact in &generation_artifacts {
        assert!(
            !tmp.join(artifact).exists(),
            "runner must not write generation artifact '{artifact}' during execution"
        );
    }

    let _ = std::fs::remove_dir_all(&tmp);
}


/// MUST NOT modify generated test files during execution
#[test]
fn test_runner__execution__must_not_modify_generated_test_files_during_execution() {
    struct ExecuteOnlyRunner;
    impl Runner for ExecuteOnlyRunner {
        fn run(&self, _tests: &[GeneratedTest], _test_dir: &Path) -> anyhow::Result<RunResult> {
            // Simulate execution without touching any test files.
            Ok(RunResult { results: vec![], total_duration: Duration::ZERO })
        }
        fn is_available(&self) -> bool { true }
        fn name(&self) -> &str { "execute-only" }
    }

    let tmp = std::env::temp_dir()
        .join(format!("ought_immutable_{}", std::process::id()));
    std::fs::create_dir_all(&tmp).unwrap();

    // Pre-populate the test directory with a generated test file.
    let test_file_name = "runner__execution__must_not_modify_test.rs";
    let test_file = tmp.join(test_file_name);
    let original_content = "/// MUST NOT modify generated test files during execution\n\
        #[test]\n\
        fn test_runner__execution__must_not_modify_generated_test_files_during_execution() {\n\
            assert!(true);\n\
        }\n";
    std::fs::write(&test_file, original_content).unwrap();

    let before_bytes = std::fs::read(&test_file).expect("test file must be readable before run");
    let before_mtime = std::fs::metadata(&test_file)
        .expect("test file metadata must be readable before run")
        .modified()
        .ok();
    let _ = before_mtime; // suppress unused warning

    let tests = vec![GeneratedTest {
        clause_id: ClauseId("runner::execution::must_not_modify_generated_test_files_during_execution".to_string()),
        code: original_content.to_string(),
        language: Language::Rust,
        file_path: PathBuf::from(test_file_name),
    }];

    ExecuteOnlyRunner.run(&tests, &tmp).expect("runner must not error");

    // Content must be byte-for-byte identical after execution.
    let after_bytes = std::fs::read(&test_file)
        .expect("test file must still exist after runner execution");
    assert_eq!(
        before_bytes, after_bytes,
        "runner must not alter the content of generated test files during execution"
    );

    // The file must still exist (runner must not delete it either).
    assert!(
        test_file.exists(),
        "runner must not delete generated test files during execution"
    );

    // No additional .rs files must have been written into the test directory.
    let rs_files_after: Vec<_> = std::fs::read_dir(&tmp)
        .unwrap()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().and_then(|x| x.to_str()) == Some("rs"))
        .collect();
    assert_eq!(
        rs_files_after.len(), 1,
        "runner must not create new .rs files in the test directory during execution; \
         found: {rs_files_after:?}"
    );

    let _ = std::fs::remove_dir_all(&tmp);
}


/// MUST invoke the configured test command from `ought.toml` for each language runner
#[test]
fn test_runner__execution__must_invoke_the_configured_test_command_from_ought_toml_for_each() {
    // Verify the runner factory recognises every supported language key and returns
    // a runner whose name matches the key used in ought.toml [runner.<name>] tables.
    let cases = [
        ("rust",       "rust"),
        ("python",     "python"),
        ("typescript", "typescript"),
        ("ts",         "typescript"),   // alias
        ("go",         "go"),
    ];
    for (input, expected_name) in cases {
        let runner = ought_run::runners::from_name(input)
            .unwrap_or_else(|e| panic!("from_name({input:?}) must succeed: {e}"));
        assert_eq!(
            runner.name(), expected_name,
            "runner for ought.toml key '{input}' must report name '{expected_name}'"
        );
    }

    // Verify that the runner sub-config preserves the configured command
    // strings when deserialized from the `[runner.*]` portion of `ought.toml`.
    // (The aggregate config struct lives in `ought-cli` and is tested there.)
    #[derive(serde::Deserialize)]
    struct RunnerOnly {
        runner: HashMap<String, RunnerConfig>,
    }

    let toml = r#"
[runner.rust]
command = "cargo test"
test_dir = "ought/ought-gen/"

[runner.python]
command = "pytest"
test_dir = "ought/ought-gen/"

[runner.typescript]
command = "npx jest --runInBand"
test_dir = "ought/ought-gen/"

[runner.go]
command = "go test ./..."
test_dir = "ought/ought-gen/"
"#;
    let parsed: RunnerOnly = toml::from_str(toml)
        .expect("ought.toml must load without error");

    let expected_commands = [
        ("rust",       "cargo test"),
        ("python",     "pytest"),
        ("typescript", "npx jest --runInBand"),
        ("go",         "go test ./..."),
    ];
    for (lang, expected_cmd) in expected_commands {
        let cfg = parsed.runner.get(lang)
            .unwrap_or_else(|| panic!("runner.{lang} config must be present in ought.toml"));
        assert_eq!(
            cfg.command, expected_cmd,
            "runner.{lang}.command must equal the value from ought.toml; \
             expected {expected_cmd:?}, got {:?}", cfg.command
        );
    }
}


/// MUST map individual test pass/fail results back to clause identifiers
#[test]
fn test_runner__execution__must_map_individual_test_pass_fail_results_back_to_clause_identif() {
    // Inline the bidirectional name<->ClauseId conversion that each runner implements.
    fn clause_id_to_test_name(id: &ClauseId) -> String {
        id.0.replace("::", "__")
    }
    fn test_name_to_clause_id(name: &str) -> ClauseId {
        ClauseId(name.replace("__", "::"))
    }

    // Three clauses that will appear in the harness output.
    let clause_ids = vec![
        ClauseId("runner::execution::must_invoke_command".to_string()),
        ClauseId("runner::execution::must_capture_output".to_string()),
        ClauseId("runner::execution::must_not_modify_files".to_string()),
    ];

    let mut name_to_clause: HashMap<String, ClauseId> = HashMap::new();
    for id in &clause_ids {
        name_to_clause.insert(clause_id_to_test_name(id), id.clone());
    }

    // Cargo test stdout with one pass, one fail, one ignored.
    let harness_stdout = "\
running 3 tests
test runner__execution__must_invoke_command ... ok
test runner__execution__must_capture_output ... FAILED
test runner__execution__must_not_modify_files ... ignored

test result: FAILED. 1 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out
";

    let mut results: Vec<TestResult> = Vec::new();
    for line in harness_stdout.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix("test ") {
            if let Some((name_part, status_part)) = rest.rsplit_once(" ... ") {
                let test_name = name_part.trim();
                let status = match status_part.trim() {
                    "ok"      => TestStatus::Passed,
                    "FAILED"  => TestStatus::Failed,
                    "ignored" => TestStatus::Skipped,
                    _         => TestStatus::Errored,
                };
                let clause_id = name_to_clause
                    .get(test_name)
                    .cloned()
                    .unwrap_or_else(|| test_name_to_clause_id(test_name));
                results.push(TestResult {
                    clause_id,
                    status,
                    message: None,
                    duration: Duration::ZERO,
                    details: TestDetails::default(),
                });
            }
        }
    }

    assert_eq!(results.len(), 3, "must produce exactly one result per test line in harness output");

    let invoke = results.iter()
        .find(|r| r.clause_id.0 == "runner::execution::must_invoke_command")
        .expect("must_invoke_command ClauseId must appear in mapped results");
    assert_eq!(invoke.status, TestStatus::Passed,
        "'ok' output line must map to Passed on clause runner::execution::must_invoke_command");

    let capture = results.iter()
        .find(|r| r.clause_id.0 == "runner::execution::must_capture_output")
        .expect("must_capture_output ClauseId must appear in mapped results");
    assert_eq!(capture.status, TestStatus::Failed,
        "'FAILED' output line must map to Failed on clause runner::execution::must_capture_output");

    let modify = results.iter()
        .find(|r| r.clause_id.0 == "runner::execution::must_not_modify_files")
        .expect("must_not_modify_files ClauseId must appear in mapped results");
    assert_eq!(modify.status, TestStatus::Skipped,
        "'ignored' output line must map to Skipped on clause runner::execution::must_not_modify_files");

    // Verify round-trip: every test-function name converts to a valid ClauseId and back.
    for id in &clause_ids {
        let name = clause_id_to_test_name(id);
        let recovered = test_name_to_clause_id(&name);
        assert_eq!(recovered, *id,
            "clause_id -> test_name -> clause_id round-trip must be lossless for {id:?}");
    }
}


/// MUST pass the generated test files/directory to the test harness
#[test]
fn test_runner__execution__must_pass_the_generated_test_files_directory_to_the_test_harness() {
    use std::sync::{Arc, Mutex};

    // A runner that records the test_dir it receives — we verify the exact path
    // is forwarded rather than silently dropped or substituted.
    struct RecordingRunner {
        captured_dir: Arc<Mutex<Option<PathBuf>>>,
        captured_file_paths: Arc<Mutex<Vec<PathBuf>>>,
    }
    impl Runner for RecordingRunner {
        fn run(&self, tests: &[GeneratedTest], test_dir: &Path) -> anyhow::Result<RunResult> {
            *self.captured_dir.lock().unwrap() = Some(test_dir.to_path_buf());
            let mut paths = self.captured_file_paths.lock().unwrap();
            for t in tests {
                paths.push(test_dir.join(&t.file_path));
            }
            Ok(RunResult { results: vec![], total_duration: Duration::ZERO })
        }
        fn is_available(&self) -> bool { true }
        fn name(&self) -> &str { "recording" }
    }

    let test_dir = std::env::temp_dir()
        .join(format!("ought_pass_dir_{}", std::process::id()));
    std::fs::create_dir_all(&test_dir).unwrap();

    let captured_dir = Arc::new(Mutex::new(None));
    let captured_paths = Arc::new(Mutex::new(vec![]));
    let runner = RecordingRunner {
        captured_dir: Arc::clone(&captured_dir),
        captured_file_paths: Arc::clone(&captured_paths),
    };

    let tests = vec![GeneratedTest {
        clause_id: ClauseId("runner::execution::must_pass_dir".to_string()),
        code: "#[test] fn test_runner__execution__must_pass_dir() {}".to_string(),
        language: Language::Rust,
        file_path: PathBuf::from("runner/execution/must_pass_dir_test.rs"),
    }];

    runner.run(&tests, &test_dir).expect("runner must not error");

    // The exact test_dir must arrive at the runner unchanged.
    let actual_dir = captured_dir.lock().unwrap().clone();
    assert_eq!(
        actual_dir.as_deref(),
        Some(test_dir.as_path()),
        "runner must receive the exact test_dir path from the caller; \
         expected {test_dir:?}, got {actual_dir:?}"
    );

    // Every generated-test file path must be rooted within that test_dir.
    let paths = captured_paths.lock().unwrap().clone();
    assert!(!paths.is_empty(), "runner must receive at least one test file path");
    for p in &paths {
        assert!(
            p.starts_with(&test_dir),
            "every test file path passed to the harness must be inside test_dir; \
             {p:?} is not under {test_dir:?}"
        );
    }

    let _ = std::fs::remove_dir_all(&test_dir);
}


/// OTHERWISE: kill the test harness process and report a timeout error
#[test]
fn test_runner__execution__otherwise_kill_the_test_harness_process_and_report_a_timeout_error() {
    use std::sync::mpsc;

    // A runner that deliberately hangs -- simulating a hung test harness process.
    struct HangingRunner {
        hang_for: Duration,
    }
    impl Runner for HangingRunner {
        fn run(&self, _tests: &[GeneratedTest], _test_dir: &Path) -> anyhow::Result<RunResult> {
            std::thread::sleep(self.hang_for);
            anyhow::bail!("runner timed out; harness did not finish within deadline")
        }
        fn is_available(&self) -> bool { true }
        fn name(&self) -> &str { "hanging" }
    }

    let timeout = Duration::from_millis(60);    // simulated MUST BY deadline
    let hang_for = Duration::from_millis(500);  // runner runs far longer than the deadline

    let (tx, rx) = mpsc::channel::<anyhow::Result<RunResult>>();

    std::thread::spawn(move || {
        let tmp = std::env::temp_dir()
            .join(format!("ought_kill_hang_{}", std::process::id()));
        std::fs::create_dir_all(&tmp).ok();
        let result = HangingRunner { hang_for }.run(&[], &tmp);
        let _ = tx.send(result);
        let _ = std::fs::remove_dir_all(&tmp);
    });

    // The enforcement layer waits up to `timeout`; if the runner hasn't finished,
    // it must be killed and a timeout error must be reported.
    match rx.recv_timeout(timeout) {
        Err(mpsc::RecvTimeoutError::Timeout) => {
            // Expected: the deadline fired before the runner completed.
            // A compliant implementation would at this point:
            //   1. Send SIGKILL (or Child::kill()) to the harness process.
            //   2. Return Err(anyhow!("test suite timed out after <deadline>")) to the caller.
            // The test confirms that the timeout mechanism fires correctly so the
            // OTHERWISE branch can execute.
        }
        Ok(Ok(_)) => {
            panic!(
                "a runner that hangs for {hang_for:?} must not complete within the \
                 {timeout:?} MUST BY deadline; the harness process must be killed and a \
                 timeout error reported instead"
            );
        }
        Ok(Err(_)) => {
            // The runner itself errored before the timeout — also acceptable, since it
            // means the harness did not run past the deadline unchecked.
        }
        Err(mpsc::RecvTimeoutError::Disconnected) => {
            panic!("runner thread disconnected unexpectedly");
        }
    }
}


/// MUST capture stdout, stderr, and exit code from the test harness
#[test]
fn test_runner__execution__must_capture_stdout_stderr_and_exit_code_from_the_test_harness() {
    // A runner that faithfully models the three capture channels:
    //   stdout  -> parsed test results
    //   stderr  -> failure/error messages
    //   exit code -> overall pass/fail signal
    struct CapturingRunner {
        harness_stderr: String,
        harness_exit_success: bool,
    }
    impl Runner for CapturingRunner {
        fn run(&self, tests: &[GeneratedTest], _test_dir: &Path) -> anyhow::Result<RunResult> {
            if !self.harness_exit_success {
                // Non-zero exit: report all tests as Errored and store captured stderr.
                let err = self.harness_stderr.trim().to_string();
                let results = tests.iter().map(|t| TestResult {
                    clause_id: t.clause_id.clone(),
                    status: TestStatus::Errored,
                    message: Some(format!("test harness failed: {err}")),
                    duration: Duration::ZERO,
                    details: TestDetails {
                        failure_message: Some(err.clone()),
                        ..Default::default()
                    },
                }).collect();
                return Ok(RunResult { results, total_duration: Duration::ZERO });
            }
            // Zero exit: tests passed; stdout was parsed but no failures to report.
            let results = tests.iter().map(|t| TestResult {
                clause_id: t.clause_id.clone(),
                status: TestStatus::Passed,
                message: None,
                duration: Duration::ZERO,
                details: TestDetails::default(),
            }).collect();
            Ok(RunResult { results, total_duration: Duration::ZERO })
        }
        fn is_available(&self) -> bool { true }
        fn name(&self) -> &str { "capturing" }
    }

    let tmp = std::env::temp_dir()
        .join(format!("ought_capture_{}", std::process::id()));
    std::fs::create_dir_all(&tmp).unwrap();

    let tests = vec![GeneratedTest {
        clause_id: ClauseId("runner::execution::clause_under_test".to_string()),
        code: String::new(),
        language: Language::Rust,
        file_path: PathBuf::from("test.rs"),
    }];

    // Scenario A: harness exits non-zero -> stderr content must reach TestDetails.
    let failing = CapturingRunner {
        harness_stderr: "error[E0001]: cannot compile `my-crate`\n  --> src/lib.rs:3".to_string(),
        harness_exit_success: false,
    };
    let result = failing.run(&tests, &tmp).expect("runner must return Ok even on harness failure");
    assert_eq!(result.results.len(), 1);
    assert_eq!(result.results[0].status, TestStatus::Errored,
        "non-zero exit code must map to TestStatus::Errored");
    let detail = result.results[0].details.failure_message.as_deref().unwrap_or("");
    assert!(
        detail.contains("cannot compile"),
        "captured stderr must be stored verbatim in TestDetails::failure_message; got: {detail:?}"
    );

    // Scenario B: harness exits zero -> results must be Passed.
    let passing = CapturingRunner {
        harness_stderr: String::new(),
        harness_exit_success: true,
    };
    let result = passing.run(&tests, &tmp).expect("runner must return Ok");
    assert_eq!(result.results[0].status, TestStatus::Passed,
        "zero exit code must map to TestStatus::Passed");
    assert!(
        result.results[0].details.failure_message.is_none(),
        "a successful harness run must not populate failure_message"
    );

    let _ = std::fs::remove_dir_all(&tmp);
}

// =============================================================================
// runner / result_collection
// =============================================================================

