//! Generated tests for the `language_runners` subsection of the `runner` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

#![allow(dead_code, clippy::all)]
#![allow(non_snake_case, unused_imports)]
use std::path::{Path, PathBuf};
use std::fs;
use std::time::Duration;
use std::collections::HashMap;
use ought_spec::ClauseId;
use ought_run::RunnerConfig;
use ought_gen::GeneratedTest;
use ought_gen::generator::Language;
use ought_run::{TestResult, TestStatus, TestDetails, RunResult};
use ought_run::runner::Runner;
use ought_run::runners;

// =============================================================================
// runner / language_runners
// =============================================================================

/// MUST ship with a Rust runner
///
/// The runner must include a Rust language runner that delegates to `cargo test`.
/// Being a MUST clause, the runner must exist, be accessible by name, and since
/// these tests are themselves compiled with cargo, the harness must also be available.

/// MUST ship with a Rust runner
///
/// The runner must include a Rust language runner that delegates to `cargo test`.
/// Being a MUST clause, the runner must exist, be accessible by name, and since
/// these tests are themselves compiled with cargo, the harness must also be available.
#[test]
fn test_runner__language_runners__must_ship_with_a_rust_runner() {
    // The factory must recognise "rust" as a valid language key.
    let runner = ought_run::runners::from_name("rust")
        .expect("from_name(\"rust\") must succeed — Rust runner is required");

    assert_eq!(
        runner.name(),
        "rust",
        "Rust runner must report name \"rust\""
    );

    // Because these tests are compiled and run with cargo, the harness is
    // definitionally available in this environment.
    assert!(
        runner.is_available(),
        "Rust runner must report is_available() == true when cargo is on PATH \
         (this test suite is itself running under cargo)"
    );
}


/// SHOULD ship with a Python runner
///
/// The runner should include a Python language runner that delegates to `pytest`.
/// The runner implementation must exist and be reachable by name; availability
/// in the current environment (i.e. whether pytest is installed) is separate.
#[test]
fn test_runner__language_runners__should_ship_with_a_python_runner() {
    // The factory must recognise "python" as a valid language key.
    let runner = ought_run::runners::from_name("python")
        .expect("from_name(\"python\") must succeed — Python runner should be shipped");

    assert_eq!(
        runner.name(),
        "python",
        "Python runner must report name \"python\""
    );

    // is_available() reflects whether pytest is installed in this environment —
    // that is not required for the runner to ship.  We just verify the method
    // exists and returns a bool without panicking.
    let _ = runner.is_available();
}


/// SHOULD ship with a JavaScript/TypeScript runner
///
/// The runner should include a TypeScript/JavaScript runner that delegates to
/// `npx jest --verbose`.  Both "typescript" and the "ts" alias must be recognised.
#[test]
fn test_runner__language_runners__should_ship_with_a_javascript_typescript_runner() {
    // Primary name must be recognised.
    let runner = ought_run::runners::from_name("typescript")
        .expect("from_name(\"typescript\") must succeed — TS/JS runner should be shipped");

    assert_eq!(
        runner.name(),
        "typescript",
        "TypeScript runner must report name \"typescript\""
    );

    // "ts" is the documented short alias — it must resolve to the same runner.
    let runner_alias = ought_run::runners::from_name("ts")
        .expect("from_name(\"ts\") must succeed — \"ts\" is the short alias for the TS runner");

    assert_eq!(
        runner_alias.name(),
        "typescript",
        "\"ts\" alias must resolve to a runner named \"typescript\""
    );

    // Availability depends on whether npx is installed; just confirm no panic.
    let _ = runner.is_available();
}


/// SHOULD support custom runners via the `[runner.<name>]` config in `ought.toml`
///
/// Any arbitrary runner name used as `[runner.<name>]` in `ought.toml` must be
/// preserved in the parsed `Config::runner` map with its `command` and `test_dir`
/// values intact.  The runner map is keyed by the name from the TOML table header,
/// so custom names are fully round-tripped through config parsing.
#[test]
fn test_runner__language_runners__should_support_custom_runners_via_the_runner_name_config_in_ought_t() {
    // Test harness mirrors just the part of `ought.toml` this test cares about:
    // arbitrary `[runner.<name>]` tables deserialize into `RunnerConfig`. The
    // aggregate config struct lives in `ought-cli` and is tested there.
    #[derive(serde::Deserialize)]
    struct RunnerOnly {
        runner: HashMap<String, RunnerConfig>,
    }

    let toml = r#"
[runner.rust]
command = "cargo test"
test_dir = "ought/ought-gen/"

[runner.my-ruby-runner]
command = "bundle exec rspec"
test_dir = "spec/ought/"

[runner.dotnet]
command = "dotnet test"
test_dir = "tests/ought/"
"#;

    let parsed: RunnerOnly = toml::from_str(toml)
        .expect("ought.toml with custom [runner.*] sections must load without error");

    // Built-in runner name is preserved.
    let rust_cfg = parsed.runner.get("rust")
        .expect("runner.rust must be present in parsed config");
    assert_eq!(rust_cfg.command, "cargo test");

    // Fully custom runner name is preserved with its command.
    let ruby_cfg = parsed.runner.get("my-ruby-runner")
        .expect("runner.my-ruby-runner must be present — custom runner names must be supported");
    assert_eq!(
        ruby_cfg.command, "bundle exec rspec",
        "custom runner command must round-trip through config parsing"
    );
    assert_eq!(
        ruby_cfg.test_dir.to_string_lossy(),
        "spec/ought/",
        "custom runner test_dir must round-trip through config parsing"
    );

    // A second custom name also round-trips correctly.
    let dotnet_cfg = parsed.runner.get("dotnet")
        .expect("runner.dotnet must be present — arbitrary runner names must be supported");
    assert_eq!(dotnet_cfg.command, "dotnet test");

    // The total number of runners matches what was declared.
    assert_eq!(
        parsed.runner.len(),
        3,
        "all three [runner.*] sections must be parsed; found {:?}",
        parsed.runner.keys().collect::<Vec<_>>()
    );
}


/// MAY ship with a Go runner
///
/// The runner may optionally include a Go language runner that delegates to
/// `go test -v ./...`.  If it ships, it must be accessible via `from_name("go")`
/// and report the correct name; this test verifies that the shipped binary
/// includes the Go runner.
#[test]
fn test_runner__language_runners__may_ship_with_a_go_runner() {
    // The Go runner is optional (MAY), but the codebase does ship one.
    // Verify that `from_name` accepts "go" without error.
    let result = ought_run::runners::from_name("go");

    assert!(
        result.is_ok(),
        "from_name(\"go\") must succeed because the Go runner is included in this build; \
         error: {:?}",
        result.err()
    );

    let runner = result.unwrap();
    assert_eq!(
        runner.name(),
        "go",
        "Go runner must report name \"go\""
    );

    // Availability reflects whether `go` is installed — not a shipping requirement.
    let _ = runner.is_available();
}

// =============================================================================
// runner / error_handling
// =============================================================================

