//! Generated tests for the `language_runners` subsection of the `runner` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.
//! (Hand-updated once for the generic-CLI-runner refactor; safe to regenerate.)

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]

use std::path::{Path, PathBuf};
use std::fs;
use std::time::Duration;
use std::collections::HashMap;
use ought_spec::ClauseId;
use ought_run::RunnerConfig;
use ought_gen::GeneratedTest;
use ought_gen::generator::Language;
use ought_run::{TestResult, TestStatus, TestDetails, RunResult};
use ought_run::runner::Runner;
use ought_run::runners;

/// Build a runner for the given preset name by filling in a test_dir over
/// the preset config — matches the minimal `[runner.<name>]` form users write.
fn runner_for(lang: &str) -> anyhow::Result<Box<dyn Runner>> {
    let cfg = RunnerConfig {
        test_dir: Some(PathBuf::from("ought/ought-gen/")),
        ..Default::default()
    };
    runners::from_config(lang, &cfg, Path::new("."))
}

// =============================================================================
// runner / language_runners
// =============================================================================

/// MUST ship with a Rust runner
///
/// The runner must include a Rust language runner that delegates to a cargo-
/// driven harness. Being a MUST clause, the runner must exist and be
/// accessible via the "rust" preset.
#[test]
fn test_runner__language_runners__must_ship_with_a_rust_runner() {
    let runner = runner_for("rust")
        .expect("rust preset must resolve into a runner — Rust runner is required");

    assert_eq!(
        runner.name(),
        "rust",
        "Rust runner must report name \"rust\""
    );

    // Because these tests are compiled and run with cargo, the cargo harness
    // is definitionally available in this environment.
    assert!(
        runner.is_available(),
        "Rust runner must report is_available() == true when cargo is on PATH \
         (this test suite is itself running under cargo)"
    );
}

/// SHOULD ship with a Python runner
#[test]
fn test_runner__language_runners__should_ship_with_a_python_runner() {
    let runner = runner_for("python")
        .expect("python preset must resolve into a runner");

    assert_eq!(
        runner.name(),
        "python",
        "Python runner must report name \"python\""
    );

    // is_available() reflects whether pytest is installed — that is not a
    // shipping requirement.
    let _ = runner.is_available();
}

/// SHOULD ship with a JavaScript/TypeScript runner
#[test]
fn test_runner__language_runners__should_ship_with_a_javascript_typescript_runner() {
    let runner = runner_for("typescript")
        .expect("typescript preset must resolve into a runner");

    assert_eq!(
        runner.name(),
        "typescript",
        "TypeScript runner must report name \"typescript\""
    );

    // "ts" is the documented short alias — it must resolve the same preset.
    let runner_alias = runner_for("ts")
        .expect("\"ts\" is the short alias for the TS preset");

    assert_eq!(
        runner_alias.name(),
        "ts",
        "runner built from the 'ts' section must report its section name"
    );
    // Both should derive from the same preset config.
    let ts_preset = ought_run::presets::preset("ts").expect("ts preset exists");
    let typescript_preset = ought_run::presets::preset("typescript").expect("typescript preset exists");
    assert_eq!(
        ts_preset.command, typescript_preset.command,
        "'ts' and 'typescript' must map to the same underlying preset command"
    );

    let _ = runner.is_available();
}

/// SHOULD support custom runners via the `[runner.<name>]` config in `ought.toml`
#[test]
fn test_runner__language_runners__should_support_custom_runners_via_the_runner_name_config_in_ought_t() {
    // Arbitrary `[runner.<name>]` tables deserialize into `RunnerConfig`. The
    // aggregate config struct lives in `ought-cli` and is tested there.
    #[derive(serde::Deserialize)]
    struct RunnerOnly {
        runner: HashMap<String, RunnerConfig>,
    }

    let toml = r#"
[runner.rust]
test_dir = "ought/ought-gen/"

[runner.my-ruby-runner]
command = "bundle exec rspec --format=junit --out={junit_path}"
test_dir = "spec/ought/"
format = "junit-xml"
file_extensions = ["rb"]

[runner.dotnet]
command = "dotnet test --logger junit;LogFilePath={junit_path}"
test_dir = "tests/ought/"
format = "junit-xml"
file_extensions = ["cs"]
"#;

    let parsed: RunnerOnly = toml::from_str(toml)
        .expect("ought.toml with custom [runner.*] sections must load without error");

    // Built-in runner name is preserved and resolves via its preset.
    let rust_cfg = parsed.runner.get("rust")
        .expect("runner.rust must be present in parsed config");
    let rust_resolved = rust_cfg.resolve("rust").expect("rust cfg must resolve via preset");
    assert!(rust_resolved.command.contains("cargo"),
        "rust preset command must invoke cargo; got {:?}", rust_resolved.command);

    // Fully custom runner name is preserved with its command.
    let ruby_cfg = parsed.runner.get("my-ruby-runner")
        .expect("runner.my-ruby-runner must be present — custom runner names must be supported");
    assert_eq!(
        ruby_cfg.command.as_deref(),
        Some("bundle exec rspec --format=junit --out={junit_path}"),
        "custom runner command must round-trip through config parsing"
    );
    assert_eq!(
        ruby_cfg.test_dir.as_ref().unwrap().to_string_lossy(),
        "spec/ought/",
        "custom runner test_dir must round-trip through config parsing"
    );

    // A second custom name also round-trips correctly.
    let dotnet_cfg = parsed.runner.get("dotnet")
        .expect("runner.dotnet must be present — arbitrary runner names must be supported");
    assert_eq!(
        dotnet_cfg.command.as_deref(),
        Some("dotnet test --logger junit;LogFilePath={junit_path}")
    );

    // The total number of runners matches what was declared.
    assert_eq!(
        parsed.runner.len(),
        3,
        "all three [runner.*] sections must be parsed; found {:?}",
        parsed.runner.keys().collect::<Vec<_>>()
    );
}

/// MAY ship with a Go runner
#[test]
fn test_runner__language_runners__may_ship_with_a_go_runner() {
    // The Go runner is optional (MAY), but the codebase does ship a preset.
    let result = runner_for("go");

    assert!(
        result.is_ok(),
        "go preset must resolve; error: {:?}",
        result.err()
    );

    let runner = result.unwrap();
    assert_eq!(
        runner.name(),
        "go",
        "Go runner must report name \"go\""
    );

    // Availability reflects whether `gotestsum` (the preset default) is on PATH.
    let _ = runner.is_available();
}

// =============================================================================
// runner / error_handling
// =============================================================================
